/**
 * Curated opportunities seed.
 *
 * Covers OpportunityType values not well-served by automated importers:
 * SUMMER_PROGRAM, BOOTCAMP, CONFERENCE, FELLOWSHIP (prestige), EXCHANGE, RESEARCH.
 *
 * All entries are verified=true and source='curated'.
 * Run: npx ts-node --transpile-only prisma/seeds/curated-opportunities.ts
 *
 * Update annually (June–July) for summer programs; December for fellowships.
 */
import { upsertManualOpportunity } from '../../src/services/import/manual.import';
import { logger } from '../../src/utils/logger';

const opportunities = [

  // ── SUMMER PROGRAMS (Italian) ──────────────────────────────────────────────

  {
    title: 'H-Farm Summer School — Digital Innovation & Entrepreneurship',
    description: 'H-Farm Summer School offre programmi intensivi su digital innovation, startup building e business design nel campus di Roncade (Treviso). Partecipanti dai 16 ai 25 anni. Residenziale, include alloggio e pasti. Ideale per chi vuole costruire il proprio progetto imprenditoriale in ambiente internazionale.',
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://www.h-farm.com/en/education/h-farm-schools/h-farm-summer-school',
    organizer: 'H-Farm',
    location: 'Roncade, Italy',
    city: 'Roncade',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 14,
    cost: 2500,
    hasScholarship: false,
    eligibleFields: ['BUSINESS', 'COMPUTER_SCIENCE', 'DESIGN'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'entrepreneurship', 'startup', 'italy', 'h-farm'],
    sourceId: 'curated-hfarm-summer-school',
  },

  {
    title: 'Bocconi Summer School — Business & Economics',
    description: "Bocconi University's summer programs cover finance, management, marketing, and economics. Held in Milan, they combine lectures by Bocconi faculty with case studies and company visits. Programs run 1–3 weeks. Financial aid available for outstanding applicants.",
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://www.unibocconi.eu/wps/wcm/connect/bocconi/sitopubblico_en/navigation+tree/home/programs/summer+school',
    organizer: 'Università Bocconi',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 14,
    cost: 3200,
    hasScholarship: true,
    scholarshipDetails: 'Merit-based scholarships covering 50–100% of tuition available.',
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'LAW'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'business', 'economics', 'milan', 'bocconi'],
    sourceId: 'curated-bocconi-summer-school',
  },

  {
    title: 'Politecnico di Milano Summer School — Engineering & Design',
    description: "Polimi's international summer schools cover architecture, industrial design, and engineering. Courses are taught in English, attracting students from over 60 countries. Located in Milan's vibrant design district.",
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://www.polimi.it/en/educational-offer/summer-schools/',
    organizer: 'Politecnico di Milano',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 10,
    cost: 2000,
    hasScholarship: false,
    eligibleFields: ['ENGINEERING', 'DESIGN', 'ARCHITECTURE', 'COMPUTER_SCIENCE'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'engineering', 'design', 'milan', 'polimi'],
    sourceId: 'curated-polimi-summer-school',
  },

  {
    title: 'LUISS Summer School — Law, Political Science & International Relations',
    description: "LUISS Guido Carli's summer programs focus on European law, international relations, and political economy. Held in Rome, with visits to EU institutions and diplomatic venues. Taught in English.",
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://summerschool.luiss.it/',
    organizer: 'LUISS Guido Carli',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 14,
    cost: 2800,
    hasScholarship: true,
    scholarshipDetails: 'Need-based grants available for Italian and international students.',
    eligibleFields: ['LAW', 'POLITICAL_SCIENCE', 'ECONOMICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'law', 'political-science', 'rome', 'luiss'],
    sourceId: 'curated-luiss-summer-school',
  },

  {
    title: 'SDA Bocconi Executive Summer Program — Leadership & Innovation',
    description: 'SDA Bocconi School of Management summer programs are aimed at ambitious undergraduates and recent graduates looking to develop leadership and innovation skills. Intensive 1-week format with business simulations.',
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://www.sdabocconi.it/en/programs/executive-education/open-programs',
    organizer: 'SDA Bocconi School of Management',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 7,
    cost: 1800,
    hasScholarship: false,
    eligibleFields: ['BUSINESS', 'ECONOMICS'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'business', 'leadership', 'milan', 'sda-bocconi'],
    sourceId: 'curated-sda-bocconi-summer',
  },

  // ── BOOTCAMPS ──────────────────────────────────────────────────────────────

  {
    title: '42 Roma Luiss — Coding Bootcamp (Piscine)',
    description: "42 Roma Luiss offers a 4-week intensive coding bootcamp called the 'Piscine' — a peer-learning, project-based program with no prior programming experience required. Completely free, no tuition. Top performers are invited to join the full 3-year program.",
    type: 'BOOTCAMP' as const,
    url: 'https://42roma.it/',
    organizer: '42 Roma Luiss',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 28,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['bootcamp', 'coding', 'programming', 'rome', '42-network', 'free'],
    sourceId: 'curated-42-roma-piscine',
  },

  {
    title: 'Codemotion Tech Conference & Workshop — Milan',
    description: "Italy's largest tech community event. Codemotion Milan features 100+ talks, workshops, and hands-on labs on software engineering, cloud, AI, and DevOps. Mix of free tickets (online stream) and paid in-person passes.",
    type: 'BOOTCAMP' as const,
    url: 'https://conferences.codemotion.com/milan/',
    organizer: 'Codemotion',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    durationDays: 2,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['bootcamp', 'conference', 'tech', 'milan', 'codemotion', 'networking'],
    sourceId: 'curated-codemotion-milan',
  },

  // ── CONFERENCES ────────────────────────────────────────────────────────────

  {
    title: 'Web Marketing Festival — Rimini',
    description: "Il WMF è il più grande evento italiano sull'innovazione digitale, marketing, AI e startup. Tre giorni di talk, workshop, e networking a Rimini con oltre 60.000 partecipanti. Accesso gratuito con registrazione anticipata.",
    type: 'CONFERENCE' as const,
    url: 'https://www.webmarketingfestival.it/',
    organizer: 'Web Marketing Festival',
    location: 'Rimini, Italy',
    city: 'Rimini',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 3,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['BUSINESS', 'COMPUTER_SCIENCE', 'DESIGN'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['conference', 'marketing', 'digital', 'innovation', 'rimini', 'free'],
    sourceId: 'curated-wmf-rimini',
  },

  {
    title: 'TEDxMilano',
    description: 'TEDxMilano riunisce speaker, innovatori e creativi in un formato ispirato ai TED Talks. Ogni edizione esplora temi trasversali: tecnologia, scienze, arti, business e imprenditoria sociale. Ideale per studenti universitari alla ricerca di ispirazione e networking.',
    type: 'CONFERENCE' as const,
    url: 'https://tedxmilano.com/',
    organizer: 'TEDxMilano',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 1,
    cost: 50,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['conference', 'ted', 'talks', 'innovation', 'milan', 'networking'],
    sourceId: 'curated-tedx-milan',
  },

  // ── FELLOWSHIPS (prestige, international) ──────────────────────────────────

  {
    title: 'Schwarzman Scholars Program — Beijing',
    description: "The Schwarzman Scholars program at Tsinghua University in Beijing is a highly selective 1-year master's program designed to develop future global leaders. Full funding including tuition, accommodation, travel, and living stipend. Open to students aged 18-28.",
    type: 'FELLOWSHIP' as const,
    url: 'https://www.schwarzmanscholars.org/',
    organizer: 'Schwarzman Scholars',
    location: 'Beijing, China',
    city: 'Beijing',
    country: 'CN',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 365,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Fully funded: tuition, accommodation, travel, and $4,000 personal stipend.',
    stipend: 4000,
    eligibleFields: [] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['fellowship', 'fully-funded', 'leadership', 'global', 'china', 'masters'],
    sourceId: 'curated-schwarzman-scholars',
  },

  {
    title: 'Rhodes Scholarship — Oxford University',
    description: 'The Rhodes Scholarship is the oldest and most celebrated international fellowship, funding postgraduate study at the University of Oxford. Open to students aged 19–25. Fully funded: university fees, living allowance, and airfare.',
    type: 'FELLOWSHIP' as const,
    url: 'https://www.rhodeshouse.ox.ac.uk/scholarships/',
    organizer: 'Rhodes Trust',
    location: 'Oxford, United Kingdom',
    city: 'Oxford',
    country: 'GB',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Fully funded: Oxford fees, living allowance (£18,180/year), and return airfare.',
    eligibleFields: [] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['fellowship', 'fully-funded', 'oxford', 'uk', 'postgraduate', 'prestige'],
    sourceId: 'curated-rhodes-scholarship',
  },

  {
    title: 'Harvard HPAIR — Asia Pacific Student Leaders Conference',
    description: 'Harvard Project for Asian and International Relations (HPAIR) brings together 600+ student leaders from 50+ countries for a week-long conference in Asia. Focus: leadership, international policy, business, and technology. Partial need-based financial aid available.',
    type: 'CONFERENCE' as const,
    url: 'https://www.hpair.org/',
    organizer: 'Harvard HPAIR',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 7,
    cost: 800,
    hasScholarship: true,
    scholarshipDetails: 'Need-based financial aid available for delegates.',
    eligibleFields: [] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['conference', 'leadership', 'international', 'harvard', 'asia', 'networking'],
    sourceId: 'curated-harvard-hpair',
  },

  // ── EXCHANGE PROGRAMS ──────────────────────────────────────────────────────

  {
    title: 'IAESTE Internship Exchange — International Science & Engineering',
    description: 'IAESTE (International Association for the Exchange of Students for Technical Experience) places science, engineering, and technology students in paid work placements abroad. 80+ countries, 6–12 week programs. Free to apply; host company covers living costs.',
    type: 'EXCHANGE' as const,
    url: 'https://www.iaeste.org/',
    organizer: 'IAESTE',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 56,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ENGINEERING', 'COMPUTER_SCIENCE', 'PHYSICAL_SCIENCES', 'LIFE_SCIENCES', 'MATHEMATICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 5,
    tags: ['exchange', 'internship', 'engineering', 'science', 'international', 'paid'],
    sourceId: 'curated-iaeste-exchange',
  },

  {
    title: 'Fondazione Intercultura — AFS Exchange Program',
    description: 'Intercultura/AFS offre scambi culturali da 1 mese a 1 anno in oltre 50 paesi. Programmi high school e undergraduate, con borse di studio parziali e totali offerte da enti pubblici e privati. Uno dei programmi di scambio più longevi e riconosciuti al mondo.',
    type: 'EXCHANGE' as const,
    url: 'https://www.intercultura.it/',
    organizer: 'Fondazione Intercultura / AFS Italia',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 3000,
    hasScholarship: true,
    scholarshipDetails: 'Borse di studio parziali e totali disponibili tramite convenzioni con enti locali.',
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 4,
    tags: ['exchange', 'cultural', 'international', 'scholarship', 'afs'],
    sourceId: 'curated-intercultura-afs',
  },

  // ── RESEARCH PROGRAMS ──────────────────────────────────────────────────────

  {
    title: 'CERN Summer Student Programme',
    description: "CERN's Summer Student Programme offers undergraduate students in physics, computing, and engineering the opportunity to work at the world's largest particle physics laboratory in Geneva. 8–13 weeks, fully paid (CHF 91/day + housing). Applications open November–January.",
    type: 'RESEARCH' as const,
    url: 'https://home.cern/summer-student-programme',
    organizer: 'CERN',
    location: 'Geneva, Switzerland',
    city: 'Geneva',
    country: 'CH',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 63,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Daily allowance CHF 91 + free on-site accommodation in the CERN hostel.',
    stipend: 91,
    eligibleFields: ['PHYSICAL_SCIENCES', 'COMPUTER_SCIENCE', 'ENGINEERING', 'MATHEMATICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 5,
    tags: ['research', 'physics', 'cern', 'geneva', 'paid', 'stem'],
    sourceId: 'curated-cern-summer',
  },

  {
    title: 'EMBO Short-Term Fellowship — Molecular Biology',
    description: 'EMBO Short-Term Fellowships fund visits of up to 3 months to European molecular biology labs for collaborative research. Open to PhD students and postdocs. Covers travel and living expenses. Applications accepted year-round.',
    type: 'RESEARCH' as const,
    url: 'https://www.embo.org/funding/fellowships-awards-and-grants/short-term-fellowships/',
    organizer: 'EMBO',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 60,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Covers travel and living costs for 1–3 months abroad.',
    eligibleFields: ['LIFE_SCIENCES', 'MEDICINE'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['research', 'biology', 'molecular', 'embo', 'europe', 'phd', 'paid'],
    sourceId: 'curated-embo-short-term',
  },

  {
    title: 'DAAD Research Internship in Science & Engineering (RISE) — Germany',
    description: 'DAAD RISE places undergraduate students from abroad in research internships at top German universities and institutes for 6–12 weeks during summer. Fields: biology, chemistry, physics, CS, and engineering. Stipend €650–850/month.',
    type: 'RESEARCH' as const,
    url: 'https://www.daad.de/rise/en/',
    organizer: 'DAAD',
    location: 'Germany',
    country: 'DE',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 56,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Stipend of €650–850/month plus travel allowance.',
    stipend: 700,
    eligibleFields: ['LIFE_SCIENCES', 'PHYSICAL_SCIENCES', 'COMPUTER_SCIENCE', 'ENGINEERING'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 4,
    tags: ['research', 'internship', 'germany', 'daad', 'stem', 'paid', 'summer'],
    sourceId: 'curated-daad-rise',
  },

  // ── VOLUNTEERING ───────────────────────────────────────────────────────────

  {
    title: 'ESN Erasmus Student Network — Volunteer Coordinator',
    description: "ESN è la più grande rete studentesca europea, presente in 40 paesi e 1.000+ sezioni universitarie. Diventare volontario o coordinatore locale permette di organizzare eventi internazionali, supportare studenti Erasmus, e sviluppare competenze di leadership e gestione di progetti.",
    type: 'VOLUNTEERING' as const,
    url: 'https://esn.org/volunteer',
    organizer: 'Erasmus Student Network',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['volunteering', 'erasmus', 'esn', 'europe', 'leadership', 'networking'],
    sourceId: 'curated-esn-volunteer',
  },

  {
    title: 'European Solidarity Corps — Volunteering Abroad (EU)',
    description: "Il European Solidarity Corps finanzia periodi di volontariato da 2 settimane a 12 mesi in tutta Europa per giovani 18–30 anni. Copre viaggio, alloggio, vitto e pocket money. Ideale per chi vuole un'esperienza all'estero in ambito sociale, ambientale o educativo.",
    type: 'VOLUNTEERING' as const,
    url: 'https://youth.europa.eu/solidarity/esc/volunteering_en',
    organizer: 'European Commission',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Fully funded: travel, accommodation, meals, and monthly pocket money (€150–€200).',
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['volunteering', 'europe', 'eu', 'fully-funded', 'social', 'solidarity'],
    sourceId: 'curated-european-solidarity-corps',
  },

  // ── COMPETITION ────────────────────────────────────────────────────────────

  {
    title: 'Model United Nations — WFUNA International MUN',
    description: "WIMUN (World Federation of United Nations Associations) è la simulazione delle Nazioni Unite più riconosciuta a livello internazionale. Studenti universitari rappresentano paesi in commissioni ONU, dibattendo risoluzioni su crisi globali. Si tiene a New York e Ginevra.",
    type: 'COMPETITION' as const,
    url: 'https://www.wfuna.org/wimun',
    organizer: 'WFUNA',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 5,
    cost: 600,
    hasScholarship: true,
    scholarshipDetails: 'Scholarship applications available for delegates from developing countries.',
    eligibleFields: ['POLITICAL_SCIENCE', 'LAW', 'HUMANITIES'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['competition', 'model-un', 'diplomacy', 'international', 'new-york', 'geneva'],
    sourceId: 'curated-wimun',
  },

  {
    title: "L'Oréal Brandstorm — Global Innovation Competition",
    description: "L'Oréal Brandstorm è una competizione internazionale di innovazione e marketing aperta a team di 2–3 studenti universitari. I team sviluppano un concept di prodotto/servizio per uno dei brand L'Oréal. I vincitori nazionali accedono alla finale globale a Parigi con mentoship e premi.",
    type: 'COMPETITION' as const,
    url: 'https://brandstorm.loreal.com/',
    organizer: "L'Oréal",
    location: 'Paris, France',
    city: 'Paris',
    country: 'FR',
    isAbroad: true,
    isRemote: true,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['BUSINESS', 'DESIGN', 'ECONOMICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 5,
    tags: ['competition', 'marketing', 'innovation', 'loreal', 'business', 'global'],
    sourceId: 'curated-loreal-brandstorm',
  },

];

async function run() {
  let created = 0;
  let updated = 0;
  let failed = 0;

  for (const opp of opportunities) {
    try {
      const result = await upsertManualOpportunity(opp as any);
      if (result.action === 'created') created++;
      else updated++;
      logger.info(`[Seed] ${result.action}: ${opp.title.slice(0, 60)}`);
    } catch (err) {
      logger.error(`[Seed] Failed: ${opp.title.slice(0, 60)} — ${err}`);
      failed++;
    }
  }

  logger.info(`[Seed] Done: ${created} created, ${updated} updated, ${failed} failed`);
  process.exit(failed > 0 ? 1 : 0);
}

run();
