/**
 * 100 mock opportunities for development/testing.
 * Run: npx ts-node --transpile-only prisma/seeds/mock-opportunities.ts
 */
import { upsertManualOpportunity } from '../../src/services/import/manual.import';
import { logger } from '../../src/utils/logger';

const opportunities = [

  // ── STAGE / INTERNSHIP ─────────────────────────────────────────────────────

  {
    title: 'Stage Sviluppo Software — Fintech Startup Milano',
    description: 'Cerchiamo uno stagista da inserire nel team di sviluppo backend. Lavorerai su API REST in Node.js e TypeScript, integrazione con sistemi bancari PSD2, e deployment su AWS. Ambiente giovane, 4 giorni in sede + 1 da remoto.',
    type: 'STAGE' as const,
    url: 'https://example.com/stage-fintech-milano',
    company: 'FinFlow Srl',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 800,
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['stage', 'backend', 'nodejs', 'fintech', 'milan', 'paid'],
    sourceId: 'mock-stage-fintech-milano',
  },

  {
    title: 'Tirocinio Marketing Digitale — Agenzia Creativa Roma',
    description: "Opportunità di tirocinio nel dipartimento marketing di un'agenzia creativa romana. Ti occuperai di content strategy, gestione social media, SEO/SEM e reportistica. Formazione continua e possibilità di assunzione.",
    type: 'STAGE' as const,
    url: 'https://example.com/tirocinio-marketing-roma',
    company: 'CreativeHub Roma',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 600,
    eligibleFields: ['BUSINESS', 'HUMANITIES', 'DESIGN'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['stage', 'marketing', 'social-media', 'seo', 'rome', 'paid'],
    sourceId: 'mock-stage-marketing-roma',
  },

  {
    title: 'Internship Data Science — Retail Analytics Torino',
    description: 'Join our data team to build predictive models for retail demand forecasting. You will use Python, Spark, and Databricks to analyze millions of transactions. Strong math background required.',
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/internship-datascience-torino',
    company: 'RetailMetrics SpA',
    location: 'Turin, Italy',
    city: 'Turin',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 1000,
    eligibleFields: ['COMPUTER_SCIENCE', 'MATHEMATICS', 'ENGINEERING'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['internship', 'data-science', 'python', 'machine-learning', 'torino', 'paid'],
    sourceId: 'mock-internship-datascience-torino',
  },

  {
    title: 'Stage UX/UI Design — App Salute Digitale',
    description: "Stai cercando uno stage nel design? Entra nel nostro team di prodotto. Lavorerai su wireframing con Figma, user testing con utenti reali, e design system per la nostra app di telemedicina. Portfolio richiesto.",
    type: 'STAGE' as const,
    url: 'https://example.com/stage-ux-salute',
    company: 'MedApp Italia',
    location: 'Bologna, Italy',
    city: 'Bologna',
    country: 'IT',
    isAbroad: false,
    isRemote: true,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 700,
    eligibleFields: ['DESIGN', 'COMPUTER_SCIENCE', 'PSYCHOLOGY'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['stage', 'ux', 'ui', 'figma', 'healthcare', 'hybrid', 'paid'],
    sourceId: 'mock-stage-ux-salute',
  },

  {
    title: 'Legal Internship — Studio Legale Internazionale Milano',
    description: 'Studio legale internazionale con sede a Milano ricerca tirocinante nel dipartimento di diritto commerciale e M&A. Parteciperai a due diligence, redazione contratti, e ricerche giurisprudenziali. Ottima conoscenza di inglese e italiano giuridico.',
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/legal-internship-milano',
    company: 'Rossi & Partners LLP',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 900,
    eligibleFields: ['LAW'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['internship', 'law', 'ma', 'commercial-law', 'milan', 'paid'],
    sourceId: 'mock-legal-internship-milano',
  },

  {
    title: 'Finance Internship — Investment Banking Londra',
    description: 'Prestigious 10-week summer internship in the M&A division of a leading London investment bank. Work on live deals, financial modelling, and pitch decks. Candidates must have strong Excel/PowerPoint and at least one prior finance experience.',
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/finance-internship-london',
    company: 'Meridian Capital Partners',
    location: 'London, UK',
    city: 'London',
    country: 'GB',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 2500,
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'MATHEMATICS'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 5,
    tags: ['internship', 'finance', 'investment-banking', 'london', 'paid', 'abroad'],
    sourceId: 'mock-finance-internship-london',
  },

  {
    title: 'Stage Comunicazione Istituzionale — NGO Napoli',
    description: "ONG ambientale cerca stagista per comunicazione e fundraising. Ti occuperai di newsletter, comunicati stampa, gestione dei rapporti con i media e organizzazione eventi. Rimborso spese previsto. Ottimo per chi vuole entrare nel terzo settore.",
    type: 'STAGE' as const,
    url: 'https://example.com/stage-ngo-napoli',
    company: 'GreenNapoli APS',
    location: 'Naples, Italy',
    city: 'Naples',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 400,
    eligibleFields: ['HUMANITIES', 'POLITICAL_SCIENCE', 'BUSINESS'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['stage', 'comunicazione', 'ngo', 'ambiente', 'napoli'],
    sourceId: 'mock-stage-ngo-napoli',
  },

  {
    title: 'Engineering Internship — Automotive R&D Torino',
    description: 'Join the powertrain R&D division of a leading Italian automotive group. You will support simulation and testing of hybrid drivetrain components using MATLAB/Simulink. Knowledge of thermodynamics required.',
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/engineering-internship-automotive',
    company: 'ItalMotion Group',
    location: 'Turin, Italy',
    city: 'Turin',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 1100,
    eligibleFields: ['ENGINEERING', 'PHYSICAL_SCIENCES'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['internship', 'engineering', 'automotive', 'matlab', 'torino', 'paid'],
    sourceId: 'mock-engineering-internship-automotive',
  },

  {
    title: 'Stage Ricerca Clinica — Ospedale Universitario Padova',
    description: 'Il Dipartimento di Oncologia Clinica offre uno stage di ricerca in ambito trial clinici di fase II/III. Supporterai la raccolta dati, la preparazione di report per il comitato etico, e la revisione sistematica della letteratura.',
    type: 'STAGE' as const,
    url: 'https://example.com/stage-ricerca-clinica-padova',
    company: 'Azienda Ospedaliera Università di Padova',
    location: 'Padua, Italy',
    city: 'Padua',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 500,
    eligibleFields: ['MEDICINE', 'LIFE_SCIENCES'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['stage', 'ricerca', 'medicina', 'trial-clinici', 'padova'],
    sourceId: 'mock-stage-ricerca-clinica-padova',
  },

  {
    title: 'Product Management Internship — SaaS Scaleup Remoto',
    description: 'Remote internship for a B2B SaaS startup. You will shadow the product team, write PRDs, run user interviews, and help prioritize the roadmap. English required. 20h/week — compatible with full-time study.',
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/pm-internship-remote',
    company: 'Taskraft Inc.',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 400,
    eligibleFields: ['COMPUTER_SCIENCE', 'BUSINESS', 'ECONOMICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['internship', 'product-management', 'remote', 'saas', 'part-time'],
    sourceId: 'mock-pm-internship-remote',
  },

  // ── HACKATHON ──────────────────────────────────────────────────────────────

  {
    title: 'HackMED — Hackathon Salute & AI Roma',
    description: "48 ore per sviluppare soluzioni AI nel settore sanitario. Team da 3–5 persone, mentori provenienti da Roche, Philips Healthcare e startup italiane. Premio totale €20.000. Categorie: diagnostica, patient journey, gestione ospedaliera.",
    type: 'HACKATHON' as const,
    url: 'https://example.com/hackmed-roma',
    organizer: 'HealthInnovation Italia',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 2,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'MEDICINE', 'ENGINEERING', 'LIFE_SCIENCES'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['hackathon', 'ai', 'health', 'rome', 'prize', 'free'],
    sourceId: 'mock-hackmed-roma',
  },

  {
    title: 'ClimaThon Italia — Hackathon Sostenibilità',
    description: 'Hackathon nazionale focalizzato su soluzioni al cambiamento climatico. Partecipa in presenza a Milano o online. 72 ore di lavoro intenso, coaching da esperti ambientali e tech, prize pool €15.000.',
    type: 'HACKATHON' as const,
    url: 'https://example.com/climathon-italia',
    organizer: 'Climate-KIC Italy',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: true,
    format: 'HYBRID' as const,
    durationDays: 3,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ENGINEERING', 'COMPUTER_SCIENCE', 'PHYSICAL_SCIENCES', 'ECONOMICS'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['hackathon', 'sustainability', 'climate', 'hybrid', 'prize', 'free'],
    sourceId: 'mock-climathon-italia',
  },

  {
    title: 'Junction Helsinki — Europe\'s Biggest Hackathon',
    description: 'Europe\'s largest hackathon, held in Helsinki. 1500+ participants from 80+ countries, 40+ sponsors including Google, Nokia, and Unity. Multiple tracks: Web3, AR/VR, Mobility, Health, Climate. Travel grants available.',
    type: 'HACKATHON' as const,
    url: 'https://example.com/junction-helsinki',
    organizer: 'Junction Ry',
    location: 'Helsinki, Finland',
    city: 'Helsinki',
    country: 'FI',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 2,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Travel grants of up to €300 available for selected teams.',
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING', 'DESIGN'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['hackathon', 'finland', 'europe', 'abroad', 'travel-grant', 'free'],
    sourceId: 'mock-junction-helsinki',
  },

  {
    title: 'BioHack Italia — Biotecnologie & Bioinformatica',
    description: "48 ore per costruire strumenti bioinformatici open source. Dati reali messi a disposizione da CNR e Fondazione Telethon. Mentori da Illumina e EMBL. Vince il team che crea l'impatto scientifico più riproducibile.",
    type: 'HACKATHON' as const,
    url: 'https://example.com/biohack-italia',
    organizer: 'Open Bio Italia',
    location: 'Florence, Italy',
    city: 'Florence',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 2,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['LIFE_SCIENCES', 'COMPUTER_SCIENCE', 'MEDICINE'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['hackathon', 'biotech', 'bioinformatics', 'florence', 'science', 'free'],
    sourceId: 'mock-biohack-italia',
  },

  {
    title: 'FinHack — Hackathon Open Banking',
    description: 'Hackathon organizzato da un consorzio di banche italiane. Accesso alle API PSD2 dei principali istituti. Sfide su: open banking, frode detection, financial inclusion. Premio €25.000 + fast-track a percorsi di accelerazione.',
    type: 'HACKATHON' as const,
    url: 'https://example.com/finhack-openbanking',
    organizer: 'ABI Lab',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 2,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'ECONOMICS', 'MATHEMATICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['hackathon', 'fintech', 'open-banking', 'milan', 'prize'],
    sourceId: 'mock-finhack-openbanking',
  },

  // ── FELLOWSHIP ─────────────────────────────────────────────────────────────

  {
    title: 'Ashoka Youth Venture Fellowship — Social Innovation',
    description: 'Ashoka selects 20 young change-makers each year for an 18-month fellowship. Fellows receive coaching, a €5,000 seed grant, and access to a global network of social entrepreneurs. Applications open to undergrads and recent graduates.',
    type: 'FELLOWSHIP' as const,
    url: 'https://example.com/ashoka-youth-venture',
    organizer: 'Ashoka Europe',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: '€5,000 seed grant + full coaching package.',
    eligibleFields: [] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['fellowship', 'social-innovation', 'entrepreneurship', 'europe', 'fully-funded'],
    sourceId: 'mock-ashoka-youth-venture',
  },

  {
    title: 'Horizon Europe Young Researchers Grant',
    description: 'Two-year research fellowship for early-stage researchers in EU priority areas: green hydrogen, AI ethics, and quantum computing. Hosted at a European research institute of your choice. Salary + travel + equipment budget.',
    type: 'FELLOWSHIP' as const,
    url: 'https://example.com/horizon-europe-young-researchers',
    organizer: 'European Commission',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Salary €2,200/month + €8,000 equipment budget + travel allowance.',
    stipend: 2200,
    eligibleFields: ['PHYSICAL_SCIENCES', 'COMPUTER_SCIENCE', 'ENGINEERING', 'LIFE_SCIENCES'] as any[],
    minYearOfStudy: 5,
    maxYearOfStudy: 6,
    tags: ['fellowship', 'research', 'eu', 'science', 'fully-funded', 'abroad'],
    sourceId: 'mock-horizon-europe-young-researchers',
  },

  {
    title: 'Obama Foundation Leaders Europe — Fellowship',
    description: 'The Obama Foundation selects 25 emerging leaders from Europe each year for a year-long program combining in-person summits, virtual coaching, and community projects. Focus on civic leadership and public service.',
    type: 'FELLOWSHIP' as const,
    url: 'https://example.com/obama-foundation-leaders-europe',
    organizer: 'Obama Foundation',
    isAbroad: true,
    isRemote: true,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Fully funded including travel, accommodation for summits, and program expenses.',
    eligibleFields: [] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['fellowship', 'leadership', 'civic', 'usa', 'fully-funded', 'prestige'],
    sourceId: 'mock-obama-foundation-leaders-europe',
  },

  {
    title: 'ENI Joule — Fellowship per Sostenibilità Energetica',
    description: "ENI seleziona ogni anno 30 giovani talenti per un fellowship in sustainability e transizione energetica. Il programma include mentorship da senior ENI, un project grant €10.000, e accesso ai laboratori R&D di San Donato Milanese.",
    type: 'FELLOWSHIP' as const,
    url: 'https://example.com/eni-joule-fellowship',
    organizer: 'ENI',
    location: 'San Donato Milanese, Italy',
    city: 'San Donato Milanese',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Project grant €10.000 + €1.500/mese durante il fellowship.',
    stipend: 1500,
    eligibleFields: ['ENGINEERING', 'PHYSICAL_SCIENCES', 'ECONOMICS', 'COMPUTER_SCIENCE'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['fellowship', 'energy', 'sustainability', 'eni', 'italy', 'paid', 'prestige'],
    sourceId: 'mock-eni-joule-fellowship',
  },

  // ── SUMMER PROGRAM ─────────────────────────────────────────────────────────

  {
    title: 'MIT Digital Economy Summer Program',
    description: "Intensive 3-week program at MIT exploring the intersection of technology, economics, and policy. Lectures by MIT faculty, case studies, and project work with international peers. Housing included in Harvard Square.",
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://example.com/mit-digital-economy-summer',
    organizer: 'MIT Sloan',
    location: 'Cambridge, MA, USA',
    city: 'Cambridge',
    country: 'US',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 21,
    cost: 4500,
    hasScholarship: true,
    scholarshipDetails: 'Need-based scholarships up to 70% of tuition for international students.',
    eligibleFields: ['ECONOMICS', 'COMPUTER_SCIENCE', 'BUSINESS', 'POLITICAL_SCIENCE'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 5,
    tags: ['summer-school', 'mit', 'economics', 'usa', 'abroad', 'prestige'],
    sourceId: 'mock-mit-digital-economy-summer',
  },

  {
    title: 'Sciences Po Paris — European Politics Summer Academy',
    description: "Two-week intensive program on EU institutions, foreign policy, and geopolitics. Held in Paris. Includes visits to the European Parliament, OECD headquarters, and the Élysée Palace. French not required.",
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://example.com/sciencespo-summer-paris',
    organizer: 'Sciences Po Paris',
    location: 'Paris, France',
    city: 'Paris',
    country: 'FR',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 14,
    cost: 3800,
    hasScholarship: true,
    scholarshipDetails: 'Partial scholarships available for EU students from underrepresented backgrounds.',
    eligibleFields: ['POLITICAL_SCIENCE', 'LAW', 'ECONOMICS', 'HUMANITIES'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'sciencespo', 'politics', 'paris', 'eu', 'abroad'],
    sourceId: 'mock-sciencespo-summer-paris',
  },

  {
    title: 'Summer School Design Thinking — IED Milano',
    description: "Programma estivo di design thinking e prototipazione rapida all'Istituto Europeo di Design. 10 giorni, mix di lezioni teoriche e workshop pratici con aziende partner. Ideale per chi vuole testare la propria creatività in un ambiente professionale.",
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://example.com/ied-design-thinking-summer',
    organizer: 'IED Milano',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 10,
    cost: 1800,
    hasScholarship: false,
    eligibleFields: ['DESIGN', 'BUSINESS', 'COMPUTER_SCIENCE', 'ARCHITECTURE'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'design-thinking', 'ied', 'milan', 'creative'],
    sourceId: 'mock-ied-design-thinking-summer',
  },

  {
    title: 'Oxford Internet Institute — Digital Futures Summer School',
    description: "One-week residential program at the University of Oxford examining how digital technologies are reshaping society, politics, and the economy. Seminars with leading researchers, group project, and Oxford college experience.",
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://example.com/oxford-digital-futures-summer',
    organizer: 'Oxford Internet Institute',
    location: 'Oxford, UK',
    city: 'Oxford',
    country: 'GB',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 7,
    cost: 2900,
    hasScholarship: true,
    scholarshipDetails: 'A limited number of bursaries covering full fees for students from low-income backgrounds.',
    eligibleFields: ['COMPUTER_SCIENCE', 'POLITICAL_SCIENCE', 'HUMANITIES', 'ECONOMICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'oxford', 'digital', 'uk', 'abroad', 'prestige'],
    sourceId: 'mock-oxford-digital-futures-summer',
  },

  {
    title: 'Quantitative Finance Summer Program — Banca d\'Italia',
    description: 'Programma estivo della Banca d\'Italia per studenti eccellenti in matematica, fisica ed economia quantitativa. 3 settimane di seminari su modelli di rischio, politica monetaria, e analisi macroprudenziale. Borse di studio coprano vitto e alloggio.',
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://example.com/bancaitalia-quant-summer',
    organizer: 'Banca d\'Italia',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 21,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Borsa completa che copre alloggio, pasti e rimborso viaggio per i selezionati.',
    eligibleFields: ['MATHEMATICS', 'ECONOMICS', 'PHYSICAL_SCIENCES'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 5,
    tags: ['summer-school', 'finance', 'quant', 'banca-italia', 'rome', 'fully-funded', 'prestige'],
    sourceId: 'mock-bancaitalia-quant-summer',
  },

  // ── CONFERENCE ─────────────────────────────────────────────────────────────

  {
    title: 'TEDxMilano Student Track — Speaker Application',
    description: "Vuoi parlare sul palco di TEDxMilano? Ogni anno selezioniamo 5 studenti universitari per la student track. Supporto nella preparazione del talk, coaching da esperti TED, e visibilità su una platea di 2.000+ persone.",
    type: 'CONFERENCE' as const,
    url: 'https://example.com/tedxmilano-student-track',
    organizer: 'TEDxMilano',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['conference', 'tedx', 'speaking', 'milan', 'networking', 'free'],
    sourceId: 'mock-tedxmilano-student-track',
  },

  {
    title: 'Forum Ambrosetti — The European House Scholarship',
    description: "Il Forum Ambrosetti seleziona ogni anno 20 studenti eccellenti di università italiane per partecipare gratuitamente al Summit di Cernobbio, il principale forum di policy in Italia. Networking con CEO, ministri e personalità internazionali.",
    type: 'CONFERENCE' as const,
    url: 'https://example.com/forum-ambrosetti-scholarship',
    organizer: 'The European House – Ambrosetti',
    location: 'Cernobbio, Italy',
    city: 'Cernobbio',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Accesso gratuito al forum, alloggio e pasti inclusi per i selezionati.',
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'LAW', 'POLITICAL_SCIENCE'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['conference', 'ambrosetti', 'cernobbio', 'policy', 'networking', 'prestige', 'fully-funded'],
    sourceId: 'mock-forum-ambrosetti-scholarship',
  },

  {
    title: 'Web Summit Lisbon — Student Pass',
    description: "Web Summit is the world's largest tech conference (70,000+ attendees). Student passes available at 90% discount (€50 instead of €500). Access to all stages, startup exhibition, and networking events with investors, founders, and engineers.",
    type: 'CONFERENCE' as const,
    url: 'https://example.com/websummit-lisbon-student',
    organizer: 'Web Summit',
    location: 'Lisbon, Portugal',
    city: 'Lisbon',
    country: 'PT',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 50,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'BUSINESS', 'ENGINEERING', 'DESIGN'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['conference', 'tech', 'startup', 'lisbon', 'networking', 'abroad', 'discount'],
    sourceId: 'mock-websummit-lisbon-student',
  },

  {
    title: 'Neuroscience Summit Italia — Young Researcher Award',
    description: "La Società Italiana di Neuroscienze organizza una sessione dedicata ai giovani ricercatori. Presenta il tuo lavoro (poster o talk) e concorri per il Young Researcher Award da €2.000. Iscrizione gratuita per dottorandi e laureandi magistrali.",
    type: 'CONFERENCE' as const,
    url: 'https://example.com/neuroscience-summit-italia',
    organizer: 'SINS – Società Italiana di Neuroscienze',
    location: 'Venice, Italy',
    city: 'Venice',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['MEDICINE', 'LIFE_SCIENCES', 'PSYCHOLOGY'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['conference', 'neuroscience', 'research', 'venice', 'award', 'free'],
    sourceId: 'mock-neuroscience-summit-italia',
  },

  // ── EXCHANGE ───────────────────────────────────────────────────────────────

  {
    title: 'Erasmus+ Semestre a Barcellona — UPF',
    description: "Opportunità Erasmus+ presso la Universitat Pompeu Fabra di Barcellona. Durata 5 mesi (febbraio–giugno o settembre–gennaio). Borsa Erasmus €500/mese. Corsi disponibili in inglese e spagnolo in economia, giurisprudenza e scienze politiche.",
    type: 'EXCHANGE' as const,
    url: 'https://example.com/erasmus-upf-barcellona',
    organizer: 'Universitat Pompeu Fabra',
    location: 'Barcelona, Spain',
    city: 'Barcelona',
    country: 'ES',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 150,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Borsa Erasmus+ €500/mese erogata dall\'università di provenienza.',
    stipend: 500,
    eligibleFields: ['ECONOMICS', 'LAW', 'POLITICAL_SCIENCE', 'BUSINESS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 5,
    tags: ['exchange', 'erasmus', 'barcelona', 'spain', 'abroad', 'scholarship'],
    sourceId: 'mock-erasmus-upf-barcellona',
  },

  {
    title: 'Double Degree Program — Politecnico di Torino & TU Munich',
    description: "Programma di doppio titolo tra Politecnico di Torino e Technische Universität München per studenti magistrali in ingegneria. Due anni: primo anno a Torino, secondo anno a Monaco. Titolo rilasciato da entrambe le università.",
    type: 'EXCHANGE' as const,
    url: 'https://example.com/double-degree-polito-tum',
    organizer: 'Politecnico di Torino / TU Munich',
    location: 'Munich, Germany',
    city: 'Munich',
    country: 'DE',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 365,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'DAAD scholarship €850/month for the year spent in Germany.',
    stipend: 850,
    eligibleFields: ['ENGINEERING', 'COMPUTER_SCIENCE'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 5,
    tags: ['exchange', 'double-degree', 'germany', 'engineering', 'prestige', 'scholarship'],
    sourceId: 'mock-double-degree-polito-tum',
  },

  {
    title: 'Global Undergraduate Exchange Program — USA (State Dept.)',
    description: "Fully funded semester exchange at a US university, sponsored by the US Department of State. Open to students from Italy and other partner countries. Covers tuition, housing, living expenses, and flights. Highly competitive.",
    type: 'EXCHANGE' as const,
    url: 'https://example.com/global-ugrad-usa',
    organizer: 'U.S. Department of State',
    location: 'United States',
    country: 'US',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 120,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Fully funded: tuition, housing, meals, insurance, flights, and visa costs.',
    eligibleFields: [] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 4,
    tags: ['exchange', 'usa', 'state-department', 'fully-funded', 'abroad', 'prestige'],
    sourceId: 'mock-global-ugrad-usa',
  },

  // ── BOOTCAMP ───────────────────────────────────────────────────────────────

  {
    title: 'Codemotion Bootcamp — Full Stack JavaScript',
    description: "Bootcamp intensivo di 8 settimane full-time su React, Node.js e PostgreSQL. Il programma include 400+ ore di coding, 3 progetti reali, e career week finale con colloqui con aziende partner. Placement rate 89%.",
    type: 'BOOTCAMP' as const,
    url: 'https://example.com/codemotion-bootcamp-js',
    organizer: 'Codemotion Academy',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 56,
    cost: 3500,
    hasScholarship: true,
    scholarshipDetails: 'Income-share agreement disponibile: nessun costo finché non trovi lavoro.',
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['bootcamp', 'javascript', 'fullstack', 'react', 'nodejs', 'rome'],
    sourceId: 'mock-codemotion-bootcamp-js',
  },

  {
    title: 'Data Science Bootcamp Online — Le Wagon',
    description: "9-week intensive online bootcamp in data science and ML. Topics: Python, SQL, statistics, scikit-learn, deep learning, NLP. Live sessions with instructors + async content. Certificate upon completion. Italian cohort available.",
    type: 'BOOTCAMP' as const,
    url: 'https://example.com/lewagon-data-science-online',
    organizer: 'Le Wagon',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    durationDays: 63,
    cost: 4000,
    hasScholarship: true,
    scholarshipDetails: 'Partial scholarships (€500–1,000) available for students from underrepresented groups.',
    eligibleFields: ['COMPUTER_SCIENCE', 'MATHEMATICS', 'ENGINEERING', 'ECONOMICS'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['bootcamp', 'data-science', 'python', 'ml', 'remote', 'certificate'],
    sourceId: 'mock-lewagon-data-science-online',
  },

  {
    title: 'Product Design Bootcamp — Interaction Design Foundation',
    description: "12-week self-paced online bootcamp with live mentorship sessions. Covers UX research, information architecture, prototyping, and portfolio building. Upon completion you will have 3 case studies ready for job applications.",
    type: 'BOOTCAMP' as const,
    url: 'https://example.com/idf-product-design-bootcamp',
    organizer: 'Interaction Design Foundation',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    durationDays: 84,
    cost: 600,
    hasScholarship: false,
    eligibleFields: ['DESIGN', 'COMPUTER_SCIENCE', 'PSYCHOLOGY'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['bootcamp', 'ux', 'product-design', 'online', 'portfolio', 'affordable'],
    sourceId: 'mock-idf-product-design-bootcamp',
  },

  {
    title: 'Cybersecurity Bootcamp — SANS Institute (Online)',
    description: "Intensive 5-day online cybersecurity bootcamp covering ethical hacking, network defence, and incident response. Taught by SANS certified instructors. Prepares you for GIAC certifications. Includes 4-month access to the course materials.",
    type: 'BOOTCAMP' as const,
    url: 'https://example.com/sans-cybersecurity-bootcamp',
    organizer: 'SANS Institute',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    durationDays: 5,
    cost: 800,
    hasScholarship: true,
    scholarshipDetails: 'SANS Cyber Talent Scholarship covers full cost for top applicants.',
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['bootcamp', 'cybersecurity', 'ethical-hacking', 'giac', 'online', 'certificate'],
    sourceId: 'mock-sans-cybersecurity-bootcamp',
  },

  // ── RESEARCH ───────────────────────────────────────────────────────────────

  {
    title: 'CERN Summer Student Programme — Fisica delle Particelle',
    description: "Il CERN accetta ogni anno 200+ studenti per un programma estivo di 8–13 settimane a Ginevra. Lavori in uno dei laboratori di fisica delle particelle più avanzati al mondo. Stipendio mensile + alloggio nel campus CERN.",
    type: 'RESEARCH' as const,
    url: 'https://example.com/cern-summer-student',
    organizer: 'CERN',
    location: 'Geneva, Switzerland',
    city: 'Geneva',
    country: 'CH',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 70,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Stipendio CHF 90/giorno + contributo alloggio + rimborso viaggio.',
    stipend: 2700,
    eligibleFields: ['PHYSICAL_SCIENCES', 'ENGINEERING', 'COMPUTER_SCIENCE', 'MATHEMATICS'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 5,
    tags: ['research', 'physics', 'cern', 'switzerland', 'abroad', 'fully-funded', 'prestige'],
    sourceId: 'mock-cern-summer-student',
  },

  {
    title: 'CNR Iniziativa Giovani — Borse di Ricerca',
    description: "Il Consiglio Nazionale delle Ricerche offre borse di ricerca per studenti magistrali e dottorandi in 107 istituti distribuiti in tutta Italia. Durata 3–12 mesi. Ambiti: nanotecnologie, intelligenza artificiale, scienze marine, storia e scienze umane.",
    type: 'RESEARCH' as const,
    url: 'https://example.com/cnr-iniziativa-giovani',
    organizer: 'CNR – Consiglio Nazionale delle Ricerche',
    location: 'Italy (various)',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Borsa da €1.200 a €2.000/mese a seconda del livello del candidato.',
    stipend: 1400,
    eligibleFields: ['PHYSICAL_SCIENCES', 'COMPUTER_SCIENCE', 'LIFE_SCIENCES', 'HUMANITIES', 'ENGINEERING'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['research', 'cnr', 'italy', 'borsa', 'paid', 'science'],
    sourceId: 'mock-cnr-iniziativa-giovani',
  },

  {
    title: 'Weizmann Institute — Feinberg Summer School (Israele)',
    description: "The Weizmann Institute's summer school invites 40 international students for 8 weeks of supervised research in life sciences, chemistry, and physics labs. All expenses paid. Accepted students work directly with principal investigators.",
    type: 'RESEARCH' as const,
    url: 'https://example.com/weizmann-summer-feinberg',
    organizer: 'Weizmann Institute of Science',
    location: 'Rehovot, Israel',
    city: 'Rehovot',
    country: 'IL',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 56,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Fully funded: flights, accommodation, meals, and weekly stipend.',
    stipend: 600,
    eligibleFields: ['LIFE_SCIENCES', 'PHYSICAL_SCIENCES'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 5,
    tags: ['research', 'life-sciences', 'chemistry', 'israel', 'abroad', 'fully-funded'],
    sourceId: 'mock-weizmann-summer-feinberg',
  },

  {
    title: 'IIT — Istituto Italiano di Tecnologia: Research Internship',
    description: "L'IIT di Genova offre posizioni di ricerca per studenti magistrali in robotica, neuroscienza computazionale, nanotecnologie e machine learning. Collaborazione con ricercatori internazionali e accesso a infrastrutture all'avanguardia.",
    type: 'RESEARCH' as const,
    url: 'https://example.com/iit-research-internship',
    organizer: 'Istituto Italiano di Tecnologia',
    location: 'Genoa, Italy',
    city: 'Genoa',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 900,
    eligibleFields: ['ENGINEERING', 'COMPUTER_SCIENCE', 'PHYSICAL_SCIENCES', 'LIFE_SCIENCES'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['research', 'robotics', 'ai', 'iit', 'genoa', 'paid'],
    sourceId: 'mock-iit-research-internship',
  },

  // ── COMPETITION ─────────────────────────────────────────────────────────────

  {
    title: 'CFA Institute Research Challenge — Italy',
    description: "La sfida italiana del CFA Institute Research Challenge invita team di 3–5 studenti universitari a produrre una equity research su un'azienda italiana quotata. I vincitori nazionali partecipano alla finale europea.",
    type: 'COMPETITION' as const,
    url: 'https://example.com/cfa-research-challenge-italy',
    organizer: 'CFA Society Italy',
    location: 'Italy',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'MATHEMATICS'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 5,
    tags: ['competition', 'finance', 'cfa', 'equity-research', 'italy', 'prestige'],
    sourceId: 'mock-cfa-research-challenge-italy',
  },

  {
    title: 'ICPC — International Collegiate Programming Contest',
    description: "The ICPC is the world's most prestigious competitive programming contest. Italian teams compete in regional rounds, then the best advance to the ICPC World Finals. Participate as a team of 3 students.",
    type: 'COMPETITION' as const,
    url: 'https://example.com/icpc-italy',
    organizer: 'ICPC Foundation',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'MATHEMATICS', 'ENGINEERING'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 5,
    tags: ['competition', 'programming', 'icpc', 'algorithms', 'prestige', 'free'],
    sourceId: 'mock-icpc-italy',
  },

  {
    title: 'European Law Moot Court Competition',
    description: "Simulate a case before the Court of Justice of the European Union. Teams of 4 law students research, write a memorial, and plead orally before panels of judges. Final rounds held in Luxembourg at the actual CJEU building.",
    type: 'COMPETITION' as const,
    url: 'https://example.com/european-law-moot-court',
    organizer: 'European Law Moot Court Society',
    location: 'Luxembourg',
    city: 'Luxembourg',
    country: 'LU',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Travel and accommodation grants for teams reaching the final rounds.',
    eligibleFields: ['LAW'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['competition', 'law', 'moot-court', 'eu', 'luxembourg', 'prestige'],
    sourceId: 'mock-european-law-moot-court',
  },

  {
    title: 'National Business Plan Competition — StartCup Italia',
    description: "StartCup è la principale competizione italiana di business planning universitario. Partecipa con la tua idea imprenditoriale e concorri per €50.000 in premi e accesso al PNI (Premio Nazionale per l'Innovazione). Aperto a team con almeno uno studente universitario.",
    type: 'COMPETITION' as const,
    url: 'https://example.com/startcup-italia',
    organizer: 'NetVal – Rete per la Valorizzazione della Ricerca Universitaria',
    location: 'Italy',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['competition', 'startup', 'business-plan', 'italy', 'prize', 'entrepreneurship'],
    sourceId: 'mock-startcup-italia',
  },

  {
    title: 'Architecture Student Awards — Ordine degli Architetti Roma',
    description: "Concorso nazionale di progettazione architettonica aperto a studenti di Architettura e Ingegneria Edile. Tema: rigenerazione urbana di aree industriali dismesse. Prize pool €12.000 + pubblicazione su rivista di settore.",
    type: 'COMPETITION' as const,
    url: 'https://example.com/architecture-student-awards-roma',
    organizer: "Ordine degli Architetti di Roma",
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ARCHITECTURE', 'ENGINEERING'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['competition', 'architecture', 'design', 'urban', 'rome', 'prize'],
    sourceId: 'mock-architecture-student-awards-roma',
  },

  // ── EXTRACURRICULAR ─────────────────────────────────────────────────────────

  {
    title: 'Model United Nations — NMUN New York',
    description: "NMUN is the world's largest MUN conference, held at the United Nations Headquarters in New York. Represent a country, debate global issues, and draft resolutions alongside 5,000+ delegates from 140+ countries.",
    type: 'EXTRACURRICULAR' as const,
    url: 'https://example.com/nmun-new-york',
    organizer: 'National Model United Nations',
    location: 'New York, USA',
    city: 'New York',
    country: 'US',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 350,
    hasScholarship: true,
    scholarshipDetails: 'Conference fee waivers available for delegations from developing countries.',
    eligibleFields: ['POLITICAL_SCIENCE', 'LAW', 'ECONOMICS', 'HUMANITIES'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['extracurricular', 'mun', 'un', 'new-york', 'diplomacy', 'abroad'],
    sourceId: 'mock-nmun-new-york',
  },

  {
    title: 'Junior Enterprise Italy — Diventare Consulente Universitario',
    description: "Le Junior Enterprise sono associazioni universitarie che offrono servizi di consulenza a PMI italiane. Entra nel board o nel team di progetto della JE della tua università e acquisisci esperienza reale in strategia, marketing, e IT già durante la laurea triennale.",
    type: 'EXTRACURRICULAR' as const,
    url: 'https://example.com/junior-enterprise-italy',
    organizer: 'JADE Italy',
    location: 'Italy (all major universities)',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['BUSINESS', 'ECONOMICS', 'COMPUTER_SCIENCE', 'ENGINEERING'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 4,
    tags: ['extracurricular', 'consulting', 'junior-enterprise', 'italy', 'leadership', 'free'],
    sourceId: 'mock-junior-enterprise-italy',
  },

  {
    title: 'Intercollegiate Finance Consortium — Trading Competition',
    description: "Virtual stock trading competition for students across 50+ European universities. Trade a simulated €1M portfolio over 8 weeks, receive mentorship from finance professionals, and compete for €5,000 in prizes.",
    type: 'EXTRACURRICULAR' as const,
    url: 'https://example.com/ifc-trading-competition',
    organizer: 'Intercollegiate Finance Consortium',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'MATHEMATICS'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['extracurricular', 'finance', 'trading', 'competition', 'remote', 'free'],
    sourceId: 'mock-ifc-trading-competition',
  },

  {
    title: 'Google Developer Student Club — Diventa Lead',
    description: "Diventa il Google Developer Student Club Lead della tua università. Organizza eventi tecnici, workshop, e hackathon con il supporto di Google. Accesso a crediti Google Cloud, risorse didattiche, e una rete globale di 10.000+ lead in 100+ paesi.",
    type: 'EXTRACURRICULAR' as const,
    url: 'https://example.com/google-dsc-lead',
    organizer: 'Google Developers',
    isAbroad: false,
    isRemote: true,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING', 'MATHEMATICS'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 5,
    tags: ['extracurricular', 'google', 'tech', 'community', 'leadership', 'free'],
    sourceId: 'mock-google-dsc-lead',
  },

  {
    title: 'Psychology Research Lab Volunteer — UniPD',
    description: "Il Laboratorio di Psicologia Cognitiva dell'Università di Padova cerca volontari per studi su attenzione, memoria di lavoro, e decision-making. Partecipa come soggetto e poi come ricercatore junior. Crediti formativi riconosciuti.",
    type: 'EXTRACURRICULAR' as const,
    url: 'https://example.com/psychology-lab-volunteer-unipd',
    organizer: 'Università degli Studi di Padova',
    location: 'Padua, Italy',
    city: 'Padua',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['PSYCHOLOGY', 'LIFE_SCIENCES', 'MEDICINE'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['extracurricular', 'psychology', 'research', 'padova', 'volunteer', 'free'],
    sourceId: 'mock-psychology-lab-volunteer-unipd',
  },

  // ── VOLUNTEERING ────────────────────────────────────────────────────────────

  {
    title: 'UN Volunteers — Online Programme',
    description: "Il programma UN Online Volunteers permette di contribuire a progetti ONU da remoto per 10–20 ore/settimana. Ruoli disponibili in: traduzione, ricerca, comunicazione, sviluppo software e formazione. Aperto a studenti di ogni disciplina.",
    type: 'VOLUNTEERING' as const,
    url: 'https://example.com/un-volunteers-online',
    organizer: 'UNV – United Nations Volunteers',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['volunteering', 'un', 'online', 'remote', 'international', 'free'],
    sourceId: 'mock-un-volunteers-online',
  },

  {
    title: 'WWF Italia — Volontariato Conservazione Natura',
    description: "Il WWF Italia cerca volontari per attività di monitoraggio della biodiversità, educazione ambientale nelle scuole, e campagne di sensibilizzazione. Possibilità di partecipare a campi estivi nelle oasi naturali gestite da WWF.",
    type: 'VOLUNTEERING' as const,
    url: 'https://example.com/wwf-italia-volontariato',
    organizer: 'WWF Italia',
    location: 'Italy (multiple locations)',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['LIFE_SCIENCES', 'EDUCATION', 'HUMANITIES'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['volunteering', 'nature', 'wwf', 'italy', 'environment', 'free'],
    sourceId: 'mock-wwf-italia-volontariato',
  },

  {
    title: 'Teach For Italy — Insegnante Volontario',
    description: "Teach For Italy seleziona laureandi e neolaureati per portare istruzione di qualità nelle scuole di contesti svantaggiati. Programma di 2 anni con formazione intensa, mentorship, e stipendio. Contribuisci a ridurre la disuguaglianza educativa in Italia.",
    type: 'VOLUNTEERING' as const,
    url: 'https://example.com/teach-for-italy',
    organizer: 'Teach For Italy',
    location: 'Italy (multiple regions)',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 730,
    cost: 0,
    hasScholarship: false,
    stipend: 1200,
    eligibleFields: [] as any[],
    minYearOfStudy: 5,
    maxYearOfStudy: 6,
    tags: ['volunteering', 'education', 'teaching', 'social-impact', 'italy', 'paid'],
    sourceId: 'mock-teach-for-italy',
  },

  {
    title: 'Amnesty International Italia — Attivista Universitario',
    description: "Unisciti a un gruppo universitario Amnesty e partecipa a campagne per i diritti umani, letter writing, advocacy e organizzazione di eventi. Formazione su diritto internazionale e comunicazione per i diritti umani inclusa.",
    type: 'VOLUNTEERING' as const,
    url: 'https://example.com/amnesty-italia-universitario',
    organizer: 'Amnesty International Italia',
    location: 'Italy',
    country: 'IT',
    isAbroad: false,
    isRemote: true,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['volunteering', 'human-rights', 'amnesty', 'advocacy', 'italy', 'free'],
    sourceId: 'mock-amnesty-italia-universitario',
  },

  // ── EVENT ──────────────────────────────────────────────────────────────────

  {
    title: 'Fuori Salone Milano — Workshop Studenti Design',
    description: "Durante il Fuori Salone del Mobile, IED e Politecnico organizzano workshop gratuiti aperti a studenti di design e architettura. Prototipazione rapida, materiali forniti, e accesso all'esposizione professionale.",
    type: 'EVENT' as const,
    url: 'https://example.com/fuorisalone-workshop-design',
    organizer: 'Fuori Salone / IED Milano',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 1,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['DESIGN', 'ARCHITECTURE'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['event', 'design', 'milan', 'fuorisalone', 'workshop', 'free'],
    sourceId: 'mock-fuorisalone-workshop-design',
  },

  {
    title: 'Startup Weekend — 54 Ore per Creare un\'Impresa',
    description: "Startup Weekend è un evento globale dove in 54 ore costruisci un prototipo e un pitch deck per una startup. Team multidisciplinari, mentori locali, e possibilità di vincere premi e accelerazione. Edizioni in 20+ città italiane.",
    type: 'EVENT' as const,
    url: 'https://example.com/startup-weekend-italia',
    organizer: 'Techstars',
    location: 'Italy (multiple cities)',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 2,
    cost: 50,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['event', 'startup', 'entrepreneurship', 'weekend', 'italy', 'networking'],
    sourceId: 'mock-startup-weekend-italia',
  },

  {
    title: 'Digital Days Roma — Festival della Trasformazione Digitale',
    description: "3 giorni di keynote, workshop e tavole rotonde sulla trasformazione digitale in Italia. Speaker da Google, Microsoft, CDP e startup italiane. Accesso gratuito per studenti universitari con badge Student.",
    type: 'EVENT' as const,
    url: 'https://example.com/digital-days-roma',
    organizer: 'Agid / ICT & Management',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 3,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'ECONOMICS', 'ENGINEERING', 'BUSINESS'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['event', 'digital', 'tech', 'rome', 'networking', 'free'],
    sourceId: 'mock-digital-days-roma',
  },

  {
    title: 'Maker Faire Rome — Europe\'s Biggest Maker Event',
    description: "Maker Faire Rome è il più grande evento europeo per maker, innovatori e appassionati di tecnologia. 700+ espositori, 100.000+ visitatori. Studenti universitari possono esporre i loro progetti nella sezione Young Makers.",
    type: 'EVENT' as const,
    url: 'https://example.com/maker-faire-rome',
    organizer: 'Camera di Commercio di Roma',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 3,
    cost: 12,
    hasScholarship: false,
    eligibleFields: ['ENGINEERING', 'COMPUTER_SCIENCE', 'DESIGN', 'PHYSICAL_SCIENCES'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['event', 'maker', 'hardware', 'innovation', 'rome', 'affordable'],
    sourceId: 'mock-maker-faire-rome',
  },

  {
    title: 'Settimana della Salute Mentale — Workshop Gratuiti',
    description: "Durante la Settimana Mondiale della Salute Mentale, l'Università La Sapienza organizza workshop gratuiti su mindfulness, gestione dello stress da esame, e supporto psicologico. Aperto a tutti gli studenti.",
    type: 'EVENT' as const,
    url: 'https://example.com/settimana-salute-mentale-sapienza',
    organizer: "Università La Sapienza di Roma",
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 5,
    cost: 0,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['event', 'wellbeing', 'mental-health', 'rome', 'free', 'workshop'],
    sourceId: 'mock-settimana-salute-mentale-sapienza',
  },

  // ── ADDITIONAL MIXED ────────────────────────────────────────────────────────

  {
    title: 'Stage Architettura — Studio Renzo Piano Building Workshop',
    description: "Il RPBW seleziona ogni anno 2–3 stagisti per supportare i team di progetto su edifici iconici in tutto il mondo. Requisiti: eccellenti capacità grafiche (AutoCAD, Revit, rendering), portfolio solido, inglese fluente.",
    type: 'STAGE' as const,
    url: 'https://example.com/stage-rpbw',
    company: 'Renzo Piano Building Workshop',
    location: 'Genoa / Paris',
    city: 'Genoa',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 1000,
    eligibleFields: ['ARCHITECTURE'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['stage', 'architecture', 'design', 'genoa', 'prestige', 'paid'],
    sourceId: 'mock-stage-rpbw',
  },

  {
    title: 'Social Media Manager — Startup Sportiva Remoto',
    description: "Startup che sviluppa app per atleti amatoriali cerca social media manager part-time da remoto. Gestione Instagram, TikTok, e LinkedIn. Creatività + buon senso visivo richiesti. 15 ore/settimana, perfetto accanto agli studi.",
    type: 'STAGE' as const,
    url: 'https://example.com/social-media-manager-sport-startup',
    company: 'SportTrack App',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 350,
    eligibleFields: ['BUSINESS', 'HUMANITIES', 'DESIGN'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['stage', 'social-media', 'remote', 'sport', 'part-time', 'paid'],
    sourceId: 'mock-social-media-manager-sport-startup',
  },

  {
    title: 'Internship Sostenibilità — Multinazionale FMCG Milano',
    description: "Leading consumer goods company seeks a sustainability intern to support the ESG reporting team, supplier audits, and circular economy projects. 6-month internship, hybrid mode. Excellent Excel and communication skills required.",
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/internship-sustainability-fmcg',
    company: 'NaturaGroup SpA',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 950,
    eligibleFields: ['ECONOMICS', 'ENGINEERING', 'LIFE_SCIENCES', 'BUSINESS'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['internship', 'sustainability', 'esg', 'milan', 'fmcg', 'paid', 'hybrid'],
    sourceId: 'mock-internship-sustainability-fmcg',
  },

  {
    title: 'GovTech Internship — Ministero per l\'Innovazione Digitale',
    description: "Il Dipartimento per la Trasformazione Digitale cerca stagisti per supportare i team di servizi pubblici digitali (SPID, IO, PagoPA). Lavorerai su analisi dei dati, comunicazione istituzionale, o sviluppo prodotto.",
    type: 'STAGE' as const,
    url: 'https://example.com/govtech-internship-innovazione',
    company: "Dipartimento per la Trasformazione Digitale",
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: true,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 700,
    eligibleFields: ['COMPUTER_SCIENCE', 'ECONOMICS', 'LAW', 'POLITICAL_SCIENCE'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['stage', 'govtech', 'pubblica-amministrazione', 'digitale', 'rome', 'paid'],
    sourceId: 'mock-govtech-internship-innovazione',
  },

  {
    title: 'EMBL Research Internship — Biologia Molecolare Heidelberg',
    description: "The European Molecular Biology Laboratory offers 3-month internships for undergraduate students in cell biology, structural biology, and bioinformatics labs. Fully funded including stipend, accommodation in EMBL campus, and flights.",
    type: 'RESEARCH' as const,
    url: 'https://example.com/embl-internship-heidelberg',
    organizer: 'EMBL – European Molecular Biology Laboratory',
    location: 'Heidelberg, Germany',
    city: 'Heidelberg',
    country: 'DE',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 90,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Stipend €1,400/month + accommodation on campus + travel reimbursement.',
    stipend: 1400,
    eligibleFields: ['LIFE_SCIENCES', 'MEDICINE', 'COMPUTER_SCIENCE', 'PHYSICAL_SCIENCES'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 5,
    tags: ['research', 'biology', 'embl', 'germany', 'abroad', 'fully-funded', 'prestige'],
    sourceId: 'mock-embl-internship-heidelberg',
  },

  {
    title: 'AI Ethics Fellowship — Mozilla Foundation',
    description: "Mozilla Foundation selects 10 fellows annually to work on internet health, AI ethics, and digital rights. 10 months, remote-first with 2 in-person retreats. Fellows receive a $60,000 stipend and work on independent research or advocacy projects.",
    type: 'FELLOWSHIP' as const,
    url: 'https://example.com/mozilla-ai-ethics-fellowship',
    organizer: 'Mozilla Foundation',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: '$60,000 USD stipend for 10 months.',
    stipend: 5500,
    eligibleFields: ['COMPUTER_SCIENCE', 'LAW', 'POLITICAL_SCIENCE', 'HUMANITIES'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['fellowship', 'ai-ethics', 'mozilla', 'remote', 'fully-funded', 'prestige'],
    sourceId: 'mock-mozilla-ai-ethics-fellowship',
  },

  {
    title: 'Barcamp Startup Napoli — Workshop & Pitch Day',
    description: "Evento non-conferenza a Napoli dove chiunque può proporre e tenere una sessione. Temi: startup, no-profit, tech sociale, arte digitale. Giornata di workshop + pitch finale. Gratuito, pranzo incluso.",
    type: 'EVENT' as const,
    url: 'https://example.com/barcamp-startup-napoli',
    organizer: 'Campania Startup Hub',
    location: 'Naples, Italy',
    city: 'Naples',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 1,
    cost: 0,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['event', 'startup', 'naples', 'workshop', 'networking', 'free'],
    sourceId: 'mock-barcamp-startup-napoli',
  },

  {
    title: 'NASA Space Apps Challenge — Edizione Italia',
    description: "La NASA Space Apps Challenge è il più grande hackathon spaziale al mondo. Team di studenti sviluppano soluzioni a sfide legate alla Terra, allo spazio, e ai dati satellite. 24/48 ore, premi globali, sede italiana a Bologna.",
    type: 'HACKATHON' as const,
    url: 'https://example.com/nasa-space-apps-italia',
    organizer: 'NASA / Local Organizers Italy',
    location: 'Bologna, Italy',
    city: 'Bologna',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 2,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ENGINEERING', 'COMPUTER_SCIENCE', 'PHYSICAL_SCIENCES', 'DESIGN'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['hackathon', 'nasa', 'space', 'bologna', 'science', 'free'],
    sourceId: 'mock-nasa-space-apps-italia',
  },

  {
    title: 'Scuola Estiva di Diritto Europeo — Jean Monnet',
    description: "Summer school di 2 settimane a Firenze su diritto dell'Unione Europea, istituzioni comunitarie, e giurisprudenza della CGUE. Docenti da università di tutta Europa. Borsa di studio per studenti italiani selezionati.",
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://example.com/jean-monnet-summer-law-firenze',
    organizer: 'European University Institute',
    location: 'Florence, Italy',
    city: 'Florence',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 14,
    cost: 1200,
    hasScholarship: true,
    scholarshipDetails: '5 borse complete per studenti di università italiane non fiorentine.',
    eligibleFields: ['LAW', 'POLITICAL_SCIENCE'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'eu-law', 'jean-monnet', 'florence', 'scholarship'],
    sourceId: 'mock-jean-monnet-summer-law-firenze',
  },

  {
    title: 'EIT Health Student Challenge — Innovazione Sanitaria',
    description: "EIT Health lancia una sfida per studenti europei: sviluppare soluzioni innovative per il sistema sanitario. Team interdisciplinari (medici, ingegneri, economisti). Finalisti partecipano a una bootcamp a Barcellona + pitch davanti a investitori.",
    type: 'COMPETITION' as const,
    url: 'https://example.com/eit-health-student-challenge',
    organizer: 'EIT Health',
    location: 'Barcelona, Spain',
    city: 'Barcelona',
    country: 'ES',
    isAbroad: true,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Viaggio e alloggio coperti per i finalisti che partecipano alla bootcamp finale.',
    eligibleFields: ['MEDICINE', 'ENGINEERING', 'COMPUTER_SCIENCE', 'BUSINESS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['competition', 'health', 'innovation', 'eu', 'barcelona', 'interdisciplinary'],
    sourceId: 'mock-eit-health-student-challenge',
  },

  {
    title: 'Internship HR & Talent Acquisition — Scale-up Tech Firenze',
    description: "Startup tecnologica in forte crescita cerca un HR intern per supportare il recruiting, employer branding, e people operations. Lavorerai su ATS, screening CV, e job descriptions. Buona conoscenza di LinkedIn Recruiter.",
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/internship-hr-firenze',
    company: 'HireTech Srl',
    location: 'Florence, Italy',
    city: 'Florence',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 750,
    eligibleFields: ['BUSINESS', 'PSYCHOLOGY', 'HUMANITIES'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 5,
    tags: ['internship', 'hr', 'recruiting', 'florence', 'hybrid', 'paid'],
    sourceId: 'mock-internship-hr-firenze',
  },

  {
    title: 'Borsa di Studio Fondazione Cariplo — Ricerca Sociale',
    description: "Fondazione Cariplo eroga borse di ricerca per studenti magistrali e dottorandi impegnati in studi su welfare, povertà educativa, e terzo settore in Lombardia. Importo fino a €14.400 l'anno.",
    type: 'RESEARCH' as const,
    url: 'https://example.com/fondazione-cariplo-borsa',
    organizer: 'Fondazione Cariplo',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Borsa annuale di €14.400 per ricercatori selezionati.',
    stipend: 1200,
    eligibleFields: ['ECONOMICS', 'PSYCHOLOGY', 'POLITICAL_SCIENCE', 'EDUCATION'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['research', 'borsa', 'welfare', 'social', 'lombardia', 'fully-funded'],
    sourceId: 'mock-fondazione-cariplo-borsa',
  },

  {
    title: 'Stage Giornalismo — Testata Digitale Investigativa',
    description: "Testata giornalistica indipendente italiana cerca stagista per data journalism e fact-checking. Lavorerai su inchieste con FOIA, database pubblici, e strumenti di data visualization (Flourish, Datawrapper). Scrittura giornalistica richiesta.",
    type: 'STAGE' as const,
    url: 'https://example.com/stage-giornalismo-investigativo',
    company: 'Irpimedia',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: true,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 500,
    eligibleFields: ['HUMANITIES', 'POLITICAL_SCIENCE', 'COMPUTER_SCIENCE'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['stage', 'journalism', 'data', 'investigative', 'rome', 'paid'],
    sourceId: 'mock-stage-giornalismo-investigativo',
  },

  {
    title: 'Volunteer Teaching Assistant — Code.org Scuole Italiane',
    description: "Aiuta insegnanti delle scuole medie e superiori a introdurre l'informatica in classe con il curriculum Code.org. Formazione online di 4 ore, poi affiancamento in classe 1 volta/settimana. Riconoscimento delle ore come tirocinio curricolare.",
    type: 'VOLUNTEERING' as const,
    url: 'https://example.com/codeorg-teaching-assistant-italy',
    organizer: 'Code.org / Programma il Futuro',
    location: 'Italy',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'EDUCATION', 'MATHEMATICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['volunteering', 'teaching', 'coding', 'education', 'schools', 'italy', 'free'],
    sourceId: 'mock-codeorg-teaching-assistant-italy',
  },

  {
    title: 'Bain & Company On-Campus Insight Day',
    description: "Bain organizza giornate di orientamento per studenti universitari interessati alla consulenza strategica. Presentazione del settore, case interview interattivo, e networking con consulenti Bain. Gratuito, pranzo incluso. Sedi: Milano e Roma.",
    type: 'EVENT' as const,
    url: 'https://example.com/bain-insight-day',
    company: 'Bain & Company',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 1,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'MATHEMATICS', 'ENGINEERING'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 5,
    tags: ['event', 'consulting', 'bain', 'networking', 'career', 'milan', 'free'],
    sourceId: 'mock-bain-insight-day',
  },

  {
    title: 'Hackathon Trasporto Pubblico — FS Italiane Open Data',
    description: "Ferrovie dello Stato mette a disposizione dati aperti su treni, percorsi e ritardi per un hackathon nazionale. 36 ore, sfide su accessibility, predictive maintenance, e UX delle app di mobilità. Premio totale €18.000.",
    type: 'HACKATHON' as const,
    url: 'https://example.com/hackathon-fs-italiane-opendata',
    organizer: 'Ferrovie dello Stato Italiane',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 2,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING', 'DESIGN'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['hackathon', 'transport', 'open-data', 'fs', 'rome', 'prize', 'free'],
    sourceId: 'mock-hackathon-fs-italiane-opendata',
  },

  {
    title: 'Stage Comunicazione Scientifica — Fondazione AIRC',
    description: "La Fondazione AIRC per la ricerca sul cancro cerca uno stagista per l'ufficio comunicazione. Produzione di contenuti divulgativi (articoli, video, social), gestione della newsletter, e supporto agli eventi istituzionali. Biologia o scienze della comunicazione.",
    type: 'STAGE' as const,
    url: 'https://example.com/stage-comunicazione-airc',
    company: 'Fondazione AIRC',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 650,
    eligibleFields: ['LIFE_SCIENCES', 'HUMANITIES', 'MEDICINE'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['stage', 'comunicazione', 'scienze', 'airc', 'milan', 'paid'],
    sourceId: 'mock-stage-comunicazione-airc',
  },

  {
    title: 'Google Summer of Code — Open Source',
    description: "Google Summer of Code is a global program offering student stipends to work on open source projects over 12 weeks. You are mentored by experienced developers from organizations like Mozilla, Apache, CNCF, and many more. Stipend up to $6,600.",
    type: 'RESEARCH' as const,
    url: 'https://example.com/google-summer-of-code',
    organizer: 'Google',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    durationDays: 84,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Stipend from $1,500 to $6,600 depending on country and project size.',
    stipend: 2000,
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING', 'MATHEMATICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['research', 'open-source', 'google', 'gsoc', 'remote', 'paid', 'prestige'],
    sourceId: 'mock-google-summer-of-code',
  },

  {
    title: 'Bootcamp Imprenditoria Femminile — VC Incluse',
    description: "Programma intensivo di 6 settimane per studentesse e giovani professioniste che vogliono avviare un'impresa. Mentorship da fondatrici di startup di successo, workshop su pitch, fundraising, e team building. Totalmente gratuito, selezione competitiva.",
    type: 'BOOTCAMP' as const,
    url: 'https://example.com/bootcamp-imprenditoria-femminile',
    organizer: 'VC Incluse',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 42,
    cost: 0,
    hasScholarship: false,
    eligibleFields: [] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['bootcamp', 'entrepreneurship', 'women', 'startup', 'milan', 'free'],
    sourceId: 'mock-bootcamp-imprenditoria-femminile',
  },

  {
    title: 'Progetto Erasmus+ KA1 — Mobilità Staff Universitario',
    description: "Bando Erasmus+ KA1 per mobilità individuale: partecipa a un job shadowing presso un'università europea partner. 5–14 giorni, volo e soggiorno rimborsati. Aperto a studenti iscritti a corsi di dottorato come mobility participants.",
    type: 'EXCHANGE' as const,
    url: 'https://example.com/erasmus-ka1-staff-mobility',
    organizer: 'European Commission / EACEA',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 10,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Rimborso viaggio + indennità giornaliera €110–160 a seconda del paese.',
    stipend: 160,
    eligibleFields: [] as any[],
    minYearOfStudy: 5,
    maxYearOfStudy: 6,
    tags: ['exchange', 'erasmus', 'ka1', 'europe', 'fully-funded', 'abroad'],
    sourceId: 'mock-erasmus-ka1-staff-mobility',
  },

  {
    title: 'Premio Nazionale Tesi di Laurea — Banca Etica',
    description: "Banca Etica premia ogni anno le migliori tesi magistrali su finanza etica, economia solidale, e banca cooperativa. Primo premio €3.000, secondo €1.500. Candidatura entro 1 anno dalla discussione della tesi.",
    type: 'COMPETITION' as const,
    url: 'https://example.com/premio-tesi-banca-etica',
    organizer: 'Banca Etica',
    location: 'Italy',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ECONOMICS', 'LAW', 'POLITICAL_SCIENCE', 'BUSINESS'] as any[],
    minYearOfStudy: 5,
    maxYearOfStudy: 6,
    tags: ['competition', 'tesi', 'finanza-etica', 'premio', 'italy'],
    sourceId: 'mock-premio-tesi-banca-etica',
  },

  {
    title: 'Internship Supply Chain — Pharma Multinazionale Firenze',
    description: "Global pharma company seeks a supply chain management intern to support demand planning, vendor management, and S&OP processes. 6-month internship, full-time, hybrid. SAP knowledge is a plus.",
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/internship-supply-chain-pharma',
    company: 'PharmaCo Italia',
    location: 'Florence, Italy',
    city: 'Florence',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 900,
    eligibleFields: ['ENGINEERING', 'ECONOMICS', 'BUSINESS'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['internship', 'supply-chain', 'pharma', 'florence', 'paid', 'sap'],
    sourceId: 'mock-internship-supply-chain-pharma',
  },

  {
    title: 'Conferenza Nazionale Studenti di Medicina — Elective Showcase',
    description: "La SISM organizza ogni anno una conferenza per studenti di medicina dove presentare i risultati degli elective clerkship internazionali, workshop su soft skills cliniche, e networking con medici in formazione da tutta Italia.",
    type: 'CONFERENCE' as const,
    url: 'https://example.com/conferenza-sism-medicina',
    organizer: 'SISM – Segretariato Italiano Studenti in Medicina',
    location: 'Bologna, Italy',
    city: 'Bologna',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 30,
    hasScholarship: true,
    scholarshipDetails: 'Borse di partecipazione per studenti fuori sede con reddito ISEE basso.',
    eligibleFields: ['MEDICINE'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['conference', 'medicine', 'sism', 'bologna', 'networking', 'affordable'],
    sourceId: 'mock-conferenza-sism-medicina',
  },

  {
    title: 'Studio Legale Freshfields — First Steps Program',
    description: "Freshfields Bruckhaus Deringer invita studenti di terzo/quarto anno di Giurisprudenza a partecipare al programma First Steps: 2 giorni in studio, simulazioni di negoziato, networking con soci e associate. Milano. Rimborso spese viaggio.",
    type: 'EVENT' as const,
    url: 'https://example.com/freshfields-first-steps-milan',
    company: 'Freshfields Bruckhaus Deringer',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 2,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['LAW'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 5,
    tags: ['event', 'law', 'freshfields', 'milan', 'career', 'networking', 'free'],
    sourceId: 'mock-freshfields-first-steps-milan',
  },

  {
    title: 'Tirocinio Psicologia Clinica — Servizio di Consulenza Universitario',
    description: "Il Servizio di Consulenza Psicologica dell'Università di Torino accoglie tirocinanti iscritti alla laurea magistrale in Psicologia Clinica. Supervisione settimanale garantita, 150+ ore di pratica riconoscibili per l'abilitazione.",
    type: 'STAGE' as const,
    url: 'https://example.com/tirocinio-psicologia-torino',
    company: "Università degli Studi di Torino – SCP",
    location: 'Turin, Italy',
    city: 'Turin',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['PSYCHOLOGY'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['stage', 'psychology', 'clinical', 'torino', 'tirocinio', 'abilitazione'],
    sourceId: 'mock-tirocinio-psicologia-torino',
  },

  {
    title: 'Sustainability Reporting Challenge — GRI Standard',
    description: "Sfida per team universitari: produrre un sustainability report secondo gli standard GRI per un'azienda reale (PMI italiana partner). I migliori report vengono pubblicati e presentati alla conferenza finale. Categoria: università italiane.",
    type: 'COMPETITION' as const,
    url: 'https://example.com/sustainability-reporting-gri-challenge',
    organizer: 'CSR Manager Network Italia',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: true,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'ENGINEERING', 'LAW'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['competition', 'sustainability', 'esg', 'gri', 'reporting', 'italy'],
    sourceId: 'mock-sustainability-reporting-gri-challenge',
  },

  {
    title: 'Internship Intelligenza Artificiale — DeepMind Paris (Stage)',
    description: "DeepMind Research Paris occasionally accepts research interns from top European universities for 3–6 month projects in reinforcement learning, safety, and multimodal AI. Strong math background and ML research experience required.",
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/deepmind-paris-research-intern',
    company: 'DeepMind / Google',
    location: 'Paris, France',
    city: 'Paris',
    country: 'FR',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 3000,
    eligibleFields: ['COMPUTER_SCIENCE', 'MATHEMATICS', 'PHYSICAL_SCIENCES'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['internship', 'ai', 'deepmind', 'paris', 'abroad', 'research', 'prestige', 'paid'],
    sourceId: 'mock-deepmind-paris-research-intern',
  },

  {
    title: 'ESA — Giovani in Agenzia Spaziale Europea',
    description: "L'Agenzia Spaziale Europea offre posizioni YGT (Young Graduate Trainee) della durata di 12 mesi nelle sue sedi di Parigi, Madrid, Frascati, Darmstadt e Noordwijk. Stipendio €2.100/mese + sussidio alloggio. Aperto a laureandi magistrali.",
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/esa-ygt-program',
    company: 'ESA – European Space Agency',
    location: 'Frascati / Darmstadt / Madrid',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 365,
    cost: 0,
    hasScholarship: false,
    stipend: 2100,
    eligibleFields: ['ENGINEERING', 'PHYSICAL_SCIENCES', 'COMPUTER_SCIENCE', 'MATHEMATICS'] as any[],
    minYearOfStudy: 5,
    maxYearOfStudy: 6,
    tags: ['internship', 'space', 'esa', 'engineering', 'europe', 'paid', 'prestige'],
    sourceId: 'mock-esa-ygt-program',
  },

  {
    title: 'Club di Lettura Filosofia — Università di Bologna (Online)',
    description: "Il Dipartimento di Filosofia di Bologna organizza un club di lettura online bisettimanale aperto a studenti di ogni facoltà. Testi: Arendt, Foucault, Habermas, e filosofia contemporanea. Gratuito, nessun obbligo di frequenza.",
    type: 'EXTRACURRICULAR' as const,
    url: 'https://example.com/club-lettura-filosofia-bologna',
    organizer: 'Università di Bologna – Dip. Filosofia',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['HUMANITIES', 'POLITICAL_SCIENCE', 'LAW', 'PSYCHOLOGY'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['extracurricular', 'philosophy', 'reading', 'online', 'bologna', 'free'],
    sourceId: 'mock-club-lettura-filosofia-bologna',
  },

  {
    title: 'GreenHouse Accelerator — Startup Agricoltura Urbana',
    description: "GreenHouse è un programma di accelerazione per startup nel settore foodtech e agricoltura urbana. 12 settimane, equity-free, con €10.000 di finanziamento seed, accesso a laboratori e mentorship da esperti del settore alimentare.",
    type: 'BOOTCAMP' as const,
    url: 'https://example.com/greenhouse-accelerator-foodtech',
    organizer: 'GreenHouse Accelerator',
    location: 'Turin, Italy',
    city: 'Turin',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 84,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: '€10,000 seed funding equity-free + coworking space included.',
    eligibleFields: ['LIFE_SCIENCES', 'ENGINEERING', 'BUSINESS', 'ECONOMICS'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['bootcamp', 'foodtech', 'startup', 'accelerator', 'torino', 'funded'],
    sourceId: 'mock-greenhouse-accelerator-foodtech',
  },

  {
    title: 'McKinsey & Company — Giovani Talenti Scholarship',
    description: "McKinsey eroga borse di studio da €5.000 a studenti eccellenti di università italiane iscritti agli ultimi due anni di laurea magistrale. Criteri: GPA, leadership extracurriculare, e una lettera motivazionale. Include un workshop esclusivo in sede a Milano.",
    type: 'FELLOWSHIP' as const,
    url: 'https://example.com/mckinsey-giovani-talenti-scholarship',
    organizer: 'McKinsey & Company',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Borsa di €5.000 + workshop esclusivo a Milano con consulenti McKinsey.',
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'ENGINEERING', 'MATHEMATICS'] as any[],
    minYearOfStudy: 4,
    maxYearOfStudy: 6,
    tags: ['fellowship', 'scholarship', 'mckinsey', 'milan', 'prestige', 'consulting'],
    sourceId: 'mock-mckinsey-giovani-talenti-scholarship',
  },

  {
    title: 'Stage Consulenza Strategica — Big4 Milano',
    description: "Una delle Big4 della consulenza cerca stagisti per il team di Strategy & Operations di Milano. Lavorerai su analisi di mercato, modelli di business, e presentazioni executive per clienti Fortune 500. Eccellente formazione e opportunità di assunzione.",
    type: 'STAGE' as const,
    url: 'https://example.com/stage-big4-strategy-milano',
    company: 'PwC Italia',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 1000,
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'ENGINEERING', 'MATHEMATICS'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['stage', 'consulting', 'big4', 'strategy', 'milan', 'paid', 'prestige'],
    sourceId: 'mock-stage-big4-strategy-milano',
  },

  {
    title: 'Open Innovation Challenge — Leonardo SpA (Difesa & Aerospazio)',
    description: "Leonardo lancia una sfida di open innovation per studenti universitari su: cybersecurity, AI per difesa, e droni autonomi. Finalisti presentano il progetto a Roma e concorrono per €20.000 in premi e un percorso accelerato di recruitment.",
    type: 'COMPETITION' as const,
    url: 'https://example.com/open-innovation-leonardo-spa',
    organizer: 'Leonardo SpA',
    location: 'Rome, Italy',
    city: 'Rome',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'HYBRID' as const,
    cost: 0,
    hasScholarship: false,
    eligibleFields: ['ENGINEERING', 'COMPUTER_SCIENCE', 'PHYSICAL_SCIENCES', 'MATHEMATICS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['competition', 'aerospace', 'defense', 'ai', 'rome', 'prize', 'leonardo'],
    sourceId: 'mock-open-innovation-leonardo-spa',
  },

  {
    title: 'Internship Blockchain & Web3 — DeFi Startup Amsterdam',
    description: "Early-stage DeFi startup hiring a smart contract developer intern. You'll write Solidity contracts, write tests with Hardhat, and contribute to a live protocol on Ethereum mainnet. Remote-first, 3 months, paid in EUR (no crypto).",
    type: 'INTERNSHIP' as const,
    url: 'https://example.com/internship-blockchain-amsterdam',
    company: 'ChainFlow Labs',
    location: 'Amsterdam, Netherlands',
    city: 'Amsterdam',
    country: 'NL',
    isAbroad: true,
    isRemote: true,
    format: 'ONLINE' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 1200,
    eligibleFields: ['COMPUTER_SCIENCE', 'MATHEMATICS'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['internship', 'blockchain', 'web3', 'solidity', 'remote', 'abroad', 'paid'],
    sourceId: 'mock-internship-blockchain-amsterdam',
  },

  {
    title: 'Fondazione Rui — Borsa Studio per Studenti Cattolici',
    description: "La Fondazione Rui eroga borse di studio annuali per studenti universitari iscritti nelle proprie residenze universitarie a Milano, Roma, e Barcellona. Include alloggio, formazione integrale e tutoraggio accademico. Requisiti: merito e progetto personale.",
    type: 'FELLOWSHIP' as const,
    url: 'https://example.com/fondazione-rui-borsa-studio',
    organizer: 'Fondazione Rui',
    location: 'Milan / Rome / Barcelona',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Alloggio in residenza universitaria a prezzo ridotto + borsa merito annuale fino a €4.000.',
    eligibleFields: [] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['fellowship', 'scholarship', 'alloggio', 'milan', 'rome', 'merito'],
    sourceId: 'mock-fondazione-rui-borsa-studio',
  },

  {
    title: 'Urban Planning Summer Intensive — TU Delft',
    description: "Two-week intensive summer school at TU Delft on sustainable urban planning and smart cities. Studio projects, city tours, and workshops with planners from Dutch municipalities. Taught in English. Certificate issued.",
    type: 'SUMMER_PROGRAM' as const,
    url: 'https://example.com/tu-delft-urban-planning-summer',
    organizer: 'TU Delft',
    location: 'Delft, Netherlands',
    city: 'Delft',
    country: 'NL',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 14,
    cost: 2200,
    hasScholarship: false,
    eligibleFields: ['ARCHITECTURE', 'ENGINEERING', 'POLITICAL_SCIENCE'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['summer-school', 'urban-planning', 'tu-delft', 'netherlands', 'abroad', 'smart-city'],
    sourceId: 'mock-tu-delft-urban-planning-summer',
  },

  {
    title: 'Internship Moda & Lusso — Casa di Moda Milanese',
    description: "Casa di moda italiana di lusso cerca stagista per il dipartimento di product development. Ti occuperai di trend research, sviluppo collezioni, rapporti con fornitori tessili italiani, e presentazioni showroom. Ottimo per chi studia Design della Moda.",
    type: 'STAGE' as const,
    url: 'https://example.com/stage-moda-lusso-milano',
    company: 'MilanoMaison Srl',
    location: 'Milan, Italy',
    city: 'Milan',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 750,
    eligibleFields: ['DESIGN', 'BUSINESS'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['stage', 'fashion', 'luxury', 'design', 'milan', 'paid'],
    sourceId: 'mock-stage-moda-lusso-milano',
  },

  {
    title: 'Conferenza TEI — Testo Codifica Informatica per le Umanistiche',
    description: "Annual international conference of the Text Encoding Initiative consortium. Presents digital humanities research using TEI XML. Includes a student workshop and poster session. Travel grants available for accepted presenters.",
    type: 'CONFERENCE' as const,
    url: 'https://example.com/tei-conference-digital-humanities',
    organizer: 'TEI Consortium',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 80,
    hasScholarship: true,
    scholarshipDetails: 'Travel grants of up to €500 for accepted student presenters.',
    eligibleFields: ['HUMANITIES', 'COMPUTER_SCIENCE', 'EDUCATION'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['conference', 'digital-humanities', 'tei', 'xml', 'research', 'travel-grant'],
    sourceId: 'mock-tei-conference-digital-humanities',
  },

  {
    title: 'Bootcamp DevOps & Cloud — AWS Partner',
    description: "Bootcamp pratico di 4 settimane su Docker, Kubernetes, CI/CD pipelines con GitHub Actions, e AWS (EC2, S3, Lambda, RDS). Include preparazione all'esame AWS Cloud Practitioner con voucher incluso. Remoto, live sessions + lab asincroni.",
    type: 'BOOTCAMP' as const,
    url: 'https://example.com/bootcamp-devops-aws',
    organizer: 'CloudPath Academy',
    isAbroad: false,
    isRemote: true,
    format: 'ONLINE' as const,
    durationDays: 28,
    cost: 1200,
    hasScholarship: true,
    scholarshipDetails: 'Voucher esame AWS incluso. Scholarship del 50% per studenti universitari con ISEE < 25.000.',
    eligibleFields: ['COMPUTER_SCIENCE', 'ENGINEERING'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 6,
    tags: ['bootcamp', 'devops', 'aws', 'cloud', 'kubernetes', 'remote', 'certificate'],
    sourceId: 'mock-bootcamp-devops-aws',
  },

  {
    title: 'Stage Economia Circolare — Confindustria Veneto',
    description: "Confindustria Veneto e la Regione Veneto offrono stage in aziende manifatturiere locali per lavorare su progetti di economia circolare: mappatura flussi materiali, LCA, e certificazioni ambientali ISO 14001. Rimborso spese + tutoraggio.",
    type: 'STAGE' as const,
    url: 'https://example.com/stage-economia-circolare-veneto',
    company: 'Confindustria Veneto',
    location: 'Vicenza / Padova / Treviso',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 0,
    hasScholarship: false,
    stipend: 700,
    eligibleFields: ['ENGINEERING', 'ECONOMICS', 'PHYSICAL_SCIENCES', 'LIFE_SCIENCES'] as any[],
    minYearOfStudy: 3,
    maxYearOfStudy: 6,
    tags: ['stage', 'economia-circolare', 'veneto', 'manufacturing', 'environment', 'paid'],
    sourceId: 'mock-stage-economia-circolare-veneto',
  },

  {
    title: 'European Youth Parliament — Sessione Nazionale Italia',
    description: "L'EYP Italia organizza sessioni regionali e una sessione nazionale dove studenti universitari dibattono come delegati su politiche europee. Seleziona la tua università, prepara una resolution, e vivi un weekend di diplomazia simulata.",
    type: 'EXTRACURRICULAR' as const,
    url: 'https://example.com/eyp-sessione-nazionale-italia',
    organizer: 'European Youth Parliament Italy',
    location: 'Italy (rotates)',
    country: 'IT',
    isAbroad: false,
    isRemote: false,
    format: 'IN_PERSON' as const,
    cost: 30,
    hasScholarship: true,
    scholarshipDetails: 'Borse di partecipazione per studenti con difficoltà economiche.',
    eligibleFields: ['POLITICAL_SCIENCE', 'LAW', 'ECONOMICS', 'HUMANITIES'] as any[],
    minYearOfStudy: 1,
    maxYearOfStudy: 6,
    tags: ['extracurricular', 'eyp', 'politics', 'europe', 'debate', 'italy'],
    sourceId: 'mock-eyp-sessione-nazionale-italia',
  },

  {
    title: 'Erasmus+ Semestre a Vienna — WU Wirtschaftsuniversität',
    description: "Opportunità Erasmus+ alla Vienna University of Economics and Business. Corsi in inglese e tedesco in management, finance, e information systems. Borsa Erasmus €500/mese. Città vivace e ottimi collegamenti europei.",
    type: 'EXCHANGE' as const,
    url: 'https://example.com/erasmus-wu-vienna',
    organizer: 'WU Vienna University of Economics and Business',
    location: 'Vienna, Austria',
    city: 'Vienna',
    country: 'AT',
    isAbroad: true,
    isRemote: false,
    format: 'IN_PERSON' as const,
    durationDays: 150,
    cost: 0,
    hasScholarship: true,
    scholarshipDetails: 'Borsa Erasmus+ €500/mese erogata dall\'università di provenienza.',
    stipend: 500,
    eligibleFields: ['ECONOMICS', 'BUSINESS', 'COMPUTER_SCIENCE'] as any[],
    minYearOfStudy: 2,
    maxYearOfStudy: 5,
    tags: ['exchange', 'erasmus', 'vienna', 'austria', 'abroad', 'scholarship', 'economics'],
    sourceId: 'mock-erasmus-wu-vienna',
  },

];

async function run() {
  let created = 0;
  let updated = 0;
  let failed = 0;

  for (const opp of opportunities) {
    try {
      const result = await upsertManualOpportunity(opp as any);
      if (result.action === 'created') created++;
      else updated++;
      logger.info(`[MockSeed] ${result.action}: ${opp.title.slice(0, 60)}`);
    } catch (err) {
      logger.error(`[MockSeed] Failed: ${opp.title.slice(0, 60)} — ${err}`);
      failed++;
    }
  }

  logger.info(`[MockSeed] Done: ${created} created, ${updated} updated, ${failed} failed`);
  process.exit(failed > 0 ? 1 : 0);
}

run();
