/**
 * Seed list of Italian company apex domains. This is the primary Fase 1 input for
 * the fingerprint-based discovery: for each domain we resolve the careers page,
 * fingerprint the ATS, and route (permitted ATS → tier A, prohibited → no-harvest,
 * custom → tier B/C). Deliberately a mix of large enterprises (often on Workday/
 * SuccessFactors) and scaleups (often on Greenhouse/Lever) to exercise every path.
 *
 * Expandable: grown from company registries / public "top Italian companies" lists
 * across sectors. In Fase 2 this can be grown further from Registro Imprese /
 * OpenCorporates / ISTAT and search discovery.
 */
export interface CompanyDomainSeed {
  domain: string;
  name: string;
  sector?: string;
}

export const ITALY_COMPANY_DOMAINS: CompanyDomainSeed[] = [
  // Energy / utilities / industrial (frequently Workday / SuccessFactors → no-harvest expected)
  { domain: 'eni.com', name: 'Eni', sector: 'energy' },
  { domain: 'enel.com', name: 'Enel', sector: 'energy' },
  { domain: 'edison.it', name: 'Edison', sector: 'energy' },
  { domain: 'snam.it', name: 'Snam', sector: 'energy' },
  { domain: 'terna.it', name: 'Terna', sector: 'energy' },
  { domain: 'a2a.it', name: 'A2A', sector: 'utilities' },
  { domain: 'hera.it', name: 'Hera Group', sector: 'utilities' },
  { domain: 'iren.it', name: 'Iren', sector: 'utilities' },
  { domain: 'acea.it', name: 'Acea', sector: 'utilities' },
  { domain: 'saipem.com', name: 'Saipem', sector: 'energy' },
  { domain: 'leonardo.com', name: 'Leonardo', sector: 'aerospace' },
  { domain: 'fincantieri.com', name: 'Fincantieri', sector: 'shipbuilding' },
  { domain: 'avio.com', name: 'Avio', sector: 'aerospace' },
  { domain: 'thalesaleniaspace.com', name: 'Thales Alenia Space', sector: 'aerospace' },
  { domain: 'ansaldoenergia.com', name: 'Ansaldo Energia', sector: 'energy' },
  { domain: 'ansaldo-sts.com', name: 'Ansaldo STS / Hitachi Rail', sector: 'transport' },
  { domain: 'danieli.com', name: 'Danieli', sector: 'industrial' },
  { domain: 'prysmiangroup.com', name: 'Prysmian Group', sector: 'industrial' },
  { domain: 'salini-impregilo.com', name: 'Webuild', sector: 'construction' },
  { domain: 'webuildgroup.com', name: 'Webuild', sector: 'construction' },
  { domain: 'italcementi.com', name: 'Italcementi / HeidelbergCement Italia', sector: 'construction' },
  { domain: 'buzzi.it', name: 'Buzzi', sector: 'construction' },
  { domain: 'italgas.it', name: 'Italgas', sector: 'energy' },
  { domain: 'sogin.it', name: 'Sogin', sector: 'energy' },
  { domain: 'rina.org', name: 'RINA', sector: 'engineering' },
  { domain: 'bonatti.it', name: 'Bonatti', sector: 'engineering' },
  { domain: 'maire-tecnimont.com', name: 'MAIRE Tecnimont', sector: 'engineering' },
  { domain: 'technip.com', name: 'TechnipFMC Italia', sector: 'engineering' },

  // Automotive / industrial manufacturing
  { domain: 'pirelli.com', name: 'Pirelli', sector: 'automotive' },
  { domain: 'brembo.com', name: 'Brembo', sector: 'automotive' },
  { domain: 'stellantis.com', name: 'Stellantis', sector: 'automotive' },
  { domain: 'ferrari.com', name: 'Ferrari', sector: 'automotive' },
  { domain: 'lamborghini.com', name: 'Automobili Lamborghini', sector: 'automotive' },
  { domain: 'ducati.com', name: 'Ducati', sector: 'automotive' },
  { domain: 'piaggiogroup.com', name: 'Piaggio Group', sector: 'automotive' },
  { domain: 'iveco.com', name: 'Iveco', sector: 'automotive' },
  { domain: 'cnhindustrial.com', name: 'CNH Industrial', sector: 'automotive' },
  { domain: 'marelli.com', name: 'Marelli', sector: 'automotive' },
  { domain: 'sogefigroup.com', name: 'Sogefi', sector: 'automotive' },
  { domain: 'landirenzo.com', name: 'Landi Renzo', sector: 'automotive' },
  { domain: 'same-deutz-fahr.com', name: 'SDF Group', sector: 'industrial' },
  { domain: 'comer-industries.com', name: 'Comer Industries', sector: 'industrial' },
  { domain: 'interpump.it', name: 'Interpump Group', sector: 'industrial' },
  { domain: 'ima.it', name: 'IMA Group', sector: 'industrial' },
  { domain: 'coesia.com', name: 'Coesia', sector: 'industrial' },
  { domain: 'biesse.com', name: 'Biesse Group', sector: 'industrial' },
  { domain: 'scmgroup.com', name: 'SCM Group', sector: 'industrial' },
  { domain: 'sacmi.com', name: 'Sacmi', sector: 'industrial' },
  { domain: 'carraro.com', name: 'Carraro Group', sector: 'industrial' },
  { domain: 'zapi.com', name: 'Zapi Group', sector: 'industrial' },
  { domain: 'gruppofabbri.com', name: 'Gruppo Fabbri', sector: 'industrial' },
  { domain: 'techint.com', name: 'Tenaris (Techint)', sector: 'industrial' },
  { domain: 'tenaris.com', name: 'Tenaris', sector: 'industrial' },
  { domain: 'de-nora.com', name: 'De Nora', sector: 'industrial' },
  { domain: 'zambon.com', name: 'Zambon', sector: 'pharma' },

  // Finance / insurance / banking
  { domain: 'generali.com', name: 'Generali', sector: 'insurance' },
  { domain: 'unicredit.eu', name: 'UniCredit', sector: 'banking' },
  { domain: 'intesasanpaolo.com', name: 'Intesa Sanpaolo', sector: 'banking' },
  { domain: 'bancobpm.it', name: 'Banco BPM', sector: 'banking' },
  { domain: 'mps.it', name: 'Monte dei Paschi di Siena', sector: 'banking' },
  { domain: 'mediobanca.com', name: 'Mediobanca', sector: 'banking' },
  { domain: 'bper.it', name: 'BPER Banca', sector: 'banking' },
  { domain: 'credem.it', name: 'Credem', sector: 'banking' },
  { domain: 'fineco.it', name: 'FinecoBank', sector: 'banking' },
  { domain: 'mediolanum.com', name: 'Banca Mediolanum', sector: 'banking' },
  { domain: 'illimity.com', name: 'Illimity Bank', sector: 'fintech' },
  { domain: 'unipol.it', name: 'Unipol Group', sector: 'insurance' },
  { domain: 'poste.it', name: 'Poste Italiane', sector: 'logistics' },
  { domain: 'nexi.it', name: 'Nexi', sector: 'fintech' },
  { domain: 'satispay.com', name: 'Satispay', sector: 'fintech' },
  { domain: 'scalapay.com', name: 'Scalapay', sector: 'fintech' },
  { domain: 'prima.it', name: 'Prima Assicurazioni', sector: 'insurance' },
  { domain: 'moneyfarm.com', name: 'Moneyfarm', sector: 'fintech' },
  { domain: 'oval.money', name: 'Oval Money', sector: 'fintech' },
  { domain: 'younited.it', name: 'Younited', sector: 'fintech' },
  { domain: 'fabrick.com', name: 'Fabrick', sector: 'fintech' },
  { domain: 'sella.it', name: 'Banca Sella', sector: 'banking' },
  { domain: 'azimut.it', name: 'Azimut Group', sector: 'finance' },
  { domain: 'anima.it', name: 'Anima SGR', sector: 'finance' },
  { domain: 'cdp.it', name: 'Cassa Depositi e Prestiti', sector: 'finance' },
  { domain: 'borsaitaliana.it', name: 'Borsa Italiana / Euronext', sector: 'finance' },
  { domain: 'reply.com', name: 'Reply', sector: 'consulting' },

  // Fashion / luxury
  { domain: 'moncler.com', name: 'Moncler', sector: 'fashion' },
  { domain: 'prada.com', name: 'Prada Group', sector: 'fashion' },
  { domain: 'gucci.com', name: 'Gucci', sector: 'fashion' },
  { domain: 'armani.com', name: 'Giorgio Armani', sector: 'fashion' },
  { domain: 'versace.com', name: 'Versace', sector: 'fashion' },
  { domain: 'valentino.com', name: 'Valentino', sector: 'fashion' },
  { domain: 'bulgari.com', name: 'Bulgari', sector: 'fashion' },
  { domain: 'ferragamo.com', name: 'Salvatore Ferragamo', sector: 'fashion' },
  { domain: 'tods.com', name: "Tod's Group", sector: 'fashion' },
  { domain: 'zegna.com', name: 'Ermenegildo Zegna', sector: 'fashion' },
  { domain: 'diesel.com', name: 'Diesel (OTB Group)', sector: 'fashion' },
  { domain: 'otb.net', name: 'OTB Group', sector: 'fashion' },
  { domain: 'benetton.com', name: 'Benetton Group', sector: 'fashion' },
  { domain: 'ovs.it', name: 'OVS', sector: 'fashion' },
  { domain: 'calzedonia.com', name: 'Calzedonia Group', sector: 'fashion' },
  { domain: 'luxottica.com', name: 'Luxottica / EssilorLuxottica', sector: 'fashion' },
  { domain: 'safilogroup.com', name: 'Safilo Group', sector: 'fashion' },
  { domain: 'furla.com', name: 'Furla', sector: 'fashion' },
  { domain: 'trussardi.com', name: 'Trussardi', sector: 'fashion' },
  { domain: 'missoni.com', name: 'Missoni', sector: 'fashion' },
  { domain: 'dolcegabbana.com', name: 'Dolce & Gabbana', sector: 'fashion' },
  { domain: 'aeffe.com', name: 'Aeffe Group', sector: 'fashion' },
  { domain: 'geox.com', name: 'Geox', sector: 'fashion' },
  { domain: 'golden-goose.com', name: 'Golden Goose', sector: 'fashion' },
  { domain: 'moleskine.com', name: 'Moleskine', sector: 'retail' },
  { domain: 'kering.com', name: 'Kering Italia', sector: 'fashion' },

  // Food / beverage
  { domain: 'barilla.com', name: 'Barilla', sector: 'food' },
  { domain: 'ferrero.com', name: 'Ferrero', sector: 'food' },
  { domain: 'lavazza.com', name: 'Lavazza', sector: 'food' },
  { domain: 'illy.com', name: 'Illycaffè', sector: 'food' },
  { domain: 'campari.com', name: 'Campari Group', sector: 'beverage' },
  { domain: 'parmalat.com', name: 'Parmalat', sector: 'food' },
  { domain: 'granarolo.it', name: 'Granarolo', sector: 'food' },
  { domain: 'perfetti.com', name: 'Perfetti Van Melle', sector: 'food' },
  { domain: 'fileni.it', name: 'Fileni', sector: 'food' },
  { domain: 'amadori.it', name: 'Amadori', sector: 'food' },
  { domain: 'veronesi.it', name: 'Gruppo Veronesi', sector: 'food' },
  { domain: 'cremonini.com', name: 'Cremonini Group', sector: 'food' },
  { domain: 'newlat.com', name: 'Newlat Food', sector: 'food' },
  { domain: 'ferrarelle.it', name: 'Ferrarelle', sector: 'beverage' },
  { domain: 'sanpellegrino.com', name: 'Sanpellegrino', sector: 'beverage' },
  { domain: 'san-benedetto.it', name: 'Acqua San Benedetto', sector: 'beverage' },
  { domain: 'peroni.com', name: 'Birra Peroni', sector: 'beverage' },
  { domain: 'martini.com', name: 'Martini & Rossi', sector: 'beverage' },
  { domain: 'mutti-parma.com', name: 'Mutti', sector: 'food' },
  { domain: 'divella.it', name: 'Divella', sector: 'food' },
  { domain: 'rummo.com', name: 'Rummo', sector: 'food' },
  { domain: 'stellaartois.it', name: 'AB InBev Italia', sector: 'beverage' },
  { domain: 'auricchio.it', name: 'Auricchio', sector: 'food' },
  { domain: 'galbani.it', name: 'Galbani', sector: 'food' },
  { domain: 'eataly.net', name: 'Eataly', sector: 'retail' },

  // Telecom / tech / media
  { domain: 'tim.it', name: 'TIM (Telecom Italia)', sector: 'telecom' },
  { domain: 'vodafone.it', name: 'Vodafone Italia', sector: 'telecom' },
  { domain: 'wind3.it', name: 'WindTre', sector: 'telecom' },
  { domain: 'iliad.it', name: 'Iliad Italia', sector: 'telecom' },
  { domain: 'fastweb.it', name: 'Fastweb', sector: 'telecom' },
  { domain: 'openfiber.it', name: 'Open Fiber', sector: 'telecom' },
  { domain: 'rai.it', name: 'RAI', sector: 'media' },
  { domain: 'mediaset.it', name: 'Mediaset', sector: 'media' },
  { domain: 'skyitalia.it', name: 'Sky Italia', sector: 'media' },
  { domain: 'gedi.it', name: 'GEDI Group', sector: 'media' },
  { domain: 'rcsmediagroup.it', name: 'RCS MediaGroup', sector: 'media' },
  { domain: 'mondadori.it', name: 'Mondadori Group', sector: 'media' },
  { domain: 'bendingspoons.com', name: 'Bending Spoons', sector: 'tech' },
  { domain: 'docebo.com', name: 'Docebo', sector: 'tech' },
  { domain: 'musixmatch.com', name: 'Musixmatch', sector: 'tech' },
  { domain: 'translated.com', name: 'Translated', sector: 'tech' },
  { domain: 'datrix.ai', name: 'Datrix', sector: 'tech' },
  { domain: 'buildo.io', name: 'Buildo', sector: 'tech' },
  { domain: 'moveax.it', name: 'MoveAx', sector: 'tech' },
  { domain: 'yoox.com', name: 'YOOX Net-a-Porter', sector: 'ecommerce' },
  { domain: 'subito.it', name: 'Subito.it', sector: 'ecommerce' },
  { domain: 'cortilia.it', name: 'Cortilia', sector: 'ecommerce' },
  { domain: 'depop.com', name: 'Depop', sector: 'ecommerce' },
  { domain: 'tannico.it', name: 'Tannico', sector: 'ecommerce' },
  { domain: 'chili.com', name: 'Chili', sector: 'media' },
  { domain: 'engineering.it', name: 'Engineering Group', sector: 'tech' },
  { domain: 'almaviva.it', name: 'Almaviva', sector: 'tech' },
  { domain: 'reevo.it', name: 'Reevo', sector: 'tech' },
  { domain: 'seesib.it', name: 'Seesib', sector: 'tech' },
  { domain: 'cedacri.it', name: 'Cedacri', sector: 'tech' },
  { domain: 'sistemieautomazione.it', name: 'Sistemi e Automazione', sector: 'tech' },
  { domain: 'exprivia.it', name: 'Exprivia', sector: 'tech' },
  { domain: 'dedagroup.it', name: 'Dedagroup', sector: 'tech' },
  { domain: 'lutech.it', name: 'Lutech', sector: 'tech' },
  { domain: 'var-group.it', name: 'VAR Group', sector: 'tech' },
  { domain: 'seac.it', name: 'Seac', sector: 'tech' },
  { domain: 'teamsystem.com', name: 'TeamSystem', sector: 'tech' },
  { domain: 'zucchetti.it', name: 'Zucchetti', sector: 'tech' },
  { domain: 'datalogic.com', name: 'Datalogic', sector: 'tech' },
  { domain: 'sicurit.it', name: 'Sicurit', sector: 'tech' },
  { domain: 'sesa.it', name: 'Sesa', sector: 'tech' },

  // Pharma / healthcare
  { domain: 'menarini.com', name: 'Menarini', sector: 'pharma' },
  { domain: 'chiesi.com', name: 'Chiesi Farmaceutici', sector: 'pharma' },
  { domain: 'recordati.com', name: 'Recordati', sector: 'pharma' },
  { domain: 'zambongroup.com', name: 'Zambon Group', sector: 'pharma' },
  { domain: 'bracco.com', name: 'Bracco Imaging', sector: 'pharma' },
  { domain: 'diasorin.com', name: 'DiaSorin', sector: 'pharma' },
  { domain: 'ibsa.ch', name: 'IBSA Group', sector: 'pharma' },
  { domain: 'kedrion.com', name: 'Kedrion Biopharma', sector: 'pharma' },
  { domain: 'italfarmaco.com', name: 'Italfarmaco', sector: 'pharma' },
  { domain: 'esaote.com', name: 'Esaote', sector: 'medtech' },
  { domain: 'sorin.com', name: 'Sorin Group (LivaNova)', sector: 'medtech' },
  { domain: 'gvm.it', name: 'GVM Care & Research', sector: 'healthcare' },
  { domain: 'humanitas.it', name: 'Humanitas', sector: 'healthcare' },
  { domain: 'sangiovanni.it', name: 'Ospedale San Giovanni', sector: 'healthcare' },
  { domain: 'kos-group.com', name: 'KOS Group', sector: 'healthcare' },
  { domain: 'angelini.it', name: 'Angelini Industries', sector: 'pharma' },
  { domain: 'alfasigma.com', name: 'Alfasigma', sector: 'pharma' },
  { domain: 'sifigroup.com', name: 'SIFI', sector: 'pharma' },

  // Retail / consumer / logistics
  { domain: 'esselunga.it', name: 'Esselunga', sector: 'retail' },
  { domain: 'coop.it', name: 'Coop Italia', sector: 'retail' },
  { domain: 'conad.it', name: 'Conad', sector: 'retail' },
  { domain: 'carrefour.it', name: 'Carrefour Italia', sector: 'retail' },
  { domain: 'gruppomd.it', name: 'MD Discount', sector: 'retail' },
  { domain: 'eurospin.it', name: 'Eurospin', sector: 'retail' },
  { domain: 'lidl.it', name: 'Lidl Italia', sector: 'retail' },
  { domain: 'ikea.it', name: 'IKEA Italia', sector: 'retail' },
  { domain: 'mediaworld.it', name: 'MediaWorld', sector: 'retail' },
  { domain: 'unieuro.it', name: 'Unieuro', sector: 'retail' },
  { domain: 'brt.it', name: 'BRT (Bartolini)', sector: 'logistics' },
  { domain: 'gls-italy.com', name: 'GLS Italy', sector: 'logistics' },
  { domain: 'sda.it', name: 'SDA Express Courier', sector: 'logistics' },
  { domain: 'ferrovie.it', name: 'Ferrovie dello Stato', sector: 'transport' },
  { domain: 'italo.it', name: 'Italo (NTV)', sector: 'transport' },
  { domain: 'autostrade.it', name: 'Autostrade per l’Italia', sector: 'transport' },
  { domain: 'aeroportiroma.it', name: 'Aeroporti di Roma', sector: 'transport' },
  { domain: 'sea-aeroportimilano.it', name: 'SEA Aeroporti Milano', sector: 'transport' },
  { domain: 'ita-airways.com', name: 'ITA Airways', sector: 'transport' },
  { domain: 'msccrociere.it', name: 'MSC Crociere', sector: 'transport' },
  { domain: 'grimaldi-lines.com', name: 'Grimaldi Group', sector: 'transport' },
];
