-- Seed all major Italian universities (skip duplicates by name)
INSERT INTO "University" ("id", "name", "city", "country", "isActive")
SELECT gen_random_uuid(), v.name, v.city, 'Italia', true
FROM (VALUES
  ('Politecnico di Bari', 'Bari'),
  ('Università degli Studi di Bari Aldo Moro', 'Bari'),
  ('Università degli Studi di Bergamo', 'Bergamo'),
  ('Università degli Studi di Brescia', 'Brescia'),
  ('Università degli Studi della Calabria', 'Cosenza'),
  ('Università degli Studi di Cagliari', 'Cagliari'),
  ('Università degli Studi di Camerino', 'Camerino'),
  ('Università degli Studi di Cassino e del Lazio Meridionale', 'Cassino'),
  ('Università degli Studi di Catania', 'Catania'),
  ('Università degli Studi Magna Graecia di Catanzaro', 'Catanzaro'),
  ('Università degli Studi G. d''Annunzio Chieti-Pescara', 'Chieti'),
  ('Università degli Studi di Ferrara', 'Ferrara'),
  ('Università degli Studi di Foggia', 'Foggia'),
  ('Università degli Studi di Genova', 'Genova'),
  ('Università degli Studi dell''Insubria', 'Varese'),
  ('Università degli Studi dell''Aquila', 'L''Aquila'),
  ('Università del Salento', 'Lecce'),
  ('Università degli Studi di Macerata', 'Macerata'),
  ('Università degli Studi di Messina', 'Messina'),
  ('Università degli Studi di Milano', 'Milano'),
  ('Università degli Studi di Milano-Bicocca', 'Milano'),
  ('Università degli Studi di Modena e Reggio Emilia', 'Modena'),
  ('Università degli Studi del Molise', 'Campobasso'),
  ('Università degli Studi di Napoli L''Orientale', 'Napoli'),
  ('Università degli Studi di Napoli Parthenope', 'Napoli'),
  ('Università degli Studi della Campania Luigi Vanvitelli', 'Caserta'),
  ('Università degli Studi di Palermo', 'Palermo'),
  ('Università degli Studi di Parma', 'Parma'),
  ('Università degli Studi di Pavia', 'Pavia'),
  ('Università degli Studi di Perugia', 'Perugia'),
  ('Università per Stranieri di Perugia', 'Perugia'),
  ('Università degli Studi del Piemonte Orientale', 'Vercelli'),
  ('Scuola Normale Superiore di Pisa', 'Pisa'),
  ('Scuola Superiore Sant''Anna', 'Pisa'),
  ('Università Politecnica delle Marche', 'Ancona'),
  ('Università degli Studi Mediterranea di Reggio Calabria', 'Reggio Calabria'),
  ('Università degli Studi di Roma Tor Vergata', 'Roma'),
  ('Università degli Studi Roma Tre', 'Roma'),
  ('Università degli Studi di Roma Foro Italico', 'Roma'),
  ('Università degli Studi di Salerno', 'Salerno'),
  ('Università degli Studi del Sannio', 'Benevento'),
  ('Università degli Studi di Sassari', 'Sassari'),
  ('Università degli Studi di Siena', 'Siena'),
  ('Università per Stranieri di Siena', 'Siena'),
  ('Università degli Studi di Teramo', 'Teramo'),
  ('Università degli Studi di Trento', 'Trento'),
  ('Università degli Studi di Trieste', 'Trieste'),
  ('Università degli Studi della Tuscia', 'Viterbo'),
  ('Università degli Studi di Udine', 'Udine'),
  ('Università degli Studi di Urbino Carlo Bo', 'Urbino'),
  ('Università degli Studi di Verona', 'Verona'),
  ('IUAV - Università di Venezia', 'Venezia'),
  -- Private
  ('Università Bocconi', 'Milano'),
  ('Università Cattolica del Sacro Cuore', 'Milano'),
  ('Università Vita-Salute San Raffaele', 'Milano'),
  ('Università IULM', 'Milano'),
  ('Humanitas University', 'Milano'),
  ('LUISS Guido Carli', 'Roma'),
  ('Università Campus Bio-Medico di Roma', 'Roma'),
  ('Università Europea di Roma', 'Roma'),
  ('LUMSA', 'Roma'),
  ('Link Campus University', 'Roma'),
  ('Università LUM Giuseppe Degennaro', 'Bari'),
  ('Università Suor Orsola Benincasa', 'Napoli'),
  ('Università Carlo Cattaneo - LIUC', 'Castellanza'),
  ('Libera Università di Bolzano', 'Bolzano'),
  ('Università Kore di Enna', 'Enna'),
  -- Online
  ('Università Telematica e-Campus', 'Novedrate'),
  ('Università Telematica Pegaso', 'Napoli'),
  ('Università Telematica Mercatorum', 'Roma'),
  ('Università Telematica Niccolò Cusano', 'Roma'),
  ('Università Telematica San Raffaele Roma', 'Roma'),
  ('Università Telematica Giustino Fortunato', 'Benevento'),
  ('Università Telematica Internazionale UniNettuno', 'Roma'),
  ('Università Telematica Leonardo da Vinci', 'Chieti'),
  -- Art & Design
  ('IED - Istituto Europeo di Design', 'Milano'),
  ('NABA - Nuova Accademia di Belle Arti', 'Milano'),
  ('Accademia di Belle Arti di Firenze', 'Firenze'),
  ('Accademia di Belle Arti di Roma', 'Roma'),
  ('Domus Academy', 'Milano'),
  ('Istituto Marangoni', 'Milano'),
  ('SAE Institute', 'Milano')
) AS v(name, city)
WHERE NOT EXISTS (
  SELECT 1 FROM "University" u WHERE u."name" = v.name
);
