'use client';

import React, { createContext, useContext, useState } from 'react';

export type Language = 'Italiano' | 'Inglese' | 'Cinese' | 'Spagnolo';

export const LANGUAGE_DISPLAY_NAMES: Record<Language, string> = {
  Italiano: 'Italiano',
  Inglese: 'English',
  Cinese: '中文',
  Spagnolo: 'Español',
};

export const SKILL_KEYS = [
  'computer_science', 'data_science', 'machine_learning', 'web_development',
  'mobile_development', 'cybersecurity', 'cloud_computing', 'devops',
  'ui_ux_design', 'graphic_design', 'marketing', 'communication',
  'economics', 'finance', 'management', 'entrepreneurship',
  'engineering', 'mathematics', 'physics', 'chemistry',
  'biology', 'medicine', 'law', 'political_science',
  'languages', 'literature', 'philosophy', 'psychology',
  'sociology', 'architecture', 'design', 'music',
] as const;

export type SkillKey = typeof SKILL_KEYS[number];

type Translations = typeof it;

const it = {
  // Navigation
  nav: {
    uni: 'Uni',
    home: 'Home',
    network: 'Network',
    profile: 'Profilo',
  },
  // Home page
  home: {
    forYou: 'Per te',
    explore: 'Esplora',
    searchPlaceholder: 'Cerca opportunità…',
    filters: 'Filtri',
    reset: 'Reset',
    noOpportunities: 'Nessuna opportunità trovata',
    publishedDaysAgo: 'Pubblicato 3 giorni fa',
    goToOpportunity: "Vai all\u2019opportunit\u00e0",
    linkUnavailable: 'Link non disponibile',
    applyFilters: 'Applica filtri',
    filterType: 'Tipo',
    filterMode: 'Modalità',
    filterLevel: 'Livello',
    filterRemote: 'Remoto',
    filterInPerson: 'In presenza',
    filterHybrid: 'Ibrido',
    filterJunior: 'Junior',
    filterSenior: 'Senior',
    filterFullTime: 'Full-time',
    filterPartTime: 'Part-time',
    filterWorkshop: 'Workshop',
    filterInternship: 'Internship',
    filterEducation: 'Education',
  },
  // Notifications
  notifications: {
    title: 'Notifiche',
    today: 'Oggi',
    yesterday: 'Ieri',
    earlier: 'Precedenti',
    empty: 'Nessuna notifica',
  },
  // Universities
  uni: {
    title: 'Università',
    notFound: 'Università non trovata',
    whyRecommended: 'Perché è consigliata per te',
    recommendedDesc: 'In base al tuo profilo e ai tuoi interessi, questa università offre opportunità in linea con il tuo percorso.',
    statAlumni: 'Alumni',
    statRating: 'Rating',
    statOpportunities: 'Opportunità',
    statActiveStudents: 'Studenti attivi',
    availableCourses: 'Corsi disponibili',
    visitSite: 'Visita il sito ufficiale',
    opportunities: 'opportunità',
    courseTriennale: 'Triennale',
    courseMagistrale: 'Magistrale',
    courseCicloUnico: 'Ciclo Unico',
  },
  // Profile
  profile: {
    title: 'Profilo',
    saved: 'Salvati',
    savedUni: 'Università',
    savedOpp: 'Opportunità',
    settings: 'Impostazioni',
    preferences: 'Preferenze',
    notifications: 'Notifiche',
    darkMode: 'Modalità scura',
    language: 'Lingua',
    security: 'Sicurezza',
    privacy: 'Privacy',
    securityPrivacy: 'Sicurezza e Privacy',
    helpSupport: 'Aiuto & Supporto',
    info: 'Info',
    logout: "Esci dall\u2019account",
    editProfile: 'Modifica Profilo',
    name: 'Nome',
    bio: 'Bio',
    course: 'Corso di studi',
    year: 'Anno',
    skills: 'Competenze',
    save: 'Salva',
    saving: 'Salvataggio...',
    cancel: 'Annulla',
    done: 'Fatto',
    add: 'Aggiungi',
    addSkills: 'Aggiungi competenze',
    tapToChangePhoto: 'Tocca per cambiare foto',
    bioPlaceholder: 'Raccontaci di te...',
    coursePlaceholder: 'es. Ingegneria Informatica',
    yearPlaceholder: 'es. 3',
    noSavedOpportunities: 'Nessuna opportunità salvata ancora',
    noSavedUniversities: 'Nessuna università salvata ancora',
    exploreOpportunities: 'Esplora opportunità',
    exploreUniversities: 'Esplora università',
    searchPathmates: 'Cerca pathmates...',
    noResults: 'Nessun risultato trovato',
    noPathmates: 'Non hai ancora pathmates',
    suggestedPathmates: 'Pathmates consigliati',
    yearSuffix: '° anno',
    universityHidden: 'Università nascosta',
    deletingAccount: 'Eliminando...',
    deleteIrreversibleMsg: 'Questa azione è irreversibile. Tutti i tuoi dati verranno eliminati definitivamente.',
  },
  // Privacy sheet
  privacy: {
    title: 'Privacy',
    profileVisibility: 'Visibilità profilo',
    whoCanSeeProfile: 'Chi può vedere il tuo profilo',
    whoCanSeeSkills: 'Chi può vedere le tue competenze',
    whoCanSeeUniversity: 'Chi può vedere la tua università',
    activity: 'Attività',
    whoCanSeeSavedOpps: 'Chi può vedere le tue opportunità salvate',
    whoCanSeePathmates: 'Chi può vedere i tuoi pathmates',
    whoCanMessage: 'Chi può inviarti messaggi',
    dataPersonalization: 'Dati e personalizzazione',
    allowRecommendations: 'Consenti raccomandazioni personalizzate',
    improveSuggestions: 'Migliora i suggerimenti per te',
    shareAnonymousData: "Condividi dati anonimi per migliorare l\u2019app",
    noPersonalData: 'Nessun dato personale condiviso',
    downloadData: 'Scarica i tuoi dati',
    deleteAccount: 'Elimina account',
    everyone: 'Tutti',
    nobody: 'Nessuno',
  },
  // Security sheet
  security: {
    title: 'Sicurezza',
    changePassword: 'Cambia password',
    twoFactor: 'Autenticazione a due fattori',
    activeSessions: 'Sessioni attive',
    manageDevices: 'Gestisci i dispositivi connessi',
    disconnectAll: 'Disconnetti tutti i dispositivi',
    // Change password modal
    changePasswordTitle: 'Cambia password',
    currentPassword: 'Password attuale',
    newPassword: 'Nuova password',
    confirmPassword: 'Conferma password',
    passwordPlaceholder: 'Inserisci la password',
    newPasswordPlaceholder: 'Almeno 6 caratteri',
    confirmPasswordPlaceholder: 'Ripeti la nuova password',
    forgotPassword: 'Password dimenticata?',
    passwordMismatch: 'Le password non coincidono',
    passwordTooShort: 'La password deve avere almeno 6 caratteri',
    updatePassword: 'Aggiorna password',
    // Forgot password modal
    forgotPasswordTitle: 'Password dimenticata',
    forgotPasswordDesc: 'Inserisci la tua email. Ti invieremo un codice di verifica.',
    emailLabel: 'Email',
    emailPlaceholder: 'La tua email',
    sendCode: 'Invia codice',
    codeSentDesc: 'Abbiamo inviato un codice a {email}. Controllate anche lo spam.',
    verificationCode: 'Codice di verifica',
    codePlaceholder: '123456',
    resetPassword: 'Reimposta password',
    backToLogin: 'Torna al cambio password',
    passwordUpdated: 'Password aggiornata con successo!',
    codeResent: 'Nuovo codice inviato',
    resendCode: 'Invia nuovo codice',
  },
  // Help sheet
  help: {
    title: 'Aiuto & Supporto',
    helpCenter: 'Centro assistenza',
    browseFaq: 'Sfoglia le domande frequenti',
    contactUs: 'Contattaci',
    writeForHelp: 'Scrivici per assistenza',
    reportProblem: 'Segnala un problema',
    termsOfService: 'Termini di servizio',
    privacyPolicy: 'Informativa sulla privacy',
  },
  // Info sheet
  info: {
    title: 'Info',
    appVersion: 'Versione app',
    whatsNew: 'Novità',
    discoverFeatures: 'Scopri le ultime funzionalità',
    openSourceLicenses: 'Licenze open source',
    followSocial: 'Seguici sui social',
  },
  // Networking page
  networking: {
    messages: 'Messaggi',
    explore: 'Esplora',
    noMessages: 'Nessun messaggio ancora',
    connectExplore: 'Connettiti con altri studenti nella sezione Esplora!',
    writeMessage: 'Scrivi un messaggio...',
    shareWithCommunity: 'Condividi qualcosa con la community...',
    addPhoto: 'Aggiungi foto',
    publish: 'Pubblica',
    noComments: 'Nessun commento ancora',
    writeComment: 'Scrivi un commento...',
    group: 'gruppo',
    createGroup: 'Crea gruppo',
    noMessagePreview: 'Nessun messaggio',
    conversationsSingular: 'conversazione',
    conversationsPlural: 'conversazioni',
  },
  // User profile (other user)
  userProfile: {
    notFound: 'Profilo non trovato',
    sendMessage: 'Invia messaggio',
    connected: 'Connesso',
    requestSent: 'Richiesta inviata',
    connect: 'Connetti',
    bio: 'Bio',
    skills: 'Competenze',
  },
  // Common
  common: {
    loading: 'Caricamento...',
    cancel: 'Annulla',
    confirm: 'Conferma',
    typeToConfirm: 'Scrivi "{input}" per confermare',
    error: 'Errore',
  },
  // Group modals
  group: {
    newGroup: 'Nuovo Gruppo',
    newChat: 'Nuova chat',
    groupName: 'Nome del gruppo',
    description: 'Descrizione (opzionale)',
    selectedCount: '{count} selezionati',
    minTwo: '(minimo 2)',
    searchFriends: 'Cerca amici...',
    searchUsers: 'Cerca utenti...',
    noFriendsFound: 'Nessun amico trovato',
    noUsersFound: 'Nessun utente trovato',
    noUsersAvailable: 'Nessun utente disponibile',
    startChat: 'Avvia chat',
    autoNameWith: 'Gruppo con',
    autoNameOthers: 'e altri',
    unsavedChanges: 'Vuoi davvero uscire? Le modifiche non salvate andranno perse.',
    errorLoadFriends: 'Errore nel caricamento degli amici',
    errorLoadImage: "Errore nel caricamento dell'immagine",
    errorCreate: 'Impossibile creare il gruppo, riprova',
    options: 'Opzioni gruppo',
    memberCount: 'membri',
    createdByPrefix: 'Creato da',
    onDate: 'il',
    editPhoto: 'Modifica foto gruppo',
    updatingPhoto: 'Aggiornamento...',
    addMembers: 'Aggiungi membri',
    viewMembers: 'Vedi membri',
    dangerZone: 'Zona pericolosa',
    leaveGroup: 'Esci dal gruppo',
    deleteGroup: 'Elimina gruppo',
    photoUpdated: 'Foto del gruppo aggiornata',
    errorUpdatePhoto: "Errore nell'aggiornamento della foto",
    leftGroup: 'Hai lasciato il gruppo',
    groupDeleted: 'Gruppo eliminato',
    membersAdded: 'Membri aggiunti al gruppo',
    memberRemoved: 'Membro rimosso dal gruppo',
    leaveConfirmTitle: 'Esci dal gruppo',
    leaveConfirmMsgPrefix: 'Vuoi davvero uscire dal gruppo',
    leaveConfirmBtn: 'Esci',
    deleteConfirmMsg: 'Questa azione è irreversibile. Tutti i messaggi verranno eliminati e i membri verranno notificati.',
    deleteConfirmBtn: 'Elimina',
    deleteConfirmInput: 'ELIMINA',
    allFriendsInGroup: 'Tutti i tuoi amici sono già nel gruppo',
    alreadyInGroup: 'Già nel gruppo',
    creator: 'Creatore',
    you: 'Tu',
    remove: 'Rimuovi',
    removeConfirmTitle: 'Rimuovi membro',
    removeConfirmMsgPrefix: 'Vuoi rimuovere',
    removeConfirmMsgSuffix: 'dal gruppo?',
    removeConfirmBtn: 'Rimuovi',
    newChatDesc: 'Inizia una conversazione con qualcuno',
    createGroupDesc: 'Crea un gruppo con i tuoi amici',
  },
  skillLabels: {
    computer_science: 'Informatica',
    data_science: 'Data Science',
    machine_learning: 'Machine Learning',
    web_development: 'Web Development',
    mobile_development: 'Mobile Development',
    cybersecurity: 'Cybersecurity',
    cloud_computing: 'Cloud Computing',
    devops: 'DevOps',
    ui_ux_design: 'UI/UX Design',
    graphic_design: 'Graphic Design',
    marketing: 'Marketing',
    communication: 'Comunicazione',
    economics: 'Economia',
    finance: 'Finanza',
    management: 'Management',
    entrepreneurship: 'Imprenditoria',
    engineering: 'Ingegneria',
    mathematics: 'Matematica',
    physics: 'Fisica',
    chemistry: 'Chimica',
    biology: 'Biologia',
    medicine: 'Medicina',
    law: 'Giurisprudenza',
    political_science: 'Scienze Politiche',
    languages: 'Lingue',
    literature: 'Letteratura',
    philosophy: 'Filosofia',
    psychology: 'Psicologia',
    sociology: 'Sociologia',
    architecture: 'Architettura',
    design: 'Design',
    music: 'Musica',
  },
  opportunitiesContent: {
    '1': {
      description: "Siamo alla ricerca di uno studente appassionato di sviluppo web per unirsi al nostro team di ingegneria. Lavorerai su progetti reali con impatto diretto sul prodotto, collaborando con ingegneri senior su feature front-end e back-end. Richiediamo conoscenza di JavaScript/TypeScript e dei fondamentali del web. È previsto un compenso mensile e la possibilità di assunzione a tempo indeterminato al termine del percorso.",
      location: "Milano, IT • Remoto",
      about: "TechNova Solutions è una startup fintech in rapida crescita con sede a Milano. Lavoriamo per rivoluzionare il settore dei pagamenti digitali con soluzioni basate su intelligenza artificiale e blockchain. Il nostro team è composto da oltre 50 ingegneri provenienti da tutta Europa, uniti dalla passione per la tecnologia e dall'impatto sociale del nostro lavoro.",
    },
    '2': {
      description: "Unisciti a noi per una settimana intensiva di Design Thinking e prototyping applicato al mondo reale. Il programma include sessioni mattutine di teoria, pomeriggi di hands-on workshop con mentori del settore e una presentazione finale davanti a un panel di aziende partner. Partecipazione gratuita con borsa di studio disponibile.",
      location: "Milano, IT • Ibrido",
      about: "Creative Hub Milan è un centro di innovazione dedicato alla cultura del design e alla creatività applicata. Ogni anno formiamo centinaia di giovani designer attraverso workshop intensivi e programmi di mentorship con professionisti del settore. Collaboriamo con oltre 80 aziende italiane e internazionali.",
    },
    '3': {
      description: "Analisi di dataset complessi per l'ottimizzazione dei processi di credito e gestione del rischio. Il ruolo prevede elaborazione dati in Python, creazione di dashboard in Tableau e reporting settimanale ai manager. Sono richieste esperienza pregressa in analisi dati e conoscenza di SQL. Contratto a tempo determinato con possibilità di rinnovo.",
      location: "Roma, IT • In presenza",
      about: "Fintech Alpha è una società fintech specializzata nella gestione del rischio di credito. Utilizziamo modelli statistici avanzati e machine learning per ottimizzare i processi di valutazione del credito, operando con oltre 200 partner bancari in tutta Italia. Fondata nel 2018, contiamo oggi più di 120 dipendenti.",
    },
    '4': {
      description: "Un percorso formativo avanzato che esplora le implicazioni etiche dell'intelligenza artificiale in contesti aziendali, legali e sociali. Il corso è erogato in modalità ibrida con 6 moduli da 4 settimane ciascuno, inclusi casi studio con aziende leader del settore tech. Titolo riconosciuto a livello europeo.",
      location: "Milano, IT • Part-time",
      about: "Il Politecnico di Milano, una delle migliori università tecniche d'Europa, propone questo programma d'eccellenza dedicato alle sfide etiche dell'intelligenza artificiale. Il programma è riconosciuto a livello europeo e offre accesso a una rete di alumni in oltre 30 paesi, con placement rate del 94%.",
    },
  },
};

const en: Translations = {
  nav: {
    uni: 'Uni',
    home: 'Home',
    network: 'Network',
    profile: 'Profile',
  },
  home: {
    forYou: 'For you',
    explore: 'Explore',
    searchPlaceholder: 'Search opportunities…',
    filters: 'Filters',
    reset: 'Reset',
    noOpportunities: 'No opportunities found',
    publishedDaysAgo: 'Published 3 days ago',
    goToOpportunity: 'Go to opportunity',
    linkUnavailable: 'Link unavailable',
    applyFilters: 'Apply filters',
    filterType: 'Type',
    filterMode: 'Mode',
    filterLevel: 'Level',
    filterRemote: 'Remote',
    filterInPerson: 'In-person',
    filterHybrid: 'Hybrid',
    filterJunior: 'Junior',
    filterSenior: 'Senior',
    filterFullTime: 'Full-time',
    filterPartTime: 'Part-time',
    filterWorkshop: 'Workshop',
    filterInternship: 'Internship',
    filterEducation: 'Education',
  },
  notifications: {
    title: 'Notifications',
    today: 'Today',
    yesterday: 'Yesterday',
    earlier: 'Earlier',
    empty: 'No notifications',
  },
  uni: {
    title: 'Universities',
    notFound: 'University not found',
    whyRecommended: 'Why it\'s recommended for you',
    recommendedDesc: 'Based on your profile and interests, this university offers opportunities aligned with your path.',
    statAlumni: 'Alumni',
    statRating: 'Rating',
    statOpportunities: 'Opportunities',
    statActiveStudents: 'Active Students',
    availableCourses: 'Available Courses',
    visitSite: 'Visit official website',
    opportunities: 'opportunities',
    courseTriennale: 'Bachelor\'s',
    courseMagistrale: 'Master\'s',
    courseCicloUnico: 'Single Cycle',
  },
  profile: {
    title: 'Profile',
    saved: 'Saved',
    savedUni: 'Universities',
    savedOpp: 'Opportunities',
    settings: 'Settings',
    preferences: 'Preferences',
    notifications: 'Notifications',
    darkMode: 'Dark Mode',
    language: 'Language',
    security: 'Security',
    privacy: 'Privacy',
    securityPrivacy: 'Security & Privacy',
    helpSupport: 'Help & Support',
    info: 'Info',
    logout: 'Log out',
    editProfile: 'Edit Profile',
    name: 'Name',
    bio: 'Bio',
    course: 'Course of study',
    year: 'Year',
    skills: 'Skills',
    save: 'Save',
    saving: 'Saving...',
    cancel: 'Cancel',
    done: 'Done',
    add: 'Add',
    addSkills: 'Add skills',
    tapToChangePhoto: 'Tap to change photo',
    bioPlaceholder: 'Tell us about you...',
    coursePlaceholder: 'e.g. Computer Science',
    yearPlaceholder: 'e.g. 3',
    noSavedOpportunities: 'No saved opportunities yet',
    noSavedUniversities: 'No saved universities yet',
    exploreOpportunities: 'Explore opportunities',
    exploreUniversities: 'Explore universities',
    searchPathmates: 'Search Pathmates...',
    noResults: 'No results found',
    noPathmates: 'No Pathmates yet',
    suggestedPathmates: 'Suggested Pathmates',
    yearSuffix: 'st year',
    universityHidden: 'University hidden',
    deletingAccount: 'Deleting...',
    deleteIrreversibleMsg: 'This action is irreversible. All your data will be permanently deleted.',
  },
  privacy: {
    title: 'Privacy',
    profileVisibility: 'Profile Visibility',
    whoCanSeeProfile: 'Who can see your profile',
    whoCanSeeSkills: 'Who can see your skills',
    whoCanSeeUniversity: 'Who can see your university',
    activity: 'Activity',
    whoCanSeeSavedOpps: 'Who can see your saved opportunities',
    whoCanSeePathmates: 'Who can see your Pathmates',
    whoCanMessage: 'Who can message you',
    dataPersonalization: 'Data & Personalization',
    allowRecommendations: 'Allow personalized recommendations',
    improveSuggestions: 'Improves suggestions for you',
    shareAnonymousData: 'Share anonymous data to improve the app',
    noPersonalData: 'No personal data shared',
    downloadData: 'Download your data',
    deleteAccount: 'Delete account',
    everyone: 'Everyone',
    nobody: 'Nobody',
  },
  security: {
    title: 'Security',
    changePassword: 'Change password',
    twoFactor: 'Two-factor authentication',
    activeSessions: 'Active sessions',
    manageDevices: 'Manage connected devices',
    disconnectAll: 'Disconnect all devices',
    changePasswordTitle: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    passwordPlaceholder: 'Enter password',
    newPasswordPlaceholder: 'At least 6 characters',
    confirmPasswordPlaceholder: 'Repeat new password',
    forgotPassword: 'Forgot password?',
    passwordMismatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    updatePassword: 'Update password',
    forgotPasswordTitle: 'Forgot password',
    forgotPasswordDesc: 'Enter your email. We will send you a verification code.',
    emailLabel: 'Email',
    emailPlaceholder: 'Your email',
    sendCode: 'Send code',
    codeSentDesc: 'We sent a code to {email}. Check your spam folder too.',
    verificationCode: 'Verification code',
    codePlaceholder: '123456',
    resetPassword: 'Reset password',
    backToLogin: 'Back to change password',
    passwordUpdated: 'Password updated successfully!',
    codeResent: 'New code sent',
    resendCode: 'Resend code',
  },
  help: {
    title: 'Help & Support',
    helpCenter: 'Help Center',
    browseFaq: 'Browse frequently asked questions',
    contactUs: 'Contact Us',
    writeForHelp: 'Write to us for assistance',
    reportProblem: 'Report a problem',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
  },
  info: {
    title: 'Info',
    appVersion: 'App version',
    whatsNew: "What's New",
    discoverFeatures: 'Discover the latest features',
    openSourceLicenses: 'Open source licenses',
    followSocial: 'Follow us on social',
  },
  networking: {
    messages: 'Messages',
    explore: 'Explore',
    noMessages: 'No messages yet',
    connectExplore: 'Connect with other students in the Explore section!',
    writeMessage: 'Write a message...',
    shareWithCommunity: 'Share something with the community...',
    addPhoto: 'Add photo',
    publish: 'Publish',
    noComments: 'No comments yet',
    writeComment: 'Write a comment...',
    group: 'group',
    createGroup: 'Create group',
    noMessagePreview: 'No message',
    conversationsSingular: 'conversation',
    conversationsPlural: 'conversations',
  },
  userProfile: {
    notFound: 'Profile not found',
    sendMessage: 'Send message',
    connected: 'Connected',
    requestSent: 'Request sent',
    connect: 'Connect',
    bio: 'Bio',
    skills: 'Skills',
  },
  common: {
    loading: 'Loading...',
    cancel: 'Cancel',
    confirm: 'Confirm',
    typeToConfirm: 'Type "{input}" to confirm',
    error: 'Error',
  },
  group: {
    newGroup: 'New Group',
    newChat: 'New chat',
    groupName: 'Group name',
    description: 'Description (optional)',
    selectedCount: '{count} selected',
    minTwo: '(minimum 2)',
    searchFriends: 'Search friends...',
    searchUsers: 'Search users...',
    noFriendsFound: 'No friends found',
    noUsersFound: 'No user found',
    noUsersAvailable: 'No users available',
    startChat: 'Start chat',
    autoNameWith: 'Group with',
    autoNameOthers: 'and others',
    unsavedChanges: 'Are you sure you want to leave? Unsaved changes will be lost.',
    errorLoadFriends: 'Error loading friends',
    errorLoadImage: 'Error loading image',
    errorCreate: 'Could not create group, please try again',
    options: 'Group options',
    memberCount: 'members',
    createdByPrefix: 'Created by',
    onDate: 'on',
    editPhoto: 'Edit group photo',
    updatingPhoto: 'Updating...',
    addMembers: 'Add members',
    viewMembers: 'View members',
    dangerZone: 'Danger zone',
    leaveGroup: 'Leave group',
    deleteGroup: 'Delete group',
    photoUpdated: 'Group photo updated',
    errorUpdatePhoto: 'Error updating photo',
    leftGroup: 'You left the group',
    groupDeleted: 'Group deleted',
    membersAdded: 'Members added to group',
    memberRemoved: 'Member removed from group',
    leaveConfirmTitle: 'Leave group',
    leaveConfirmMsgPrefix: 'Are you sure you want to leave the group',
    leaveConfirmBtn: 'Leave',
    deleteConfirmMsg: 'This action is irreversible. All messages will be deleted and members will be notified.',
    deleteConfirmBtn: 'Delete',
    deleteConfirmInput: 'ELIMINA',
    allFriendsInGroup: 'All your friends are already in the group',
    alreadyInGroup: 'Already in group',
    creator: 'Creator',
    you: 'You',
    remove: 'Remove',
    removeConfirmTitle: 'Remove member',
    removeConfirmMsgPrefix: 'Are you sure you want to remove',
    removeConfirmMsgSuffix: 'from the group?',
    removeConfirmBtn: 'Remove',
    newChatDesc: 'Start a conversation with someone',
    createGroupDesc: 'Create a group with your friends',
  },
  skillLabels: {
    computer_science: 'Computer Science',
    data_science: 'Data Science',
    machine_learning: 'Machine Learning',
    web_development: 'Web Development',
    mobile_development: 'Mobile Development',
    cybersecurity: 'Cybersecurity',
    cloud_computing: 'Cloud Computing',
    devops: 'DevOps',
    ui_ux_design: 'UI/UX Design',
    graphic_design: 'Graphic Design',
    marketing: 'Marketing',
    communication: 'Communication',
    economics: 'Economics',
    finance: 'Finance',
    management: 'Management',
    entrepreneurship: 'Entrepreneurship',
    engineering: 'Engineering',
    mathematics: 'Mathematics',
    physics: 'Physics',
    chemistry: 'Chemistry',
    biology: 'Biology',
    medicine: 'Medicine',
    law: 'Law',
    political_science: 'Political Science',
    languages: 'Languages',
    literature: 'Literature',
    philosophy: 'Philosophy',
    psychology: 'Psychology',
    sociology: 'Sociology',
    architecture: 'Architecture',
    design: 'Design',
    music: 'Music',
  },
  opportunitiesContent: {
    '1': {
      description: "We are looking for a passionate web development student to join our engineering team. You will work on real projects with direct product impact, collaborating with senior engineers on front-end and back-end features. We require knowledge of JavaScript/TypeScript and web fundamentals. Monthly compensation provided with potential full-time employment upon completion.",
      location: "Milan, IT • Remote",
      about: "TechNova Solutions is a fast-growing fintech startup based in Milan. We work to revolutionize the digital payments sector with solutions based on artificial intelligence and blockchain. Our team consists of over 50 engineers from across Europe, united by a passion for technology and the social impact of our work.",
    },
    '2': {
      description: "Join us for an intensive week of Design Thinking and real-world prototyping. The program includes morning theory sessions, hands-on workshop afternoons with industry mentors, and a final presentation before a panel of partner companies. Free participation with scholarship available.",
      location: "Milan, IT • Hybrid",
      about: "Creative Hub Milan is an innovation center dedicated to design culture and applied creativity. Each year we train hundreds of young designers through intensive workshops and mentorship programs with industry professionals. We collaborate with over 80 Italian and international companies.",
    },
    '3': {
      description: "Analysis of complex datasets to optimize credit processes and risk management. The role involves data processing in Python, creating dashboards in Tableau, and weekly reporting to managers. Previous experience in data analysis and knowledge of SQL required. Fixed-term contract with possibility of renewal.",
      location: "Rome, IT • In-person",
      about: "Fintech Alpha is a fintech company specializing in credit risk management. We use advanced statistical models and machine learning to optimize credit assessment processes, working with over 200 banking partners throughout Italy. Founded in 2018, we now have more than 120 employees.",
    },
    '4': {
      description: "An advanced training program exploring the ethical implications of artificial intelligence in corporate, legal, and social contexts. The course is delivered in hybrid mode with 6 modules of 4 weeks each, including case studies with leading tech companies. European-recognized qualification.",
      location: "Milan, IT • Part-time",
      about: "Politecnico di Milano, one of Europe's best technical universities, presents this excellence program dedicated to the ethical challenges of artificial intelligence. The program is recognized at the European level and provides access to an alumni network in over 30 countries, with a 94% placement rate.",
    },
  },
};

const zh: Translations = {
  nav: {
    uni: '大学',
    home: '首页',
    network: '社交',
    profile: '我的',
  },
  home: {
    forYou: '为你',
    explore: '探索',
    searchPlaceholder: '搜索机会…',
    filters: '筛选',
    reset: '重置',
    noOpportunities: '未找到机会',
    publishedDaysAgo: '3天前发布',
    goToOpportunity: '前往机会',
    linkUnavailable: '链接不可用',
    applyFilters: '应用筛选',
    filterType: '类型',
    filterMode: '模式',
    filterLevel: '级别',
    filterRemote: '远程',
    filterInPerson: '线下',
    filterHybrid: '混合',
    filterJunior: '初级',
    filterSenior: '高级',
    filterFullTime: '全职',
    filterPartTime: '兼职',
    filterWorkshop: '工作坊',
    filterInternship: '实习',
    filterEducation: '教育',
  },
  notifications: {
    title: '通知',
    today: '今天',
    yesterday: '昨天',
    earlier: '更早',
    empty: '暂无通知',
  },
  uni: {
    title: '大学',
    notFound: '未找到大学',
    whyRecommended: '为何推荐给你',
    recommendedDesc: '根据你的个人资料和兴趣，该大学提供与你发展路径一致的机会。',
    statAlumni: '校友',
    statRating: '评分',
    statOpportunities: '机会',
    statActiveStudents: '活跃学生',
    availableCourses: '可用课程',
    visitSite: '访问官网',
    opportunities: '机会',
    courseTriennale: '本科',
    courseMagistrale: '硕士',
    courseCicloUnico: '一贯制',
  },
  profile: {
    title: '个人资料',
    saved: '已保存',
    savedUni: '大学',
    savedOpp: '机会',
    settings: '设置',
    preferences: '偏好设置',
    notifications: '通知',
    darkMode: '深色模式',
    language: '语言',
    security: '安全',
    privacy: '隐私',
    securityPrivacy: '安全与隐私',
    helpSupport: '帮助与支持',
    info: '信息',
    logout: '退出账户',
    editProfile: '编辑资料',
    name: '姓名',
    bio: '个人简介',
    course: '学习课程',
    year: '年级',
    skills: '技能',
    save: '保存',
    saving: '保存中...',
    cancel: '取消',
    done: '完成',
    add: '添加',
    addSkills: '添加技能',
    tapToChangePhoto: '点击更改照片',
    bioPlaceholder: '告诉我们关于你...',
    coursePlaceholder: '例如: 计算机科学',
    yearPlaceholder: '例如: 3',
    noSavedOpportunities: '暂无保存的机会',
    noSavedUniversities: '暂无保存的大学',
    exploreOpportunities: '探索机会',
    exploreUniversities: '探索大学',
    searchPathmates: '搜索Pathmates...',
    noResults: '未找到结果',
    noPathmates: '暂无Pathmates',
    suggestedPathmates: '推荐的Pathmates',
    yearSuffix: '年级',
    universityHidden: '大学已隐藏',
    deletingAccount: '删除中...',
    deleteIrreversibleMsg: '此操作不可逆。您的所有数据将被永久删除。',
  },
  privacy: {
    title: '隐私',
    profileVisibility: '个人资料可见性',
    whoCanSeeProfile: '谁可以看你的资料',
    whoCanSeeSkills: '谁可以看你的技能',
    whoCanSeeUniversity: '谁可以看你的大学',
    activity: '活动',
    whoCanSeeSavedOpps: '谁可以看你保存的机会',
    whoCanSeePathmates: '谁可以看你的Pathmates',
    whoCanMessage: '谁可以给你发消息',
    dataPersonalization: '数据与个性化',
    allowRecommendations: '允许个性化推荐',
    improveSuggestions: '改善对你的建议',
    shareAnonymousData: '共享匿名数据以改进应用',
    noPersonalData: '不共享个人数据',
    downloadData: '下载你的数据',
    deleteAccount: '删除账户',
    everyone: '所有人',
    nobody: '无人',
  },
  security: {
    title: '安全',
    changePassword: '更改密码',
    twoFactor: '双因素认证',
    activeSessions: '活动会话',
    manageDevices: '管理已连接设备',
    disconnectAll: '断开所有设备',
    changePasswordTitle: '更改密码',
    currentPassword: '当前密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    passwordPlaceholder: '输入密码',
    newPasswordPlaceholder: '至少6个字符',
    confirmPasswordPlaceholder: '重复新密码',
    forgotPassword: '忘记密码？',
    passwordMismatch: '密码不一致',
    passwordTooShort: '密码必须至少6个字符',
    updatePassword: '更新密码',
    forgotPasswordTitle: '忘记密码',
    forgotPasswordDesc: '输入您的邮箱，我们将发送验证码。',
    emailLabel: '邮箱',
    emailPlaceholder: '您的邮箱',
    sendCode: '发送验证码',
    codeSentDesc: '我们已向{email}发送了验证码，请检查垃圾邮件。',
    verificationCode: '验证码',
    codePlaceholder: '123456',
    resetPassword: '重置密码',
    backToLogin: '返回更改密码',
    passwordUpdated: '密码更新成功！',
    codeResent: '新验证码已发送',
    resendCode: '重新发送验证码',
  },
  help: {
    title: '帮助与支持',
    helpCenter: '帮助中心',
    browseFaq: '浏览常见问题',
    contactUs: '联系我们',
    writeForHelp: '给我们写信寻求帮助',
    reportProblem: '举报问题',
    termsOfService: '服务条款',
    privacyPolicy: '隐私政策',
  },
  info: {
    title: '信息',
    appVersion: '应用版本',
    whatsNew: '最新动态',
    discoverFeatures: '发现最新功能',
    openSourceLicenses: '开源许可证',
    followSocial: '关注我们的社交媒体',
  },
  networking: {
    messages: '消息',
    explore: '探索',
    noMessages: '暂无消息',
    connectExplore: '在探索板块与其他学生建立联系！',
    writeMessage: '发送消息...',
    shareWithCommunity: '与社区分享一些内容...',
    addPhoto: '添加照片',
    publish: '发布',
    noComments: '暂无评论',
    writeComment: '写评论...',
    group: '群组',
    createGroup: '创建群组',
    noMessagePreview: '无消息',
    conversationsSingular: '对话',
    conversationsPlural: '对话',
  },
  userProfile: {
    notFound: '未找到用户资料',
    sendMessage: '发送消息',
    connected: '已连接',
    requestSent: '请求已发送',
    connect: '连接',
    bio: '个人简介',
    skills: '技能',
  },
  common: {
    loading: '加载中...',
    cancel: '取消',
    confirm: '确认',
    typeToConfirm: '请输入"{input}"以确认',
    error: '错误',
  },
  group: {
    newGroup: '新群组',
    newChat: '新聊天',
    groupName: '群组名称',
    description: '描述（可选）',
    selectedCount: '已选{count}人',
    minTwo: '（至少2人）',
    searchFriends: '搜索朋友...',
    searchUsers: '搜索用户...',
    noFriendsFound: '未找到朋友',
    noUsersFound: '未找到用户',
    noUsersAvailable: '没有可用用户',
    startChat: '开始聊天',
    autoNameWith: '群组与',
    autoNameOthers: '等其他人',
    unsavedChanges: '确定要离开吗？未保存的更改将丢失。',
    errorLoadFriends: '加载朋友时出错',
    errorLoadImage: '加载图片时出错',
    errorCreate: '无法创建群组，请重试',
    options: '群组选项',
    memberCount: '位成员',
    createdByPrefix: '由',
    onDate: '创建于',
    editPhoto: '编辑群组照片',
    updatingPhoto: '更新中...',
    addMembers: '添加成员',
    viewMembers: '查看成员',
    dangerZone: '危险区域',
    leaveGroup: '退出群组',
    deleteGroup: '删除群组',
    photoUpdated: '群组照片已更新',
    errorUpdatePhoto: '更新照片时出错',
    leftGroup: '你已退出群组',
    groupDeleted: '群组已删除',
    membersAdded: '成员已添加到群组',
    memberRemoved: '成员已从群组移除',
    leaveConfirmTitle: '退出群组',
    leaveConfirmMsgPrefix: '确定要退出群组',
    leaveConfirmBtn: '退出',
    deleteConfirmMsg: '此操作不可逆。所有消息将被删除，成员将收到通知。',
    deleteConfirmBtn: '删除',
    deleteConfirmInput: 'ELIMINA',
    allFriendsInGroup: '你所有的朋友都已在群组中',
    alreadyInGroup: '已在群组中',
    creator: '创建者',
    you: '你',
    remove: '移除',
    removeConfirmTitle: '移除成员',
    removeConfirmMsgPrefix: '确定要将',
    removeConfirmMsgSuffix: '从群组移除吗？',
    removeConfirmBtn: '移除',
    newChatDesc: '与某人开始对话',
    createGroupDesc: '与朋友创建群组',
  },
  skillLabels: {
    computer_science: '计算机科学',
    data_science: '数据科学',
    machine_learning: '机器学习',
    web_development: '网页开发',
    mobile_development: '移动开发',
    cybersecurity: '网络安全',
    cloud_computing: '云计算',
    devops: 'DevOps',
    ui_ux_design: 'UI/UX设计',
    graphic_design: '平面设计',
    marketing: '市场营销',
    communication: '传播与沟通',
    economics: '经济学',
    finance: '金融',
    management: '管理学',
    entrepreneurship: '创业学',
    engineering: '工程学',
    mathematics: '数学',
    physics: '物理',
    chemistry: '化学',
    biology: '生物学',
    medicine: '医学',
    law: '法学',
    political_science: '政治学',
    languages: '语言学',
    literature: '文学',
    philosophy: '哲学',
    psychology: '心理学',
    sociology: '社会学',
    architecture: '建筑学',
    design: '设计',
    music: '音乐',
  },
  opportunitiesContent: {
    '1': {
      description: "我们正在寻找一位热爱网页开发的学生加入我们的工程团队。您将参与具有直接产品影响的真实项目，与高级工程师合作开发前端和后端功能。需要掌握JavaScript/TypeScript和网页基础知识。提供月薪补贴，表现优秀者有机会在实习结束后转为正式员工。",
      location: "米兰, IT • 远程",
      about: "TechNova Solutions是一家总部位于米兰的快速成长的金融科技初创公司。我们致力于利用人工智能和区块链技术革新数字支付领域。我们的团队由来自整个欧洲的50多名工程师组成，共同对技术和我们工作的社会影响充满热情。",
    },
    '2': {
      description: "加入我们，参加为期一周的设计思维和实际原型制作密集培训。课程包括上午的理论学习、下午由行业导师带领的实践工作坊，以及在合作企业评审团面前的最终展示。免费参加，提供奖学金。",
      location: "米兰, IT • 混合",
      about: "Creative Hub Milan是一个致力于设计文化和应用创意的创新中心。每年我们通过密集工作坊和与行业专业人士的指导计划培训数百名年轻设计师。我们与80多家意大利和国际公司合作。",
    },
    '3': {
      description: "分析复杂数据集以优化信用流程和风险管理。职责包括在Python中处理数据、在Tableau中创建仪表板，以及每周向管理人员汇报。需要具备数据分析经验和SQL知识。固定期限合同，有续签可能。",
      location: "罗马, IT • 线下",
      about: "Fintech Alpha是一家专注于信用风险管理的金融科技公司。我们使用先进的统计模型和机器学习来优化信用评估流程，在意大利各地与200多家银行合作伙伴合作。成立于2018年，目前拥有120多名员工。",
    },
    '4': {
      description: "一个探讨人工智能在商业、法律和社会背景下伦理影响的高级培训课程。课程以混合模式进行，包含6个模块，每个模块4周，包括与科技行业领先企业的案例研究。欧洲认可资质。",
      location: "米兰, IT • 兼职",
      about: "米兰理工大学是欧洲顶尖技术大学之一，推出这一致力于人工智能伦理挑战的卓越项目。该项目在欧洲层面获得认可，提供进入30多个国家校友网络的机会，就业率达94%。",
    },
  },
};

const es: Translations = {
  nav: {
    uni: 'Uni',
    home: 'Inicio',
    network: 'Red',
    profile: 'Perfil',
  },
  home: {
    forYou: 'Para ti',
    explore: 'Explorar',
    searchPlaceholder: 'Buscar oportunidades…',
    filters: 'Filtros',
    reset: 'Restablecer',
    noOpportunities: 'No se encontraron oportunidades',
    publishedDaysAgo: 'Publicado hace 3 días',
    goToOpportunity: 'Ir a la oportunidad',
    linkUnavailable: 'Enlace no disponible',
    applyFilters: 'Aplicar filtros',
    filterType: 'Tipo',
    filterMode: 'Modalidad',
    filterLevel: 'Nivel',
    filterRemote: 'Remoto',
    filterInPerson: 'Presencial',
    filterHybrid: 'Híbrido',
    filterJunior: 'Junior',
    filterSenior: 'Senior',
    filterFullTime: 'Tiempo completo',
    filterPartTime: 'Tiempo parcial',
    filterWorkshop: 'Taller',
    filterInternship: 'Pasantía',
    filterEducation: 'Educación',
  },
  notifications: {
    title: 'Notificaciones',
    today: 'Hoy',
    yesterday: 'Ayer',
    earlier: 'Anteriores',
    empty: 'Sin notificaciones',
  },
  uni: {
    title: 'Universidades',
    notFound: 'Universidad no encontrada',
    whyRecommended: 'Por qué se recomienda para ti',
    recommendedDesc: 'Según tu perfil e intereses, esta universidad ofrece oportunidades alineadas con tu trayectoria.',
    statAlumni: 'Alumni',
    statRating: 'Valoración',
    statOpportunities: 'Oportunidades',
    statActiveStudents: 'Estudiantes activos',
    availableCourses: 'Cursos disponibles',
    visitSite: 'Visitar sitio oficial',
    opportunities: 'oportunidades',
    courseTriennale: 'Grado',
    courseMagistrale: 'Máster',
    courseCicloUnico: 'Ciclo Único',
  },
  profile: {
    title: 'Perfil',
    saved: 'Guardados',
    savedUni: 'Universidades',
    savedOpp: 'Oportunidades',
    settings: 'Configuración',
    preferences: 'Preferencias',
    notifications: 'Notificaciones',
    darkMode: 'Modo oscuro',
    language: 'Idioma',
    security: 'Seguridad',
    privacy: 'Privacidad',
    securityPrivacy: 'Seguridad y Privacidad',
    helpSupport: 'Ayuda y Soporte',
    info: 'Información',
    logout: 'Cerrar sesión',
    editProfile: 'Editar Perfil',
    name: 'Nombre',
    bio: 'Bio',
    course: 'Curso de estudios',
    year: 'Año',
    skills: 'Habilidades',
    save: 'Guardar',
    saving: 'Guardando...',
    cancel: 'Cancelar',
    done: 'Listo',
    add: 'Agregar',
    addSkills: 'Agregar habilidades',
    tapToChangePhoto: 'Toca para cambiar foto',
    bioPlaceholder: 'Cuéntanos sobre ti...',
    coursePlaceholder: 'ej. Ingeniería Informática',
    yearPlaceholder: 'ej. 3',
    noSavedOpportunities: 'Sin oportunidades guardadas aún',
    noSavedUniversities: 'Sin universidades guardadas aún',
    exploreOpportunities: 'Explorar oportunidades',
    exploreUniversities: 'Explorar universidades',
    searchPathmates: 'Buscar Pathmates...',
    noResults: 'No se encontraron resultados',
    noPathmates: 'Aún no tienes Pathmates',
    suggestedPathmates: 'Pathmates sugeridos',
    yearSuffix: 'er año',
    universityHidden: 'Universidad oculta',
    deletingAccount: 'Eliminando...',
    deleteIrreversibleMsg: 'Esta acción es irreversible. Todos tus datos serán eliminados permanentemente.',
  },
  privacy: {
    title: 'Privacidad',
    profileVisibility: 'Visibilidad del perfil',
    whoCanSeeProfile: 'Quién puede ver tu perfil',
    whoCanSeeSkills: 'Quién puede ver tus habilidades',
    whoCanSeeUniversity: 'Quién puede ver tu universidad',
    activity: 'Actividad',
    whoCanSeeSavedOpps: 'Quién puede ver tus oportunidades guardadas',
    whoCanSeePathmates: 'Quién puede ver tus Pathmates',
    whoCanMessage: 'Quién puede enviarte mensajes',
    dataPersonalization: 'Datos y personalización',
    allowRecommendations: 'Permitir recomendaciones personalizadas',
    improveSuggestions: 'Mejora las sugerencias para ti',
    shareAnonymousData: 'Compartir datos anónimos para mejorar la app',
    noPersonalData: 'No se comparten datos personales',
    downloadData: 'Descargar tus datos',
    deleteAccount: 'Eliminar cuenta',
    everyone: 'Todos',
    nobody: 'Nadie',
  },
  security: {
    title: 'Seguridad',
    changePassword: 'Cambiar contraseña',
    twoFactor: 'Autenticación de dos factores',
    activeSessions: 'Sesiones activas',
    manageDevices: 'Gestionar dispositivos conectados',
    disconnectAll: 'Desconectar todos los dispositivos',
    changePasswordTitle: 'Cambiar contraseña',
    currentPassword: 'Contraseña actual',
    newPassword: 'Nueva contraseña',
    confirmPassword: 'Confirmar contraseña',
    passwordPlaceholder: 'Ingresa la contraseña',
    newPasswordPlaceholder: 'Al menos 6 caracteres',
    confirmPasswordPlaceholder: 'Repite la nueva contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    passwordMismatch: 'Las contraseñas no coinciden',
    passwordTooShort: 'La contraseña debe tener al menos 6 caracteres',
    updatePassword: 'Actualizar contraseña',
    forgotPasswordTitle: 'Contraseña olvidada',
    forgotPasswordDesc: 'Ingresa tu email. Te enviaremos un código de verificación.',
    emailLabel: 'Email',
    emailPlaceholder: 'Tu email',
    sendCode: 'Enviar código',
    codeSentDesc: 'Enviamos un código a {email}. Revisa también el spam.',
    verificationCode: 'Código de verificación',
    codePlaceholder: '123456',
    resetPassword: 'Restablecer contraseña',
    backToLogin: 'Volver a cambiar contraseña',
    passwordUpdated: '¡Contraseña actualizada con éxito!',
    codeResent: 'Nuevo código enviado',
    resendCode: 'Reenviar código',
  },
  help: {
    title: 'Ayuda y Soporte',
    helpCenter: 'Centro de ayuda',
    browseFaq: 'Navega las preguntas frecuentes',
    contactUs: 'Contáctanos',
    writeForHelp: 'Escríbenos para obtener asistencia',
    reportProblem: 'Reportar un problema',
    termsOfService: 'Términos de servicio',
    privacyPolicy: 'Política de privacidad',
  },
  info: {
    title: 'Información',
    appVersion: 'Versión de la app',
    whatsNew: 'Novedades',
    discoverFeatures: 'Descubre las últimas funciones',
    openSourceLicenses: 'Licencias de código abierto',
    followSocial: 'Síguenos en redes sociales',
  },
  networking: {
    messages: 'Mensajes',
    explore: 'Explorar',
    noMessages: 'Sin mensajes aún',
    connectExplore: '¡Conéctate con otros estudiantes en la sección Explorar!',
    writeMessage: 'Escribe un mensaje...',
    shareWithCommunity: 'Comparte algo con la comunidad...',
    addPhoto: 'Agregar foto',
    publish: 'Publicar',
    noComments: 'Sin comentarios aún',
    writeComment: 'Escribe un comentario...',
    group: 'grupo',
    createGroup: 'Crear grupo',
    noMessagePreview: 'Sin mensaje',
    conversationsSingular: 'conversación',
    conversationsPlural: 'conversaciones',
  },
  userProfile: {
    notFound: 'Perfil no encontrado',
    sendMessage: 'Enviar mensaje',
    connected: 'Conectado',
    requestSent: 'Solicitud enviada',
    connect: 'Conectar',
    bio: 'Bio',
    skills: 'Habilidades',
  },
  common: {
    loading: 'Cargando...',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    typeToConfirm: 'Escribe "{input}" para confirmar',
    error: 'Error',
  },
  group: {
    newGroup: 'Nuevo Grupo',
    newChat: 'Nueva chat',
    groupName: 'Nombre del grupo',
    description: 'Descripción (opcional)',
    selectedCount: '{count} seleccionados',
    minTwo: '(mínimo 2)',
    searchFriends: 'Buscar amigos...',
    searchUsers: 'Buscar usuarios...',
    noFriendsFound: 'Sin amigos encontrados',
    noUsersFound: 'No se encontró ningún usuario',
    noUsersAvailable: 'Sin usuarios disponibles',
    startChat: 'Iniciar chat',
    autoNameWith: 'Grupo con',
    autoNameOthers: 'y otros',
    unsavedChanges: '¿Seguro que quieres salir? Los cambios no guardados se perderán.',
    errorLoadFriends: 'Error al cargar amigos',
    errorLoadImage: 'Error al cargar la imagen',
    errorCreate: 'No se pudo crear el grupo, inténtalo de nuevo',
    options: 'Opciones del grupo',
    memberCount: 'miembros',
    createdByPrefix: 'Creado por',
    onDate: 'el',
    editPhoto: 'Editar foto del grupo',
    updatingPhoto: 'Actualizando...',
    addMembers: 'Agregar miembros',
    viewMembers: 'Ver miembros',
    dangerZone: 'Zona de peligro',
    leaveGroup: 'Salir del grupo',
    deleteGroup: 'Eliminar grupo',
    photoUpdated: 'Foto del grupo actualizada',
    errorUpdatePhoto: 'Error al actualizar la foto',
    leftGroup: 'Saliste del grupo',
    groupDeleted: 'Grupo eliminado',
    membersAdded: 'Miembros añadidos al grupo',
    memberRemoved: 'Miembro eliminado del grupo',
    leaveConfirmTitle: 'Salir del grupo',
    leaveConfirmMsgPrefix: '¿Seguro que quieres salir del grupo',
    leaveConfirmBtn: 'Salir',
    deleteConfirmMsg: 'Esta acción es irreversible. Todos los mensajes serán eliminados y los miembros serán notificados.',
    deleteConfirmBtn: 'Eliminar',
    deleteConfirmInput: 'ELIMINA',
    allFriendsInGroup: 'Todos tus amigos ya están en el grupo',
    alreadyInGroup: 'Ya en el grupo',
    creator: 'Creador',
    you: 'Tú',
    remove: 'Eliminar',
    removeConfirmTitle: 'Eliminar miembro',
    removeConfirmMsgPrefix: '¿Seguro que quieres eliminar a',
    removeConfirmMsgSuffix: 'del grupo?',
    removeConfirmBtn: 'Eliminar',
    newChatDesc: 'Inicia una conversación con alguien',
    createGroupDesc: 'Crea un grupo con tus amigos',
  },
  skillLabels: {
    computer_science: 'Informática',
    data_science: 'Ciencia de Datos',
    machine_learning: 'Aprendizaje Automático',
    web_development: 'Desarrollo Web',
    mobile_development: 'Desarrollo Móvil',
    cybersecurity: 'Ciberseguridad',
    cloud_computing: 'Computación en la Nube',
    devops: 'DevOps',
    ui_ux_design: 'Diseño UI/UX',
    graphic_design: 'Diseño Gráfico',
    marketing: 'Marketing',
    communication: 'Comunicación',
    economics: 'Economía',
    finance: 'Finanzas',
    management: 'Gestión',
    entrepreneurship: 'Emprendimiento',
    engineering: 'Ingeniería',
    mathematics: 'Matemáticas',
    physics: 'Física',
    chemistry: 'Química',
    biology: 'Biología',
    medicine: 'Medicina',
    law: 'Derecho',
    political_science: 'Ciencias Políticas',
    languages: 'Idiomas',
    literature: 'Literatura',
    philosophy: 'Filosofía',
    psychology: 'Psicología',
    sociology: 'Sociología',
    architecture: 'Arquitectura',
    design: 'Diseño',
    music: 'Música',
  },
  opportunitiesContent: {
    '1': {
      description: "Buscamos un estudiante apasionado por el desarrollo web para unirse a nuestro equipo de ingeniería. Trabajarás en proyectos reales con impacto directo en el producto, colaborando con ingenieros senior en funcionalidades front-end y back-end. Requerimos conocimiento de JavaScript/TypeScript y los fundamentos de la web. Compensación mensual y posibilidad de contratación permanente al finalizar.",
      location: "Milán, IT • Remoto",
      about: "TechNova Solutions es una startup fintech de rápido crecimiento con sede en Milán. Trabajamos para revolucionar el sector de pagos digitales con soluciones basadas en inteligencia artificial y blockchain. Nuestro equipo está compuesto por más de 50 ingenieros de toda Europa, unidos por la pasión por la tecnología y el impacto social de nuestro trabajo.",
    },
    '2': {
      description: "Únete a nosotros para una semana intensiva de Design Thinking y prototipado aplicado al mundo real. El programa incluye sesiones matutinas de teoría, tardes de workshops prácticos con mentores del sector y una presentación final ante un panel de empresas asociadas. Participación gratuita con beca disponible.",
      location: "Milán, IT • Híbrido",
      about: "Creative Hub Milan es un centro de innovación dedicado a la cultura del diseño y la creatividad aplicada. Cada año formamos a cientos de jóvenes diseñadores a través de workshops intensivos y programas de mentoría con profesionales del sector. Colaboramos con más de 80 empresas italianas e internacionales.",
    },
    '3': {
      description: "Análisis de conjuntos de datos complejos para la optimización de procesos de crédito y gestión del riesgo. El rol implica procesamiento de datos en Python, creación de dashboards en Tableau e informes semanales a los gerentes. Se requiere experiencia previa en análisis de datos y conocimiento de SQL. Contrato a término fijo con posibilidad de renovación.",
      location: "Roma, IT • Presencial",
      about: "Fintech Alpha es una empresa fintech especializada en gestión de riesgo crediticio. Utilizamos modelos estadísticos avanzados y machine learning para optimizar los procesos de evaluación de crédito, operando con más de 200 socios bancarios en toda Italia. Fundada en 2018, contamos hoy con más de 120 empleados.",
    },
    '4': {
      description: "Un programa formativo avanzado que explora las implicaciones éticas de la inteligencia artificial en contextos empresariales, legales y sociales. El curso se imparte en modalidad híbrida con 6 módulos de 4 semanas cada uno, incluidos casos de estudio con empresas líderes del sector tecnológico. Título reconocido a nivel europeo.",
      location: "Milán, IT • Tiempo parcial",
      about: "El Politecnico di Milano, una de las mejores universidades técnicas de Europa, ofrece este programa de excelencia dedicado a los desafíos éticos de la inteligencia artificial. El programa está reconocido a nivel europeo y ofrece acceso a una red de alumni en más de 30 países, con una tasa de colocación del 94%.",
    },
  },
};

const TRANSLATIONS: Record<Language, Translations> = {
  Italiano: it,
  Inglese: en,
  Cinese: zh,
  Spagnolo: es,
};

export function getSkillLabel(key: string, t: { skillLabels: Record<string, string> }): string {
  return t.skillLabels[key] ?? key;
}

export function normalizePassionToKey(value: string): string {
  if ((SKILL_KEYS as readonly string[]).includes(value)) return value;
  for (const translations of [it, en, zh, es]) {
    for (const [key, label] of Object.entries(translations.skillLabels)) {
      if (label === value) return key;
    }
  }
  return value;
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'Italiano',
  setLanguage: () => {},
  t: it,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('Italiano');
  const t = TRANSLATIONS[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
