export type Block =
  | { kind: 'p'; text: string }
  | { kind: 'list'; items: Array<{ label?: string; text: string }> };

export type Section = { heading: string; blocks: Block[] };
export type LegalDoc = { title: string; lastUpdate: string; sections: Section[] };
export type LegalContent = { terms: LegalDoc; privacy: LegalDoc };

const it: LegalContent = {
  terms: {
    title: 'Termini di Servizio',
    lastUpdate: 'Ultimo aggiornamento: Maggio 2026',
    sections: [
      { heading: '1. Accettazione dei Termini', blocks: [{ kind: 'p', text: "Utilizzando COhA dichiari di aver letto, compreso e accettato integralmente i presenti Termini di Servizio e l'Informativa sulla Privacy. Se non accetti questi termini, non puoi utilizzare la piattaforma. L'utilizzo continuato del servizio dopo eventuali modifiche costituisce accettazione delle nuove condizioni." }] },
      { heading: '2. Descrizione del Servizio', blocks: [{ kind: 'p', text: "COhA è una piattaforma di networking per studenti universitari italiani che offre: corrispondenza personalizzata con opportunità accademiche e professionali (stage, borse di studio, eventi, scambi), funzionalità social (post, commenti, amicizie), messaggistica privata e un sistema di profilazione basato su questionario. Il servizio è fornito \"così com'è\" e può essere modificato o interrotto in qualsiasi momento." }] },
      { heading: '3. Requisiti di Accesso', blocks: [{ kind: 'list', items: [{ text: 'Devi avere almeno 18 anni per registrarti e utilizzare COhA.' }, { text: 'Devi fornire informazioni accurate e veritiere durante la registrazione.' }, { text: 'Un indirizzo e-mail valido e verificabile è obbligatorio.' }, { text: 'Non puoi creare più di un account per persona.' }] }] },
      { heading: '4. Account e Sicurezza', blocks: [{ kind: 'p', text: 'Sei responsabile di:' }, { kind: 'list', items: [{ text: 'Mantenere riservate le credenziali di accesso al tuo account' }, { text: 'Tutte le attività svolte tramite il tuo account' }, { text: 'Notificarci immediatamente di qualsiasi accesso non autorizzato a [EMAIL SICUREZZA]' }] }, { kind: 'p', text: 'Non condividere le tue credenziali con terzi. COhA non ti chiederà mai la password tramite e-mail.' }] },
      { heading: "5. Contenuti dell'Utente", blocks: [{ kind: 'p', text: "Caricando o pubblicando contenuti su COhA (post, commenti, messaggi, foto profilo), concedi a COhA una licenza non esclusiva, gratuita e mondiale per ospitare, visualizzare e distribuire tali contenuti esclusivamente ai fini dell'erogazione del servizio. Rimani il proprietario dei tuoi contenuti. Sei responsabile di garantire di avere i diritti necessari sui contenuti che pubblichi." }] },
      { heading: '6. Contenuti e Comportamenti Vietati', blocks: [{ kind: 'p', text: 'È vietato utilizzare COhA per:' }, { kind: 'list', items: [{ text: 'Pubblicare contenuti illegali, diffamatori, discriminatori, osceni o che violano i diritti di terzi' }, { text: 'Molestare, minacciare o perseguitare altri utenti' }, { text: 'Diffondere spam, messaggi pubblicitari non richiesti o phishing' }, { text: 'Impersonare altre persone o creare account falsi' }, { text: 'Tentare di accedere a dati di altri utenti senza autorizzazione' }, { text: 'Utilizzare sistemi automatizzati (bot, scraper) senza previa autorizzazione scritta' }, { text: 'Interferire con il funzionamento della piattaforma' }] }] },
      { heading: '7. Sospensione e Cancellazione', blocks: [{ kind: 'p', text: "Ci riserviamo il diritto di sospendere o cancellare il tuo account, senza preavviso, in caso di violazione dei presenti Termini. Puoi cancellare il tuo account in qualsiasi momento dalle impostazioni del profilo. Alla cancellazione, i tuoi dati saranno eliminati secondo quanto previsto nell'Informativa sulla Privacy." }] },
      { heading: '8. Proprietà Intellettuale', blocks: [{ kind: 'p', text: "Il logo, il nome COhA, il design, il codice sorgente e tutti gli elementi originali della piattaforma sono di proprietà di [RAGIONE SOCIALE] e protetti dalla normativa sul diritto d'autore. È vietata la riproduzione, distribuzione o modifica senza previa autorizzazione scritta." }] },
      { heading: '9. Limitazione di Responsabilità', blocks: [{ kind: 'p', text: "COhA non garantisce la continuità, l'accuratezza o l'idoneità dei contenuti presenti sulla piattaforma, incluse le opportunità pubblicate. Non siamo responsabili per danni diretti, indiretti o consequenziali derivanti dall'uso o dall'impossibilità di uso del servizio, nei limiti consentiti dalla legge applicabile. Le opportunità pubblicate su COhA sono fornite da terzi; non ne garantiamo l'accuratezza o la disponibilità." }] },
      { heading: '10. Legge Applicabile e Foro Competente', blocks: [{ kind: 'p', text: "I presenti Termini sono regolati dalla legge italiana. Per qualsiasi controversia derivante dall'uso di COhA, le parti concordano sulla competenza esclusiva del Tribunale di [CITTÀ], fatto salvo il diritto del consumatore di adire il tribunale del proprio luogo di residenza." }] },
      { heading: '11. Contatti', blocks: [{ kind: 'p', text: 'Per qualsiasi domanda sui presenti Termini: [EMAIL LEGALE]' }] },
    ],
  },
  privacy: {
    title: 'Informativa sulla Privacy',
    lastUpdate: 'Ultimo aggiornamento: Maggio 2026',
    sections: [
      { heading: '1. Titolare del Trattamento', blocks: [{ kind: 'p', text: "Il Titolare del Trattamento dei dati personali è [RAGIONE SOCIALE / NOME E COGNOME DEL TITOLARE], con sede in [INDIRIZZO], P.IVA/C.F. [CODICE FISCALE/P.IVA]. Per qualsiasi richiesta relativa al trattamento dei tuoi dati personali, puoi contattarci all'indirizzo e-mail: [EMAIL PRIVACY]." }] },
      { heading: '2. Dati Personali Raccolti', blocks: [{ kind: 'p', text: "COhA raccoglie i seguenti dati personali forniti direttamente dall'utente:" }, { kind: 'list', items: [{ label: 'Dati identificativi', text: ': nome, cognome, indirizzo e-mail, numero di telefono (opzionale)' }, { label: 'Dati accademici', text: ': università, corso di studi, anno di corso, media voti (GPA, in forma anonimizzata per fasce)' }, { label: 'Dati di profilo', text: ': interessi, obiettivi professionali, lingue parlate, disponibilità a trasferirsi, livello di inglese, data di nascita' }, { label: 'Contenuti generati', text: ': post, commenti, messaggi privati, foto profilo' }, { label: 'Dati tecnici', text: ': indirizzo IP, dati di sessione, preferenze di notifica' }] }, { kind: 'p', text: 'Se accedi tramite Google, riceviamo dal tuo account Google i dati che hai autorizzato a condividere (di norma: nome, cognome, indirizzo e-mail, foto profilo).' }] },
      { heading: '3. Base Legale del Trattamento', blocks: [{ kind: 'list', items: [{ label: 'Esecuzione del contratto (Art. 6(1)(b) GDPR)', text: ": per la gestione dell'account, la fornitura del servizio di matching e networking." }, { label: 'Consenso (Art. 6(1)(a) GDPR)', text: ': per la profilazione psicologica tramite questionario di onboarding (cluster tag), per l\'invio di comunicazioni di marketing (se applicabile).' }, { label: 'Legittimo interesse (Art. 6(1)(f) GDPR)', text: ': per la sicurezza della piattaforma, il rilevamento di abusi e la prevenzione di frodi.' }] }] },
      { heading: '4. Finalità del Trattamento', blocks: [{ kind: 'list', items: [{ text: "Creazione e gestione dell'account utente" }, { text: 'Erogazione del servizio di matching con opportunità accademiche e professionali' }, { text: 'Funzionalità di social networking (post, commenti, messaggi, amicizie)' }, { text: 'Profilazione per il calcolo del "cluster" (tipo di personalità professionale)' }, { text: "Invio di notifiche relative all'attività sulla piattaforma" }, { text: 'Miglioramento del servizio tramite analisi anonimizzate' }, { text: 'Adempimento di obblighi legali' }] }] },
      { heading: '5. Profilazione Automatizzata (Art. 22 GDPR)', blocks: [{ kind: 'p', text: "COhA utilizza un sistema automatizzato per calcolare il tuo \"profilo\" (cluster tag: Analista, Creativo, Leader, Imprenditore, Sociale, Explorer) basato sulle risposte al questionario di onboarding. Questo profilo influenza le opportunità che ti vengono suggerite. Hai il diritto di richiedere una revisione umana di tale classificazione e di opporti alla profilazione contattandoci all'indirizzo indicato al punto 1." }] },
      { heading: '6. Conservazione dei Dati', blocks: [{ kind: 'list', items: [{ label: 'Dati account', text: ": conservati finché l'account è attivo; cancellati entro 30 giorni dalla richiesta di cancellazione" }, { label: 'Messaggi privati', text: ": conservati per 2 anni dall'ultimo messaggio, poi eliminati automaticamente" }, { label: 'Post e commenti', text: ": conservati finché l'utente li elimina o cancella l'account" }, { label: 'Richieste di amicizia rifiutate', text: ': eliminate automaticamente dopo 30 giorni' }, { label: 'Codici di verifica e-mail', text: ': eliminati automaticamente dopo 10 minuti' }, { label: 'Log di sicurezza', text: ': conservati per 90 giorni' }] }] },
      { heading: '7. Destinatari dei Dati (Responsabili del Trattamento)', blocks: [{ kind: 'p', text: "I tuoi dati personali possono essere trasmessi ai seguenti fornitori di servizi, che agiscono come Responsabili del Trattamento ai sensi dell'Art. 28 GDPR:" }, { kind: 'list', items: [{ label: 'Cloudflare Inc.', text: ' (USA) — archiviazione di immagini caricate dagli utenti (avatar, foto post, immagini messaggi) tramite Cloudflare R2. Trasferimento verso paese terzo coperto da Clausole Contrattuali Standard (SCC). DPA incluso nei ToS di Cloudflare.' }, { label: 'Cloudinary Inc.', text: ' (USA) — ottimizzazione e trasformazione delle immagini (fallback). Trasferimento verso paese terzo coperto da Clausole Contrattuali Standard (SCC).' }, { label: 'Google LLC', text: ' (USA) — autenticazione OAuth. Trasferimento coperto da SCC/DPF.' }, { label: 'Provider hosting', text: " — [NOME PROVIDER HOSTING] per l'infrastruttura server." }, { label: 'SendGrid / Twilio', text: ' (USA) — invio di e-mail transazionali. Trasferimento coperto da SCC.' }] }] },
      { heading: '8. Cookie e Tecnologie di Tracciamento', blocks: [{ kind: 'p', text: 'COhA utilizza esclusivamente cookie tecnici essenziali per il funzionamento del servizio:' }, { kind: 'list', items: [{ label: 'refreshToken', text: ' (cookie HTTPOnly, durata 7 giorni): necessario per mantenere la sessione autenticata. Non richiede consenso in quanto essenziale.' }] }, { kind: 'p', text: 'Non utilizziamo cookie di profilazione o di tracciamento di terze parti. Non utilizziamo Google Analytics o strumenti analitici basati su cookie.' }] },
      { heading: '9. Minori', blocks: [{ kind: 'p', text: "COhA è riservato a utenti di età pari o superiore a 18 anni. Non raccogliamo consapevolmente dati personali di soggetti di età inferiore a 18 anni. Se sei genitore o tutore e ritieni che tuo figlio minorenne abbia creato un account, ti invitiamo a contattarci immediatamente all'indirizzo indicato al punto 1 per richiedere la cancellazione dei dati." }] },
      { heading: '10. I Tuoi Diritti (Artt. 15-22 GDPR)', blocks: [{ kind: 'p', text: 'Hai il diritto di:' }, { kind: 'list', items: [{ label: 'Accesso (Art. 15)', text: ': ottenere conferma del trattamento e copia dei tuoi dati' }, { label: 'Rettifica (Art. 16)', text: ': correggere dati inesatti o incompleti' }, { label: 'Cancellazione (Art. 17, "diritto all\'oblio")', text: ': richiedere la cancellazione dei tuoi dati (disponibile direttamente nelle impostazioni dell\'account)' }, { label: 'Limitazione (Art. 18)', text: ': richiedere la sospensione del trattamento' }, { label: 'Portabilità (Art. 20)', text: ': ricevere i tuoi dati in formato strutturato e leggibile da macchina' }, { label: 'Opposizione (Art. 21)', text: ': opporti al trattamento basato su legittimo interesse' }, { label: 'Revoca del consenso', text: ': revocare in qualsiasi momento il consenso prestato, senza pregiudicare la liceità del trattamento precedente' }] }, { kind: 'p', text: 'Per esercitare questi diritti, contattaci a [EMAIL PRIVACY]. Hai inoltre il diritto di proporre reclamo al Garante per la Protezione dei Dati Personali (www.garanteprivacy.it).' }] },
      { heading: "11. Modifiche all'Informativa", blocks: [{ kind: 'p', text: 'Ci riserviamo il diritto di aggiornare questa informativa. In caso di modifiche sostanziali, informeremo gli utenti tramite e-mail o notifica nella piattaforma con almeno 14 giorni di preavviso.' }] },
    ],
  },
};

const en: LegalContent = {
  terms: {
    title: 'Terms of Service',
    lastUpdate: 'Last updated: May 2026',
    sections: [
      { heading: '1. Acceptance of Terms', blocks: [{ kind: 'p', text: 'By using COhA you declare that you have read, understood, and fully accepted these Terms of Service and the Privacy Policy. If you do not accept these terms, you may not use the platform. Continued use of the service after any changes constitutes acceptance of the new conditions.' }] },
      { heading: '2. Service Description', blocks: [{ kind: 'p', text: "COhA is a networking platform for Italian university students that offers: personalized matching with academic and professional opportunities (internships, scholarships, events, exchanges), social features (posts, comments, friendships), private messaging, and a questionnaire-based profiling system. The service is provided 'as is' and may be modified or discontinued at any time." }] },
      { heading: '3. Access Requirements', blocks: [{ kind: 'list', items: [{ text: 'You must be at least 18 years old to register and use COhA.' }, { text: 'You must provide accurate and truthful information during registration.' }, { text: 'A valid and verifiable email address is required.' }, { text: 'You may not create more than one account per person.' }] }] },
      { heading: '4. Account & Security', blocks: [{ kind: 'p', text: 'You are responsible for:' }, { kind: 'list', items: [{ text: 'Keeping your account login credentials confidential' }, { text: 'All activities conducted through your account' }, { text: 'Notifying us immediately of any unauthorized access to [SECURITY EMAIL]' }] }, { kind: 'p', text: 'Do not share your credentials with third parties. COhA will never ask for your password via email.' }] },
      { heading: '5. User Content', blocks: [{ kind: 'p', text: 'By uploading or publishing content on COhA (posts, comments, messages, profile photos), you grant COhA a non-exclusive, royalty-free, worldwide license to host, display, and distribute such content solely for the purpose of providing the service. You remain the owner of your content. You are responsible for ensuring you have the necessary rights to the content you publish.' }] },
      { heading: '6. Prohibited Content & Behavior', blocks: [{ kind: 'p', text: 'It is prohibited to use COhA to:' }, { kind: 'list', items: [{ text: 'Post illegal, defamatory, discriminatory, obscene content, or content that violates third-party rights' }, { text: 'Harass, threaten, or stalk other users' }, { text: 'Spread spam, unsolicited advertising, or phishing' }, { text: 'Impersonate other people or create fake accounts' }, { text: "Attempt to access other users' data without authorization" }, { text: 'Use automated systems (bots, scrapers) without prior written authorization' }, { text: 'Interfere with the functioning of the platform' }] }] },
      { heading: '7. Suspension & Deletion', blocks: [{ kind: 'p', text: 'We reserve the right to suspend or delete your account, without notice, in case of violation of these Terms. You may delete your account at any time from the profile settings. Upon deletion, your data will be erased as set out in the Privacy Policy.' }] },
      { heading: '8. Intellectual Property', blocks: [{ kind: 'p', text: 'The logo, the name COhA, the design, the source code, and all original elements of the platform are owned by [COMPANY NAME] and protected by copyright law. Reproduction, distribution, or modification without prior written authorization is prohibited.' }] },
      { heading: '9. Limitation of Liability', blocks: [{ kind: 'p', text: 'COhA does not guarantee the continuity, accuracy, or suitability of the content on the platform, including published opportunities. We are not responsible for direct, indirect, or consequential damages arising from the use or inability to use the service, to the extent permitted by applicable law. The opportunities published on COhA are provided by third parties; we do not guarantee their accuracy or availability.' }] },
      { heading: '10. Applicable Law & Jurisdiction', blocks: [{ kind: 'p', text: "These Terms are governed by Italian law. For any dispute arising from the use of COhA, the parties agree on the exclusive jurisdiction of the Court of [CITY], without prejudice to the consumer's right to bring proceedings before the court of their place of residence." }] },
      { heading: '11. Contact', blocks: [{ kind: 'p', text: 'For any questions about these Terms: [LEGAL EMAIL]' }] },
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    lastUpdate: 'Last updated: May 2026',
    sections: [
      { heading: '1. Data Controller', blocks: [{ kind: 'p', text: 'The Data Controller is [COMPANY NAME / FIRST AND LAST NAME OF THE CONTROLLER], based in [ADDRESS], VAT/Tax Code [TAX CODE/VAT]. For any request regarding the processing of your personal data, you can contact us at: [PRIVACY EMAIL].' }] },
      { heading: '2. Personal Data Collected', blocks: [{ kind: 'p', text: 'COhA collects the following personal data provided directly by the user:' }, { kind: 'list', items: [{ label: 'Identification data', text: ': first name, last name, email address, phone number (optional)' }, { label: 'Academic data', text: ': university, course of study, year of study, grade average (GPA, anonymized by range)' }, { label: 'Profile data', text: ': interests, professional goals, languages spoken, willingness to relocate, English level, date of birth' }, { label: 'Generated content', text: ': posts, comments, private messages, profile photos' }, { label: 'Technical data', text: ': IP address, session data, notification preferences' }] }, { kind: 'p', text: 'If you log in via Google, we receive from your Google account the data you have authorized to share (typically: first name, last name, email address, profile photo).' }] },
      { heading: '3. Legal Basis for Processing', blocks: [{ kind: 'list', items: [{ label: 'Performance of contract (Art. 6(1)(b) GDPR)', text: ': for account management and provision of the matching and networking service.' }, { label: 'Consent (Art. 6(1)(a) GDPR)', text: ': for psychological profiling via the onboarding questionnaire (cluster tag), for sending marketing communications (if applicable).' }, { label: 'Legitimate interest (Art. 6(1)(f) GDPR)', text: ': for platform security, abuse detection, and fraud prevention.' }] }] },
      { heading: '4. Purpose of Processing', blocks: [{ kind: 'list', items: [{ text: 'Creation and management of user account' }, { text: 'Provision of matching service with academic and professional opportunities' }, { text: 'Social networking features (posts, comments, messages, friendships)' }, { text: "Profiling for 'cluster' calculation (professional personality type)" }, { text: 'Sending notifications related to platform activity' }, { text: 'Service improvement through anonymized analysis' }, { text: 'Compliance with legal obligations' }] }] },
      { heading: '5. Automated Profiling (Art. 22 GDPR)', blocks: [{ kind: 'p', text: "COhA uses an automated system to calculate your 'profile' (cluster tag: Analyst, Creative, Leader, Entrepreneur, Social, Explorer) based on responses to the onboarding questionnaire. This profile influences the opportunities suggested to you. You have the right to request a human review of this classification and to object to profiling by contacting us at the address indicated in section 1." }] },
      { heading: '6. Data Retention', blocks: [{ kind: 'list', items: [{ label: 'Account data', text: ': retained while the account is active; deleted within 30 days of a deletion request' }, { label: 'Private messages', text: ': retained for 2 years from the last message, then automatically deleted' }, { label: 'Posts and comments', text: ': retained until the user deletes them or cancels their account' }, { label: 'Rejected friend requests', text: ': automatically deleted after 30 days' }, { label: 'Email verification codes', text: ': automatically deleted after 10 minutes' }, { label: 'Security logs', text: ': retained for 90 days' }] }] },
      { heading: '7. Data Recipients (Data Processors)', blocks: [{ kind: 'p', text: 'Your personal data may be transmitted to the following service providers, acting as Data Processors pursuant to Art. 28 GDPR:' }, { kind: 'list', items: [{ label: 'Cloudflare Inc.', text: ' (USA) — storage of user-uploaded images (avatars, post photos, message images) via Cloudflare R2. Transfer to third country covered by Standard Contractual Clauses (SCC). DPA included in Cloudflare ToS.' }, { label: 'Cloudinary Inc.', text: ' (USA) — image optimization and transformation (fallback). Transfer to third country covered by Standard Contractual Clauses (SCC).' }, { label: 'Google LLC', text: ' (USA) — OAuth authentication. Transfer covered by SCC/DPF.' }, { label: 'Hosting provider', text: ' — [HOSTING PROVIDER NAME] for server infrastructure.' }, { label: 'SendGrid / Twilio', text: ' (USA) — sending transactional emails. Transfer covered by SCC.' }] }] },
      { heading: '8. Cookies & Tracking Technologies', blocks: [{ kind: 'p', text: 'COhA uses only essential technical cookies required for the service to function:' }, { kind: 'list', items: [{ label: 'refreshToken', text: ' (HTTPOnly cookie, 7 days): required to maintain the authenticated session. Does not require consent as it is essential.' }] }, { kind: 'p', text: 'We do not use profiling or third-party tracking cookies. We do not use Google Analytics or cookie-based analytics tools.' }] },
      { heading: '9. Minors', blocks: [{ kind: 'p', text: 'COhA is reserved for users aged 18 and over. We do not knowingly collect personal data from individuals under 18. If you are a parent or guardian and believe your minor child has created an account, please contact us immediately at the address indicated in section 1 to request data deletion.' }] },
      { heading: '10. Your Rights (Arts. 15-22 GDPR)', blocks: [{ kind: 'p', text: 'You have the right to:' }, { kind: 'list', items: [{ label: 'Access (Art. 15)', text: ': obtain confirmation of processing and a copy of your data' }, { label: 'Rectification (Art. 16)', text: ': correct inaccurate or incomplete data' }, { label: 'Erasure (Art. 17, "right to be forgotten")', text: ': request the deletion of your data (available directly in account settings)' }, { label: 'Restriction (Art. 18)', text: ': request the suspension of processing' }, { label: 'Portability (Art. 20)', text: ': receive your data in a structured, machine-readable format' }, { label: 'Objection (Art. 21)', text: ': object to processing based on legitimate interest' }, { label: 'Withdrawal of consent', text: ': withdraw consent at any time without affecting the lawfulness of prior processing' }] }, { kind: 'p', text: 'To exercise these rights, contact us at [PRIVACY EMAIL]. You also have the right to lodge a complaint with the Italian Data Protection Authority (www.garanteprivacy.it).' }] },
      { heading: '11. Changes to this Policy', blocks: [{ kind: 'p', text: 'We reserve the right to update this policy. In case of material changes, we will inform users via email or platform notification with at least 14 days\' notice.' }] },
    ],
  },
};

const es: LegalContent = {
  terms: {
    title: 'Términos de Servicio',
    lastUpdate: 'Última actualización: Mayo 2026',
    sections: [
      { heading: '1. Aceptación de los Términos', blocks: [{ kind: 'p', text: 'Al usar COhA, declaras haber leído, comprendido y aceptado íntegramente estos Términos de Servicio y la Política de Privacidad. Si no aceptas estos términos, no puedes utilizar la plataforma. El uso continuado del servicio después de cualquier cambio constituye la aceptación de las nuevas condiciones.' }] },
      { heading: '2. Descripción del Servicio', blocks: [{ kind: 'p', text: "COhA es una plataforma de networking para estudiantes universitarios italianos que ofrece: correspondencia personalizada con oportunidades académicas y profesionales (prácticas, becas, eventos, intercambios), funciones sociales (publicaciones, comentarios, amistades), mensajería privada y un sistema de elaboración de perfiles basado en cuestionario. El servicio se proporciona 'tal cual' y puede modificarse o interrumpirse en cualquier momento." }] },
      { heading: '3. Requisitos de Acceso', blocks: [{ kind: 'list', items: [{ text: 'Debes tener al menos 18 años para registrarte y usar COhA.' }, { text: 'Debes proporcionar información precisa y veraz durante el registro.' }, { text: 'Es obligatorio disponer de una dirección de correo electrónico válida y verificable.' }, { text: 'No puedes crear más de una cuenta por persona.' }] }] },
      { heading: '4. Cuenta y Seguridad', blocks: [{ kind: 'p', text: 'Eres responsable de:' }, { kind: 'list', items: [{ text: 'Mantener confidenciales las credenciales de acceso a tu cuenta' }, { text: 'Todas las actividades realizadas a través de tu cuenta' }, { text: 'Notificarnos inmediatamente cualquier acceso no autorizado a [EMAIL SEGURIDAD]' }] }, { kind: 'p', text: 'No compartas tus credenciales con terceros. COhA nunca te pedirá la contraseña por correo electrónico.' }] },
      { heading: '5. Contenido del Usuario', blocks: [{ kind: 'p', text: 'Al cargar o publicar contenido en COhA (publicaciones, comentarios, mensajes, fotos de perfil), otorgas a COhA una licencia no exclusiva, gratuita y mundial para alojar, mostrar y distribuir dicho contenido exclusivamente con el fin de prestar el servicio. Sigues siendo el propietario de tu contenido. Eres responsable de garantizar que tienes los derechos necesarios sobre el contenido que publicas.' }] },
      { heading: '6. Contenido y Comportamientos Prohibidos', blocks: [{ kind: 'p', text: 'Está prohibido usar COhA para:' }, { kind: 'list', items: [{ text: 'Publicar contenido ilegal, difamatorio, discriminatorio, obsceno o que viole los derechos de terceros' }, { text: 'Acosar, amenazar o perseguir a otros usuarios' }, { text: 'Difundir spam, publicidad no solicitada o phishing' }, { text: 'Suplantar la identidad de otras personas o crear cuentas falsas' }, { text: 'Intentar acceder a los datos de otros usuarios sin autorización' }, { text: 'Usar sistemas automatizados (bots, scrapers) sin autorización previa por escrito' }, { text: 'Interferir en el funcionamiento de la plataforma' }] }] },
      { heading: '7. Suspensión y Cancelación', blocks: [{ kind: 'p', text: 'Nos reservamos el derecho de suspender o eliminar tu cuenta, sin previo aviso, en caso de incumplimiento de estos Términos. Puedes eliminar tu cuenta en cualquier momento desde la configuración del perfil. Al eliminar la cuenta, tus datos serán borrados según lo establecido en la Política de Privacidad.' }] },
      { heading: '8. Propiedad Intelectual', blocks: [{ kind: 'p', text: 'El logotipo, el nombre COhA, el diseño, el código fuente y todos los elementos originales de la plataforma son propiedad de [RAZÓN SOCIAL] y están protegidos por la legislación de derechos de autor. Queda prohibida su reproducción, distribución o modificación sin autorización previa por escrito.' }] },
      { heading: '9. Limitación de Responsabilidad', blocks: [{ kind: 'p', text: 'COhA no garantiza la continuidad, exactitud o idoneidad de los contenidos de la plataforma, incluidas las oportunidades publicadas. No somos responsables de los daños directos, indirectos o consecuentes derivados del uso o de la imposibilidad de uso del servicio, en la medida permitida por la ley aplicable. Las oportunidades publicadas en COhA son proporcionadas por terceros; no garantizamos su exactitud ni disponibilidad.' }] },
      { heading: '10. Ley Aplicable y Jurisdicción', blocks: [{ kind: 'p', text: "Estos Términos se rigen por la ley italiana. Para cualquier controversia derivada del uso de COhA, las partes acuerdan la competencia exclusiva del Tribunal de [CIUDAD], sin perjuicio del derecho del consumidor a acudir al tribunal de su lugar de residencia." }] },
      { heading: '11. Contacto', blocks: [{ kind: 'p', text: 'Para cualquier consulta sobre estos Términos: [EMAIL LEGAL]' }] },
    ],
  },
  privacy: {
    title: 'Política de Privacidad',
    lastUpdate: 'Última actualización: Mayo 2026',
    sections: [
      { heading: '1. Responsable del Tratamiento', blocks: [{ kind: 'p', text: 'El Responsable del Tratamiento de los datos personales es [RAZÓN SOCIAL / NOMBRE Y APELLIDOS DEL RESPONSABLE], con sede en [DIRECCIÓN], NIF/CIF [CÓDIGO FISCAL/NIF]. Para cualquier solicitud relativa al tratamiento de sus datos personales, puede contactarnos en: [EMAIL PRIVACIDAD].' }] },
      { heading: '2. Datos Personales Recopilados', blocks: [{ kind: 'p', text: 'COhA recopila los siguientes datos personales proporcionados directamente por el usuario:' }, { kind: 'list', items: [{ label: 'Datos identificativos', text: ': nombre, apellidos, dirección de correo electrónico, número de teléfono (opcional)' }, { label: 'Datos académicos', text: ': universidad, carrera, año de estudios, nota media (GPA, anonimizada por tramos)' }, { label: 'Datos de perfil', text: ': intereses, objetivos profesionales, idiomas hablados, disponibilidad para trasladarse, nivel de inglés, fecha de nacimiento' }, { label: 'Contenido generado', text: ': publicaciones, comentarios, mensajes privados, fotos de perfil' }, { label: 'Datos técnicos', text: ': dirección IP, datos de sesión, preferencias de notificación' }] }, { kind: 'p', text: 'Si accedes a través de Google, recibimos de tu cuenta de Google los datos que hayas autorizado a compartir (normalmente: nombre, apellidos, dirección de correo electrónico, foto de perfil).' }] },
      { heading: '3. Base Jurídica del Tratamiento', blocks: [{ kind: 'list', items: [{ label: 'Ejecución del contrato (Art. 6(1)(b) RGPD)', text: ': para la gestión de la cuenta y la prestación del servicio de matching y networking.' }, { label: 'Consentimiento (Art. 6(1)(a) RGPD)', text: ': para la elaboración de perfiles psicológicos mediante cuestionario de incorporación (cluster tag), para el envío de comunicaciones de marketing (si procede).' }, { label: 'Interés legítimo (Art. 6(1)(f) RGPD)', text: ': para la seguridad de la plataforma, la detección de abusos y la prevención del fraude.' }] }] },
      { heading: '4. Finalidad del Tratamiento', blocks: [{ kind: 'list', items: [{ text: 'Creación y gestión de la cuenta de usuario' }, { text: 'Prestación del servicio de matching con oportunidades académicas y profesionales' }, { text: 'Funciones de red social (publicaciones, comentarios, mensajes, amistades)' }, { text: "Elaboración de perfiles para el cálculo del 'cluster' (tipo de personalidad profesional)" }, { text: 'Envío de notificaciones relacionadas con la actividad en la plataforma' }, { text: 'Mejora del servicio mediante análisis anonimizados' }, { text: 'Cumplimiento de obligaciones legales' }] }] },
      { heading: '5. Elaboración Automatizada de Perfiles (Art. 22 RGPD)', blocks: [{ kind: 'p', text: "COhA utiliza un sistema automatizado para calcular tu 'perfil' (cluster tag: Analista, Creativo, Líder, Emprendedor, Social, Explorer) basado en las respuestas al cuestionario de incorporación. Este perfil influye en las oportunidades que se te sugieren. Tienes derecho a solicitar una revisión humana de esta clasificación y a oponerte a la elaboración de perfiles contactándonos en la dirección indicada en el punto 1." }] },
      { heading: '6. Conservación de los Datos', blocks: [{ kind: 'list', items: [{ label: 'Datos de cuenta', text: ': conservados mientras la cuenta esté activa; eliminados en un plazo de 30 días a partir de la solicitud de eliminación' }, { label: 'Mensajes privados', text: ': conservados durante 2 años desde el último mensaje, y luego eliminados automáticamente' }, { label: 'Publicaciones y comentarios', text: ': conservados hasta que el usuario los elimine o cancele su cuenta' }, { label: 'Solicitudes de amistad rechazadas', text: ': eliminadas automáticamente después de 30 días' }, { label: 'Códigos de verificación de correo electrónico', text: ': eliminados automáticamente después de 10 minutos' }, { label: 'Registros de seguridad', text: ': conservados durante 90 días' }] }] },
      { heading: '7. Destinatarios de los Datos (Encargados del Tratamiento)', blocks: [{ kind: 'p', text: 'Tus datos personales pueden ser transmitidos a los siguientes proveedores de servicios, que actúan como Encargados del Tratamiento en virtud del Art. 28 RGPD:' }, { kind: 'list', items: [{ label: 'Cloudflare Inc.', text: ' (EE.UU.) — almacenamiento de imágenes subidas por usuarios (avatares, fotos de publicaciones, imágenes de mensajes) a través de Cloudflare R2. Transferencia a país tercero cubierta por Cláusulas Contractuales Estándar (CCE). DPA incluido en los ToS de Cloudflare.' }, { label: 'Cloudinary Inc.', text: ' (EE.UU.) — optimización y transformación de imágenes (fallback). Transferencia a país tercero cubierta por Cláusulas Contractuales Estándar (CCE).' }, { label: 'Google LLC', text: ' (EE.UU.) — autenticación OAuth. Transferencia cubierta por CCE/DPF.' }, { label: 'Proveedor de alojamiento', text: ' — [NOMBRE DEL PROVEEDOR] para la infraestructura de servidores.' }, { label: 'SendGrid / Twilio', text: ' (EE.UU.) — envío de correos electrónicos transaccionales. Transferencia cubierta por CCE.' }] }] },
      { heading: '8. Cookies y Tecnologías de Seguimiento', blocks: [{ kind: 'p', text: 'COhA utiliza únicamente cookies técnicas esenciales necesarias para el funcionamiento del servicio:' }, { kind: 'list', items: [{ label: 'refreshToken', text: ' (cookie HTTPOnly, 7 días): necesario para mantener la sesión autenticada. No requiere consentimiento por ser esencial.' }] }, { kind: 'p', text: 'No utilizamos cookies de perfilado ni de seguimiento de terceros. No utilizamos Google Analytics ni herramientas analíticas basadas en cookies.' }] },
      { heading: '9. Menores', blocks: [{ kind: 'p', text: 'COhA está reservado a usuarios de 18 años o más. No recopilamos conscientemente datos personales de menores de 18 años. Si eres padre, madre o tutor y crees que tu hijo menor ha creado una cuenta, te pedimos que nos contactes inmediatamente en la dirección indicada en el punto 1 para solicitar la eliminación de los datos.' }] },
      { heading: '10. Tus Derechos (Arts. 15-22 RGPD)', blocks: [{ kind: 'p', text: 'Tienes derecho a:' }, { kind: 'list', items: [{ label: 'Acceso (Art. 15)', text: ': obtener confirmación del tratamiento y una copia de tus datos' }, { label: 'Rectificación (Art. 16)', text: ': corregir datos inexactos o incompletos' }, { label: 'Supresión (Art. 17, "derecho al olvido")', text: ': solicitar la eliminación de tus datos (disponible directamente en la configuración de la cuenta)' }, { label: 'Limitación (Art. 18)', text: ': solicitar la suspensión del tratamiento' }, { label: 'Portabilidad (Art. 20)', text: ': recibir tus datos en formato estructurado y legible por máquina' }, { label: 'Oposición (Art. 21)', text: ': oponerte al tratamiento basado en el interés legítimo' }, { label: 'Revocación del consentimiento', text: ': revocar en cualquier momento el consentimiento prestado, sin perjuicio de la licitud del tratamiento anterior' }] }, { kind: 'p', text: 'Para ejercer estos derechos, contáctanos en [EMAIL PRIVACIDAD]. También tienes derecho a presentar una reclamación ante la Autoridad Garante de Protección de Datos italiana (www.garanteprivacy.it).' }] },
      { heading: '11. Cambios en esta Política', blocks: [{ kind: 'p', text: 'Nos reservamos el derecho de actualizar esta política. En caso de cambios sustanciales, informaremos a los usuarios por correo electrónico o notificación en la plataforma con al menos 14 días de antelación.' }] },
    ],
  },
};

const fr: LegalContent = {
  terms: {
    title: "Conditions d'Utilisation",
    lastUpdate: 'Dernière mise à jour : Mai 2026',
    sections: [
      { heading: "1. Acceptation des Conditions", blocks: [{ kind: 'p', text: "En utilisant COhA, vous déclarez avoir lu, compris et pleinement accepté les présentes Conditions d'Utilisation et la Politique de Confidentialité. Si vous n'acceptez pas ces conditions, vous ne pouvez pas utiliser la plateforme. L'utilisation continue du service après toute modification constitue une acceptation des nouvelles conditions." }] },
      { heading: '2. Description du Service', blocks: [{ kind: 'p', text: "COhA est une plateforme de mise en réseau pour les étudiants universitaires italiens qui offre : une mise en correspondance personnalisée avec des opportunités académiques et professionnelles (stages, bourses, événements, échanges), des fonctionnalités sociales (publications, commentaires, amitiés), une messagerie privée et un système de profilage basé sur un questionnaire. Le service est fourni « tel quel » et peut être modifié ou interrompu à tout moment." }] },
      { heading: "3. Conditions d'Accès", blocks: [{ kind: 'list', items: [{ text: "Vous devez avoir au moins 18 ans pour vous inscrire et utiliser COhA." }, { text: "Vous devez fournir des informations exactes et véridiques lors de l'inscription." }, { text: "Une adresse e-mail valide et vérifiable est obligatoire." }, { text: "Vous ne pouvez pas créer plus d'un compte par personne." }] }] },
      { heading: '4. Compte et Sécurité', blocks: [{ kind: 'p', text: 'Vous êtes responsable de :' }, { kind: 'list', items: [{ text: "Garder confidentielles les informations d'identification de votre compte" }, { text: "Toutes les activités effectuées via votre compte" }, { text: "Nous notifier immédiatement de tout accès non autorisé à [EMAIL SÉCURITÉ]" }] }, { kind: 'p', text: "Ne partagez pas vos identifiants avec des tiers. COhA ne vous demandera jamais votre mot de passe par e-mail." }] },
      { heading: "5. Contenu de l'Utilisateur", blocks: [{ kind: 'p', text: "En téléchargeant ou publiant du contenu sur COhA (publications, commentaires, messages, photos de profil), vous accordez à COhA une licence non exclusive, gratuite et mondiale pour héberger, afficher et distribuer ce contenu exclusivement aux fins de la fourniture du service. Vous restez le propriétaire de votre contenu. Vous êtes responsable de vous assurer que vous disposez des droits nécessaires sur le contenu que vous publiez." }] },
      { heading: '6. Contenus et Comportements Interdits', blocks: [{ kind: 'p', text: "Il est interdit d'utiliser COhA pour :" }, { kind: 'list', items: [{ text: "Publier du contenu illégal, diffamatoire, discriminatoire, obscène ou portant atteinte aux droits de tiers" }, { text: "Harceler, menacer ou persécuter d'autres utilisateurs" }, { text: "Diffuser des spams, des publicités non sollicitées ou du phishing" }, { text: "Usurper l'identité d'autres personnes ou créer de faux comptes" }, { text: "Tenter d'accéder aux données d'autres utilisateurs sans autorisation" }, { text: "Utiliser des systèmes automatisés (bots, scrapers) sans autorisation écrite préalable" }, { text: "Interférer avec le fonctionnement de la plateforme" }] }] },
      { heading: '7. Suspension et Suppression', blocks: [{ kind: 'p', text: "Nous nous réservons le droit de suspendre ou de supprimer votre compte, sans préavis, en cas de violation des présentes Conditions. Vous pouvez supprimer votre compte à tout moment depuis les paramètres du profil. Lors de la suppression, vos données seront effacées conformément à la Politique de Confidentialité." }] },
      { heading: '8. Propriété Intellectuelle', blocks: [{ kind: 'p', text: "Le logo, le nom COhA, le design, le code source et tous les éléments originaux de la plateforme sont la propriété de [RAISON SOCIALE] et protégés par le droit d'auteur. Toute reproduction, distribution ou modification sans autorisation écrite préalable est interdite." }] },
      { heading: '9. Limitation de Responsabilité', blocks: [{ kind: 'p', text: "COhA ne garantit pas la continuité, l'exactitude ou l'adéquation du contenu présent sur la plateforme, y compris les opportunités publiées. Nous ne sommes pas responsables des dommages directs, indirects ou consécutifs résultant de l'utilisation ou de l'impossibilité d'utiliser le service, dans les limites autorisées par la loi applicable. Les opportunités publiées sur COhA sont fournies par des tiers ; nous n'en garantissons pas l'exactitude ou la disponibilité." }] },
      { heading: '10. Loi Applicable et Juridiction', blocks: [{ kind: 'p', text: "Les présentes Conditions sont régies par le droit italien. Pour tout litige découlant de l'utilisation de COhA, les parties conviennent de la compétence exclusive du Tribunal de [VILLE], sans préjudice du droit du consommateur de saisir le tribunal de son lieu de résidence." }] },
      { heading: '11. Contact', blocks: [{ kind: 'p', text: 'Pour toute question sur les présentes Conditions : [EMAIL LÉGAL]' }] },
    ],
  },
  privacy: {
    title: 'Politique de Confidentialité',
    lastUpdate: 'Dernière mise à jour : Mai 2026',
    sections: [
      { heading: '1. Responsable du Traitement', blocks: [{ kind: 'p', text: "Le Responsable du Traitement des données personnelles est [RAISON SOCIALE / NOM ET PRÉNOM DU RESPONSABLE], dont le siège est à [ADRESSE], N° TVA/SIRET [NUMÉRO FISCAL]. Pour toute demande concernant le traitement de vos données personnelles, vous pouvez nous contacter à : [EMAIL CONFIDENTIALITÉ]." }] },
      { heading: '2. Données Personnelles Collectées', blocks: [{ kind: 'p', text: "COhA collecte les données personnelles suivantes fournies directement par l'utilisateur :" }, { kind: 'list', items: [{ label: "Données d'identification", text: " : prénom, nom, adresse e-mail, numéro de téléphone (facultatif)" }, { label: 'Données académiques', text: " : université, cursus, année d'études, moyenne des notes (GPA, anonymisée par tranches)" }, { label: 'Données de profil', text: " : intérêts, objectifs professionnels, langues parlées, disponibilité à déménager, niveau d'anglais, date de naissance" }, { label: 'Contenu généré', text: " : publications, commentaires, messages privés, photos de profil" }, { label: 'Données techniques', text: " : adresse IP, données de session, préférences de notification" }] }, { kind: 'p', text: "Si vous vous connectez via Google, nous recevons de votre compte Google les données que vous avez autorisées à partager (généralement : prénom, nom, adresse e-mail, photo de profil)." }] },
      { heading: '3. Base Légale du Traitement', blocks: [{ kind: 'list', items: [{ label: 'Exécution du contrat (Art. 6(1)(b) RGPD)', text: " : pour la gestion du compte et la fourniture du service de mise en correspondance et de mise en réseau." }, { label: 'Consentement (Art. 6(1)(a) RGPD)', text: " : pour le profilage psychologique via le questionnaire d'intégration (cluster tag), pour l'envoi de communications marketing (le cas échéant)." }, { label: 'Intérêt légitime (Art. 6(1)(f) RGPD)', text: " : pour la sécurité de la plateforme, la détection des abus et la prévention des fraudes." }] }] },
      { heading: '4. Finalités du Traitement', blocks: [{ kind: 'list', items: [{ text: 'Création et gestion du compte utilisateur' }, { text: 'Fourniture du service de mise en correspondance avec des opportunités académiques et professionnelles' }, { text: 'Fonctionnalités de réseau social (publications, commentaires, messages, amitiés)' }, { text: "Profilage pour le calcul du « cluster » (type de personnalité professionnelle)" }, { text: 'Envoi de notifications relatives à l\'activité sur la plateforme' }, { text: 'Amélioration du service via des analyses anonymisées' }, { text: 'Respect des obligations légales' }] }] },
      { heading: '5. Profilage Automatisé (Art. 22 RGPD)', blocks: [{ kind: 'p', text: "COhA utilise un système automatisé pour calculer votre « profil » (cluster tag : Analyste, Créatif, Leader, Entrepreneur, Social, Explorer) basé sur les réponses au questionnaire d'intégration. Ce profil influence les opportunités qui vous sont suggérées. Vous avez le droit de demander un examen humain de cette classification et de vous opposer au profilage en nous contactant à l'adresse indiquée au point 1." }] },
      { heading: '6. Conservation des Données', blocks: [{ kind: 'list', items: [{ label: 'Données de compte', text: " : conservées tant que le compte est actif ; supprimées dans les 30 jours suivant la demande de suppression" }, { label: 'Messages privés', text: " : conservés pendant 2 ans à compter du dernier message, puis supprimés automatiquement" }, { label: 'Publications et commentaires', text: " : conservés jusqu'à ce que l'utilisateur les supprime ou ferme son compte" }, { label: "Demandes d'amitié refusées", text: " : supprimées automatiquement après 30 jours" }, { label: 'Codes de vérification par e-mail', text: " : supprimés automatiquement après 10 minutes" }, { label: 'Journaux de sécurité', text: " : conservés pendant 90 jours" }] }] },
      { heading: '7. Destinataires des Données (Sous-traitants)', blocks: [{ kind: 'p', text: "Vos données personnelles peuvent être transmises aux prestataires de services suivants, agissant en tant que Sous-traitants au sens de l'Art. 28 RGPD :" }, { kind: 'list', items: [{ label: 'Cloudflare Inc.', text: " (États-Unis) — stockage des images téléchargées par les utilisateurs (avatars, photos de publications, images de messages) via Cloudflare R2. Transfert vers un pays tiers couvert par les Clauses Contractuelles Types (CCT). DPA inclus dans les CGU de Cloudflare." }, { label: 'Cloudinary Inc.', text: " (États-Unis) — optimisation et transformation des images (solution de secours). Transfert vers un pays tiers couvert par les Clauses Contractuelles Types (CCT)." }, { label: 'Google LLC', text: " (États-Unis) — authentification OAuth. Transfert couvert par CCT/DPF." }, { label: "Fournisseur d'hébergement", text: " — [NOM DU FOURNISSEUR] pour l'infrastructure des serveurs." }, { label: 'SendGrid / Twilio', text: " (États-Unis) — envoi d'e-mails transactionnels. Transfert couvert par CCT." }] }] },
      { heading: '8. Cookies et Technologies de Suivi', blocks: [{ kind: 'p', text: "COhA utilise exclusivement des cookies techniques essentiels au fonctionnement du service :" }, { kind: 'list', items: [{ label: 'refreshToken', text: " (cookie HTTPOnly, 7 jours) : nécessaire pour maintenir la session authentifiée. Ne requiert pas de consentement car essentiel." }] }, { kind: 'p', text: "Nous n'utilisons pas de cookies de profilage ou de suivi de tiers. Nous n'utilisons pas Google Analytics ou des outils d'analyse basés sur des cookies." }] },
      { heading: '9. Mineurs', blocks: [{ kind: 'p', text: "COhA est réservé aux utilisateurs âgés de 18 ans et plus. Nous ne collectons pas sciemment de données personnelles de personnes de moins de 18 ans. Si vous êtes un parent ou tuteur et pensez que votre enfant mineur a créé un compte, nous vous invitons à nous contacter immédiatement à l'adresse indiquée au point 1 pour demander la suppression des données." }] },
      { heading: '10. Vos Droits (Arts. 15-22 RGPD)', blocks: [{ kind: 'p', text: 'Vous avez le droit de :' }, { kind: 'list', items: [{ label: 'Accès (Art. 15)', text: " : obtenir la confirmation du traitement et une copie de vos données" }, { label: 'Rectification (Art. 16)', text: " : corriger des données inexactes ou incomplètes" }, { label: 'Effacement (Art. 17, « droit à l\'oubli »)', text: " : demander la suppression de vos données (disponible directement dans les paramètres du compte)" }, { label: 'Limitation (Art. 18)', text: " : demander la suspension du traitement" }, { label: 'Portabilité (Art. 20)', text: " : recevoir vos données dans un format structuré et lisible par machine" }, { label: 'Opposition (Art. 21)', text: " : vous opposer au traitement basé sur l'intérêt légitime" }, { label: 'Retrait du consentement', text: " : retirer à tout moment le consentement donné, sans préjudice de la licéité du traitement antérieur" }] }, { kind: 'p', text: "Pour exercer ces droits, contactez-nous à [EMAIL CONFIDENTIALITÉ]. Vous avez également le droit de déposer une plainte auprès de l'Autorité italienne de protection des données (www.garanteprivacy.it)." }] },
      { heading: "11. Modifications de la Politique", blocks: [{ kind: 'p', text: "Nous nous réservons le droit de mettre à jour cette politique. En cas de modifications substantielles, nous en informerons les utilisateurs par e-mail ou notification sur la plateforme avec un préavis d'au moins 14 jours." }] },
    ],
  },
};

const zh: LegalContent = {
  terms: {
    title: '服务条款',
    lastUpdate: '最后更新：2026年5月',
    sections: [
      { heading: '1. 接受条款', blocks: [{ kind: 'p', text: '使用COhA即表示您声明已阅读、理解并完全接受本服务条款及隐私政策。如果您不接受这些条款，则不能使用本平台。在任何修改后继续使用服务即构成对新条件的接受。' }] },
      { heading: '2. 服务描述', blocks: [{ kind: 'p', text: 'COhA是一个面向意大利大学生的社交网络平台，提供：与学术和职业机会（实习、奖学金、活动、交流）的个性化匹配，社交功能（帖子、评论、好友关系），私信以及基于问卷的用户画像系统。服务"按现状"提供，可随时修改或中断。' }] },
      { heading: '3. 访问要求', blocks: [{ kind: 'list', items: [{ text: '您必须年满18岁才能注册和使用COhA。' }, { text: '您必须在注册时提供准确、真实的信息。' }, { text: '需要一个有效且可验证的电子邮件地址。' }, { text: '每人不得创建多个账户。' }] }] },
      { heading: '4. 账户与安全', blocks: [{ kind: 'p', text: '您负责：' }, { kind: 'list', items: [{ text: '保守您账户登录凭据的机密性' }, { text: '通过您账户进行的所有活动' }, { text: '立即向[安全邮箱]通知任何未经授权的访问' }] }, { kind: 'p', text: '请勿与第三方共享您的凭据。COhA绝不会通过电子邮件要求您提供密码。' }] },
      { heading: '5. 用户内容', blocks: [{ kind: 'p', text: '通过在COhA上传或发布内容（帖子、评论、消息、个人资料照片），您授予COhA一项非独占性、免版税的全球许可，以仅为提供服务之目的托管、展示和分发此类内容。您保留对内容的所有权。您有责任确保您对所发布内容拥有必要的权利。' }] },
      { heading: '6. 禁止内容与行为', blocks: [{ kind: 'p', text: '禁止使用COhA用于：' }, { kind: 'list', items: [{ text: '发布非法、诽谤、歧视性、淫秽或侵犯第三方权利的内容' }, { text: '骚扰、威胁或跟踪其他用户' }, { text: '传播垃圾邮件、未经请求的广告或网络钓鱼' }, { text: '冒充他人或创建虚假账户' }, { text: '试图在未经授权的情况下访问其他用户的数据' }, { text: '未经事先书面授权使用自动化系统（机器人、爬虫）' }, { text: '干扰平台的正常运行' }] }] },
      { heading: '7. 暂停与注销', blocks: [{ kind: 'p', text: '我们保留在违反本条款的情况下，不事先通知即暂停或删除您账户的权利。您可以随时通过个人资料设置删除您的账户。删除后，您的数据将按照隐私政策的规定予以清除。' }] },
      { heading: '8. 知识产权', blocks: [{ kind: 'p', text: '徽标、COhA名称、设计、源代码及平台的所有原创要素均归[公司名称]所有，并受版权法保护。未经事先书面授权，禁止复制、分发或修改。' }] },
      { heading: '9. 责任限制', blocks: [{ kind: 'p', text: 'COhA不保证平台内容（包括已发布机会）的连续性、准确性或适当性。在适用法律允许的范围内，我们不对因使用或无法使用服务而产生的直接、间接或后果性损害负责。COhA上发布的机会由第三方提供；我们不保证其准确性或可用性。' }] },
      { heading: '10. 适用法律与管辖权', blocks: [{ kind: 'p', text: '本条款受意大利法律管辖。对于因使用COhA而产生的任何争议，各方同意接受[城市]法院的专属管辖权，但不影响消费者在其居住地法院提起诉讼的权利。' }] },
      { heading: '11. 联系方式', blocks: [{ kind: 'p', text: '如对本条款有任何疑问，请联系：[法律邮箱]' }] },
    ],
  },
  privacy: {
    title: '隐私政策',
    lastUpdate: '最后更新：2026年5月',
    sections: [
      { heading: '1. 数据控制者', blocks: [{ kind: 'p', text: '个人数据控制者为[公司名称/控制者姓名]，地址：[地址]，税号/增值税号：[税号/增值税号]。如有任何与您个人数据处理相关的请求，可通过以下电子邮件地址联系我们：[隐私邮箱]。' }] },
      { heading: '2. 收集的个人数据', blocks: [{ kind: 'p', text: 'COhA收集用户直接提供的以下个人数据：' }, { kind: 'list', items: [{ label: '身份识别数据', text: '：姓名、电子邮件地址、电话号码（可选）' }, { label: '学术数据', text: '：大学、专业、学年、成绩平均分（GPA，按区间匿名化）' }, { label: '个人资料数据', text: '：兴趣、职业目标、所讲语言、是否愿意迁居、英语水平、出生日期' }, { label: '生成内容', text: '：帖子、评论、私信、个人资料照片' }, { label: '技术数据', text: '：IP地址、会话数据、通知偏好' }] }, { kind: 'p', text: '如果您通过Google登录，我们将从您的Google账户接收您授权共享的数据（通常为：姓名、电子邮件地址、个人资料照片）。' }] },
      { heading: '3. 处理的法律依据', blocks: [{ kind: 'list', items: [{ label: '合同履行（《通用数据保护条例》第6(1)(b)条）', text: '：用于账户管理及匹配与网络服务的提供。' }, { label: '同意（《通用数据保护条例》第6(1)(a)条）', text: '：用于通过入职问卷进行心理画像（群集标签），以及发送营销通讯（如适用）。' }, { label: '合法权益（《通用数据保护条例》第6(1)(f)条）', text: '：用于平台安全、滥用行为检测及欺诈预防。' }] }] },
      { heading: '4. 处理目的', blocks: [{ kind: 'list', items: [{ text: '创建和管理用户账户' }, { text: '提供与学术和职业机会匹配的服务' }, { text: '社交网络功能（帖子、评论、消息、好友关系）' }, { text: '用于计算"群集"（职业性格类型）的画像' }, { text: '发送与平台活动相关的通知' }, { text: '通过匿名化分析改善服务' }, { text: '遵守法律义务' }] }] },
      { heading: '5. 自动化画像（《通用数据保护条例》第22条）', blocks: [{ kind: 'p', text: 'COhA使用自动化系统根据入职问卷的回答计算您的"档案"（群集标签：分析师、创意人、领导者、企业家、社交型、探索者）。此档案影响向您推荐的机会。您有权要求对此分类进行人工审查，并可通过第1点所示地址联系我们表示反对。' }] },
      { heading: '6. 数据保留', blocks: [{ kind: 'list', items: [{ label: '账户数据', text: '：在账户活跃期间保留；在收到删除请求后30天内删除' }, { label: '私信', text: '：自最后一条消息起保留2年，之后自动删除' }, { label: '帖子和评论', text: '：保留至用户删除或注销账户' }, { label: '已拒绝的好友请求', text: '：30天后自动删除' }, { label: '电子邮件验证码', text: '：10分钟后自动删除' }, { label: '安全日志', text: '：保留90天' }] }] },
      { heading: '7. 数据接收方（数据处理者）', blocks: [{ kind: 'p', text: '您的个人数据可能被传输给以下服务提供商，他们依据《通用数据保护条例》第28条作为数据处理者行事：' }, { kind: 'list', items: [{ label: 'Cloudflare Inc.', text: '（美国）——通过Cloudflare R2存储用户上传的图片（头像、帖子照片、消息图片）。向第三国的传输由标准合同条款（SCC）覆盖。数据处理协议包含在Cloudflare服务条款中。' }, { label: 'Cloudinary Inc.', text: '（美国）——图片优化和转换（备用方案）。向第三国的传输由标准合同条款（SCC）覆盖。' }, { label: 'Google LLC', text: '（美国）——OAuth身份验证。传输由SCC/DPF覆盖。' }, { label: '托管提供商', text: '——[托管提供商名称]，提供服务器基础设施。' }, { label: 'SendGrid / Twilio', text: '（美国）——发送交易性电子邮件。传输由SCC覆盖。' }] }] },
      { heading: '8. Cookie与跟踪技术', blocks: [{ kind: 'p', text: 'COhA仅使用服务正常运行所需的基本技术cookie：' }, { kind: 'list', items: [{ label: 'refreshToken', text: '（HTTPOnly cookie，有效期7天）：维持已认证会话所必需。由于属于基本功能，无需征得同意。' }] }, { kind: 'p', text: '我们不使用第三方分析或跟踪cookie。我们不使用Google Analytics或基于cookie的分析工具。' }] },
      { heading: '9. 未成年人', blocks: [{ kind: 'p', text: 'COhA仅向18岁及以上的用户开放。我们不会故意收集18岁以下用户的个人数据。如果您是父母或监护人，且认为您的未成年子女创建了账户，请立即通过第1点所示地址联系我们，请求删除相关数据。' }] },
      { heading: '10. 您的权利（《通用数据保护条例》第15-22条）', blocks: [{ kind: 'p', text: '您享有以下权利：' }, { kind: 'list', items: [{ label: '访问权（第15条）', text: '：获取处理确认及您的数据副本' }, { label: '更正权（第16条）', text: '：更正不准确或不完整的数据' }, { label: '删除权（第17条，"被遗忘权"）', text: '：要求删除您的数据（可直接在账户设置中操作）' }, { label: '限制权（第18条）', text: '：要求暂停处理' }, { label: '可携带权（第20条）', text: '：以结构化、机器可读的格式接收您的数据' }, { label: '反对权（第21条）', text: '：反对基于合法权益的处理' }, { label: '撤回同意', text: '：随时撤回已给予的同意，而不影响此前处理的合法性' }] }, { kind: 'p', text: '如需行使这些权利，请通过[隐私邮箱]联系我们。您还有权向意大利数据保护局（www.garanteprivacy.it）提出投诉。' }] },
      { heading: '11. 政策变更', blocks: [{ kind: 'p', text: '我们保留更新本政策的权利。如有重大变更，我们将通过电子邮件或平台内通知，提前至少14天告知用户。' }] },
    ],
  },
};

import type { Language } from './language';

export const LEGAL: Record<Language, LegalContent> = {
  Italiano: it,
  Inglese: en,
  Spagnolo: es,
  Francese: fr,
  Cinese: zh,
};
